from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays

@_f
def glDrawElementsBaseVertexOES(mode, count, type, indices, basevertex) -> None: ...
@_f
def glDrawElementsInstancedBaseVertexOES(mode, count, type, indices, instancecount, basevertex) -> None: ...
@_f
def glDrawRangeElementsBaseVertexOES(mode, start, end, count, type, indices, basevertex) -> None: ...
@_f
def glMultiDrawElementsBaseVertexEXT(mode, count, type, indices, drawcount, basevertex) -> None: ...
