from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_CLAMP_TO_BORDER_OES: Incomplete
GL_TEXTURE_BORDER_COLOR_OES: Incomplete

@_f
def glGetSamplerParameterIivOES(sampler, pname, params) -> None: ...
@_f
def glGetSamplerParameterIuivOES(sampler, pname, params) -> None: ...
@_f
def glGetTexParameterIivOES(target, pname, params) -> None: ...
@_f
def glGetTexParameterIuivOES(target, pname, params) -> None: ...
@_f
def glSamplerParameterIivOES(sampler, pname, param) -> None: ...
@_f
def glSamplerParameterIuivOES(sampler, pname, param) -> None: ...
@_f
def glTexParameterIivOES(target, pname, params) -> None: ...
@_f
def glTexParameterIuivOES(target, pname, params) -> None: ...
