from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_DEPTH_RANGE: Incomplete
GL_MAX_VIEWPORTS_OES: Incomplete
GL_SCISSOR_BOX: Incomplete
GL_SCISSOR_TEST: Incomplete
GL_VIEWPORT: Incomplete
GL_VIEWPORT_BOUNDS_RANGE_OES: Incomplete
GL_VIEWPORT_INDEX_PROVOKING_VERTEX_OES: Incomplete
GL_VIEWPORT_SUBPIXEL_BITS_OES: Incomplete

@_f
def glDepthRangeArrayfvOES(first, count, v) -> None: ...
@_f
def glDepthRangeIndexedfOES(index, n, f) -> None: ...
@_f
def glDisableiOES(target, index) -> None: ...
@_f
def glEnableiOES(target, index) -> None: ...
@_f
def glGetFloati_vOES(target, index, data) -> None: ...
@_f
def glIsEnablediOES(target, index) -> None: ...
@_f
def glScissorArrayvOES(first, count, v) -> None: ...
@_f
def glScissorIndexedOES(index, left, bottom, width, height) -> None: ...
@_f
def glScissorIndexedvOES(index, v) -> None: ...
@_f
def glViewportArrayvOES(first, count, v) -> None: ...
@_f
def glViewportIndexedfOES(index, x, y, w, h) -> None: ...
@_f
def glViewportIndexedfvOES(index, v) -> None: ...
