from OpenGL.raw.GLES1._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ALL_COMPLETED_NV: Incomplete
GL_FENCE_CONDITION_NV: Incomplete
GL_FENCE_STATUS_NV: Incomplete

@_f
def glDeleteFencesNV(n, fences) -> None: ...
@_f
def glFinishFenceNV(fence) -> None: ...
@_f
def glGenFencesNV(n, fences) -> None: ...
@_f
def glGetFenceivNV(fence, pname, params) -> None: ...
@_f
def glIsFenceNV(fence) -> None: ...
@_f
def glSetFenceNV(fence, condition) -> None: ...
@_f
def glTestFenceNV(fence) -> None: ...
