from _typeshed import Incomplete

class LookupInt:
    lookup: Incomplete
    format: Incomplete
    calculation: Incomplete
    def __init__(self, lookup, format=..., calculation=None) -> None: ...
    def __int__(self) -> int: ...
    __long__ = __int__
    def __eq__(self, other): ...
    def __cmp__(self, other): ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __eq__(self, other): ...
