from OpenGL.raw.WGL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D: Incomplete
WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D: Incomplete
WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D: Incomplete
WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D: Incomplete
WGL_GENLOCK_SOURCE_EDGE_RISING_I3D: Incomplete
WGL_GENLOCK_SOURCE_EXTERNAL_FIELD_I3D: Incomplete
WGL_GENLOCK_SOURCE_EXTERNAL_SYNC_I3D: Incomplete
WGL_GENLOCK_SOURCE_EXTERNAL_TTL_I3D: Incomplete
WGL_GENLOCK_SOURCE_MULTIVIEW_I3D: Incomplete

@_f
def wglDisableGenlockI3D(hDC) -> None: ...
@_f
def wglEnableGenlockI3D(hDC) -> None: ...
@_f
def wglGenlockSampleRateI3D(hDC, uRate) -> None: ...
@_f
def wglGenlockSourceDelayI3D(hDC, uDelay) -> None: ...
@_f
def wglGenlockSourceEdgeI3D(hDC, uEdge) -> None: ...
@_f
def wglGenlockSourceI3D(hDC, uSource) -> None: ...
@_f
def wglGetGenlockSampleRateI3D(hDC, uRate) -> None: ...
@_f
def wglGetGenlockSourceDelayI3D(hDC, uDelay) -> None: ...
@_f
def wglGetGenlockSourceEdgeI3D(hDC, uEdge) -> None: ...
@_f
def wglGetGenlockSourceI3D(hDC, uSource) -> None: ...
@_f
def wglIsEnabledGenlockI3D(hDC, pFlag) -> None: ...
@_f
def wglQueryGenlockMaxSourceDelayI3D(hDC, uMaxLineDelay, uMaxPixelDelay) -> None: ...
