from OpenGL.raw.WGL._types import *
from OpenGL import arrays as arrays

@_f
def wglBeginFrameTrackingI3D() -> None: ...
@_f
def wglEndFrameTrackingI3D() -> None: ...
@_f
def wglGetFrameUsageI3D(pUsage) -> None: ...
@_f
def wglQueryFrameTrackingI3D(pFrameCount, pMissedFrames, pLastMissedUsage) -> None: ...
