from OpenGL.raw.WGL._types import *
from OpenGL import arrays as arrays

@_f
def wglDisableFrameLockI3D() -> None: ...
@_f
def wglEnableFrameLockI3D() -> None: ...
@_f
def wglIsEnabledFrameLockI3D(pFlag) -> None: ...
@_f
def wglQueryFrameLockMasterI3D(pFlag) -> None: ...
