from OpenGL.raw.WGL._types import *
from OpenGL import arrays as arrays

@_f
def wglBindDisplayColorTableEXT(id) -> None: ...
@_f
def wglCreateDisplayColorTableEXT(id) -> None: ...
@_f
def wglDestroyDisplayColorTableEXT(id) -> None: ...
@_f
def wglLoadDisplayColorTableEXT(table, length) -> None: ...
