from OpenGL.raw.GLUT.constants import *
from ctypes import *
from OpenGL.raw.GL._types import GLdouble as GLdouble, GLenum as GLenum, GLfloat as GLfloat, GLint as GLint
from _typeshed import Incomplete

__all__ = ['GLUT_ACCUM', 'GLUT_ACTIVE_ALT', 'GLUT_ACTIVE_CTRL', 'GLUT_ACTIVE_SHIFT', 'GLUT_ALPHA', 'GLUT_API_VERSION', 'GLUT_BLUE', 'GLUT_CURSOR_BOTTOM_LEFT_CORNER', 'GLUT_CURSOR_BOTTOM_RIGHT_CORNER', 'GLUT_CURSOR_BOTTOM_SIDE', 'GLUT_CURSOR_CROSSHAIR', 'GLUT_CURSOR_CYCLE', 'GLUT_CURSOR_DESTROY', 'GLUT_CURSOR_FULL_CROSSHAIR', 'GLUT_CURSOR_HELP', 'GLUT_CURSOR_INFO', 'GLUT_CURSOR_INHERIT', 'GLUT_CURSOR_LEFT_ARROW', 'GLUT_CURSOR_LEFT_RIGHT', 'GLUT_CURSOR_LEFT_SIDE', 'GLUT_CURSOR_NONE', 'GLUT_CURSOR_RIGHT_ARROW', 'GLUT_CURSOR_RIGHT_SIDE', 'GLUT_CURSOR_SPRAY', 'GLUT_CURSOR_TEXT', 'GLUT_CURSOR_TOP_LEFT_CORNER', 'GLUT_CURSOR_TOP_RIGHT_CORNER', 'GLUT_CURSOR_TOP_SIDE', 'GLUT_CURSOR_UP_DOWN', 'GLUT_CURSOR_WAIT', 'GLUT_DEPTH', 'GLUT_DEVICE_IGNORE_KEY_REPEAT', 'GLUT_DEVICE_KEY_REPEAT', 'GLUT_DISPLAY_MODE_POSSIBLE', 'GLUT_DOUBLE', 'GLUT_DOWN', 'GLUT_ELAPSED_TIME', 'GLUT_ENTERED', 'GLUT_FULLY_COVERED', 'GLUT_FULLY_RETAINED', 'GLUT_GAME_MODE_ACTIVE', 'GLUT_GAME_MODE_DISPLAY_CHANGED', 'GLUT_GAME_MODE_HEIGHT', 'GLUT_GAME_MODE_PIXEL_DEPTH', 'GLUT_GAME_MODE_POSSIBLE', 'GLUT_GAME_MODE_REFRESH_RATE', 'GLUT_GAME_MODE_WIDTH', 'GLUT_GREEN', 'GLUT_HAS_DIAL_AND_BUTTON_BOX', 'GLUT_HAS_JOYSTICK', 'GLUT_HAS_KEYBOARD', 'GLUT_HAS_MOUSE', 'GLUT_HAS_OVERLAY', 'GLUT_HAS_SPACEBALL', 'GLUT_HAS_TABLET', 'GLUT_HIDDEN', 'GLUT_INDEX', 'GLUT_INIT_DISPLAY_MODE', 'GLUT_INIT_STATE', 'GLUT_INIT_WINDOW_HEIGHT', 'GLUT_INIT_WINDOW_WIDTH', 'GLUT_INIT_WINDOW_X', 'GLUT_INIT_WINDOW_Y', 'GLUT_JOYSTICK_AXES', 'GLUT_JOYSTICK_BUTTONS', 'GLUT_JOYSTICK_BUTTON_A', 'GLUT_JOYSTICK_BUTTON_B', 'GLUT_JOYSTICK_BUTTON_C', 'GLUT_JOYSTICK_BUTTON_D', 'GLUT_JOYSTICK_POLL_RATE', 'GLUT_KEY_DOWN', 'GLUT_KEY_END', 'GLUT_KEY_F1', 'GLUT_KEY_F10', 'GLUT_KEY_F11', 'GLUT_KEY_F12', 'GLUT_KEY_F2', 'GLUT_KEY_F3', 'GLUT_KEY_F4', 'GLUT_KEY_F5', 'GLUT_KEY_F6', 'GLUT_KEY_F7', 'GLUT_KEY_F8', 'GLUT_KEY_F9', 'GLUT_KEY_HOME', 'GLUT_KEY_INSERT', 'GLUT_KEY_LEFT', 'GLUT_KEY_PAGE_DOWN', 'GLUT_KEY_PAGE_UP', 'GLUT_KEY_REPEAT_DEFAULT', 'GLUT_KEY_REPEAT_OFF', 'GLUT_KEY_REPEAT_ON', 'GLUT_KEY_RIGHT', 'GLUT_KEY_UP', 'GLUT_LAYER_IN_USE', 'GLUT_LEFT', 'GLUT_LEFT_BUTTON', 'GLUT_LUMINANCE', 'GLUT_MENU_IN_USE', 'GLUT_MENU_NOT_IN_USE', 'GLUT_MENU_NUM_ITEMS', 'GLUT_MIDDLE_BUTTON', 'GLUT_MULTISAMPLE', 'GLUT_NORMAL', 'GLUT_NORMAL_DAMAGED', 'GLUT_NOT_VISIBLE', 'GLUT_NUM_BUTTON_BOX_BUTTONS', 'GLUT_NUM_DIALS', 'GLUT_NUM_MOUSE_BUTTONS', 'GLUT_NUM_SPACEBALL_BUTTONS', 'GLUT_NUM_TABLET_BUTTONS', 'GLUT_OVERLAY', 'GLUT_OVERLAY_DAMAGED', 'GLUT_OVERLAY_POSSIBLE', 'GLUT_OWNS_JOYSTICK', 'GLUT_PARTIALLY_RETAINED', 'GLUT_RED', 'GLUT_RGB', 'GLUT_RGBA', 'GLUT_RIGHT_BUTTON', 'GLUT_SCREEN_HEIGHT', 'GLUT_SCREEN_HEIGHT_MM', 'GLUT_SCREEN_WIDTH', 'GLUT_SCREEN_WIDTH_MM', 'GLUT_SINGLE', 'GLUT_STENCIL', 'GLUT_STEREO', 'GLUT_TRANSPARENT_INDEX', 'GLUT_UP', 'GLUT_VIDEO_RESIZE_HEIGHT', 'GLUT_VIDEO_RESIZE_HEIGHT_DELTA', 'GLUT_VIDEO_RESIZE_IN_USE', 'GLUT_VIDEO_RESIZE_POSSIBLE', 'GLUT_VIDEO_RESIZE_WIDTH', 'GLUT_VIDEO_RESIZE_WIDTH_DELTA', 'GLUT_VIDEO_RESIZE_X', 'GLUT_VIDEO_RESIZE_X_DELTA', 'GLUT_VIDEO_RESIZE_Y', 'GLUT_VIDEO_RESIZE_Y_DELTA', 'GLUT_VISIBLE', 'GLUT_WINDOW_ACCUM_ALPHA_SIZE', 'GLUT_WINDOW_ACCUM_BLUE_SIZE', 'GLUT_WINDOW_ACCUM_GREEN_SIZE', 'GLUT_WINDOW_ACCUM_RED_SIZE', 'GLUT_WINDOW_ALPHA_SIZE', 'GLUT_WINDOW_BLUE_SIZE', 'GLUT_WINDOW_BUFFER_SIZE', 'GLUT_WINDOW_COLORMAP_SIZE', 'GLUT_WINDOW_CURSOR', 'GLUT_WINDOW_DEPTH_SIZE', 'GLUT_WINDOW_DOUBLEBUFFER', 'GLUT_WINDOW_FORMAT_ID', 'GLUT_WINDOW_GREEN_SIZE', 'GLUT_WINDOW_HEIGHT', 'GLUT_WINDOW_NUM_CHILDREN', 'GLUT_WINDOW_NUM_SAMPLES', 'GLUT_WINDOW_PARENT', 'GLUT_WINDOW_RED_SIZE', 'GLUT_WINDOW_RGBA', 'GLUT_WINDOW_STENCIL_SIZE', 'GLUT_WINDOW_STEREO', 'GLUT_WINDOW_WIDTH', 'GLUT_WINDOW_X', 'GLUT_WINDOW_Y', 'GLUT_XLIB_IMPLEMENTATION', 'GLdouble', 'GLenum', 'GLfloat', 'GLint', 'glutAddMenuEntry', 'glutAddSubMenu', 'glutAttachMenu', 'glutBitmapCharacter', 'glutBitmapLength', 'glutBitmapWidth', 'glutButtonBoxFunc', 'glutChangeToMenuEntry', 'glutChangeToSubMenu', 'glutCopyColormap', 'glutCreateMenu', 'glutCreateSubWindow', 'glutCreateWindow', 'glutDestroyMenu', 'glutDestroyWindow', 'glutDetachMenu', 'glutDeviceGet', 'glutDialsFunc', 'glutDisplayFunc', 'glutEnterGameMode', 'glutEntryFunc', 'glutEstablishOverlay', 'glutExtensionSupported', 'glutForceJoystickFunc', 'glutFullScreen', 'glutGameModeGet', 'glutGameModeString', 'glutGet', 'glutGetColor', 'glutGetMenu', 'glutGetModifiers', 'glutGetWindow', 'glutHideOverlay', 'glutHideWindow', 'glutIconifyWindow', 'glutIdleFunc', 'glutIgnoreKeyRepeat', 'glutInit', 'glutInitDisplayMode', 'glutInitDisplayString', 'glutInitWindowPosition', 'glutInitWindowSize', 'glutJoystickFunc', 'glutKeyboardFunc', 'glutKeyboardUpFunc', 'glutLayerGet', 'glutLeaveGameMode', 'glutMainLoop', 'glutMenuStateFunc', 'glutMenuStatusFunc', 'glutMotionFunc', 'glutMouseFunc', 'glutOverlayDisplayFunc', 'glutPassiveMotionFunc', 'glutPopWindow', 'glutPositionWindow', 'glutPostOverlayRedisplay', 'glutPostRedisplay', 'glutPostWindowOverlayRedisplay', 'glutPostWindowRedisplay', 'glutPushWindow', 'glutRemoveMenuItem', 'glutRemoveOverlay', 'glutReportErrors', 'glutReshapeFunc', 'glutReshapeWindow', 'glutSetColor', 'glutSetCursor', 'glutSetIconTitle', 'glutSetKeyRepeat', 'glutSetMenu', 'glutSetWindow', 'glutSetWindowTitle', 'glutSetupVideoResizing', 'glutShowOverlay', 'glutShowWindow', 'glutSolidCone', 'glutSolidCube', 'glutSolidDodecahedron', 'glutSolidIcosahedron', 'glutSolidOctahedron', 'glutSolidSphere', 'glutSolidTeapot', 'glutSolidTetrahedron', 'glutSolidTorus', 'glutSpaceballButtonFunc', 'glutSpaceballMotionFunc', 'glutSpaceballRotateFunc', 'glutSpecialFunc', 'glutSpecialUpFunc', 'glutStopVideoResizing', 'glutStrokeCharacter', 'glutStrokeLength', 'glutStrokeWidth', 'glutSwapBuffers', 'glutTabletButtonFunc', 'glutTabletMotionFunc', 'glutTimerFunc', 'glutUseLayer', 'glutVideoPan', 'glutVideoResize', 'glutVideoResizeGet', 'glutVisibilityFunc', 'glutWarpPointer', 'glutWindowStatusFunc', 'glutWireCone', 'glutWireCube', 'glutWireDodecahedron', 'glutWireIcosahedron', 'glutWireOctahedron', 'glutWireSphere', 'glutWireTeapot', 'glutWireTetrahedron', 'glutWireTorus']

class STRING(c_char_p):
    @classmethod
    def from_param(cls, value): ...

glutAddMenuEntry: Incomplete
glutAddSubMenu: Incomplete
glutAttachMenu: Incomplete
glutBitmapCharacter: Incomplete
glutBitmapLength: Incomplete
glutBitmapWidth: Incomplete
glutButtonBoxFunc: Incomplete
glutChangeToMenuEntry: Incomplete
glutChangeToSubMenu: Incomplete
glutCopyColormap: Incomplete
glutCreateMenu: Incomplete
glutCreateSubWindow: Incomplete
glutCreateWindow: Incomplete
glutDestroyMenu: Incomplete
glutDestroyWindow: Incomplete
glutDetachMenu: Incomplete
glutDeviceGet: Incomplete
glutDialsFunc: Incomplete
glutDisplayFunc: Incomplete
glutEnterGameMode: Incomplete
glutEntryFunc: Incomplete
glutEstablishOverlay: Incomplete
glutExtensionSupported: Incomplete
glutForceJoystickFunc: Incomplete
glutFullScreen: Incomplete
glutGameModeGet: Incomplete
glutGameModeString: Incomplete
glutGet: Incomplete
glutGetColor: Incomplete
glutGetMenu: Incomplete
glutGetModifiers: Incomplete
glutGetWindow: Incomplete
glutHideOverlay: Incomplete
glutHideWindow: Incomplete
glutIconifyWindow: Incomplete
glutIdleFunc: Incomplete
glutIgnoreKeyRepeat: Incomplete
glutInit: Incomplete
glutInitDisplayMode: Incomplete
glutInitDisplayString: Incomplete
glutInitWindowPosition: Incomplete
glutInitWindowSize: Incomplete
glutJoystickFunc: Incomplete
glutKeyboardFunc: Incomplete
glutKeyboardUpFunc: Incomplete
glutLayerGet: Incomplete
glutLeaveGameMode: Incomplete
glutMainLoop: Incomplete
glutMenuStateFunc: Incomplete
glutMenuStatusFunc: Incomplete
glutMotionFunc: Incomplete
glutMouseFunc: Incomplete
glutOverlayDisplayFunc: Incomplete
glutPassiveMotionFunc: Incomplete
glutPopWindow: Incomplete
glutPositionWindow: Incomplete
glutPostOverlayRedisplay: Incomplete
glutPostRedisplay: Incomplete
glutPostWindowOverlayRedisplay: Incomplete
glutPostWindowRedisplay: Incomplete
glutPushWindow: Incomplete
glutRemoveMenuItem: Incomplete
glutRemoveOverlay: Incomplete
glutReportErrors: Incomplete
glutReshapeFunc: Incomplete
glutReshapeWindow: Incomplete
glutSetColor: Incomplete
glutSetCursor: Incomplete
glutSetIconTitle: Incomplete
glutSetKeyRepeat: Incomplete
glutSetMenu: Incomplete
glutSetWindow: Incomplete
glutSetWindowTitle: Incomplete
glutSetupVideoResizing: Incomplete
glutShowOverlay: Incomplete
glutShowWindow: Incomplete
glutSolidCone: Incomplete
glutSolidCube: Incomplete
glutSolidDodecahedron: Incomplete
glutSolidIcosahedron: Incomplete
glutSolidOctahedron: Incomplete
glutSolidSphere: Incomplete
glutSolidTeapot: Incomplete
glutSolidTetrahedron: Incomplete
glutSolidTorus: Incomplete
glutSpaceballButtonFunc: Incomplete
glutSpaceballMotionFunc: Incomplete
glutSpaceballRotateFunc: Incomplete
glutSpecialFunc: Incomplete
glutSpecialUpFunc: Incomplete
glutStopVideoResizing: Incomplete
glutStrokeCharacter: Incomplete
glutStrokeLength: Incomplete
glutStrokeWidth: Incomplete
glutSwapBuffers: Incomplete
glutTabletButtonFunc: Incomplete
glutTabletMotionFunc: Incomplete
glutTimerFunc: Incomplete
glutUseLayer: Incomplete
glutVideoPan: Incomplete
glutVideoResize: Incomplete
glutVideoResizeGet: Incomplete
glutVisibilityFunc: Incomplete
glutWarpPointer: Incomplete
glutWindowStatusFunc: Incomplete
glutWireCone: Incomplete
glutWireCube: Incomplete
glutWireDodecahedron: Incomplete
glutWireIcosahedron: Incomplete
glutWireOctahedron: Incomplete
glutWireSphere: Incomplete
glutWireTeapot: Incomplete
glutWireTetrahedron: Incomplete
glutWireTorus: Incomplete

# Names in __all__ with no definition:
#   GLUT_ACCUM
#   GLUT_ACTIVE_ALT
#   GLUT_ACTIVE_CTRL
#   GLUT_ACTIVE_SHIFT
#   GLUT_ALPHA
#   GLUT_API_VERSION
#   GLUT_BLUE
#   GLUT_CURSOR_BOTTOM_LEFT_CORNER
#   GLUT_CURSOR_BOTTOM_RIGHT_CORNER
#   GLUT_CURSOR_BOTTOM_SIDE
#   GLUT_CURSOR_CROSSHAIR
#   GLUT_CURSOR_CYCLE
#   GLUT_CURSOR_DESTROY
#   GLUT_CURSOR_FULL_CROSSHAIR
#   GLUT_CURSOR_HELP
#   GLUT_CURSOR_INFO
#   GLUT_CURSOR_INHERIT
#   GLUT_CURSOR_LEFT_ARROW
#   GLUT_CURSOR_LEFT_RIGHT
#   GLUT_CURSOR_LEFT_SIDE
#   GLUT_CURSOR_NONE
#   GLUT_CURSOR_RIGHT_ARROW
#   GLUT_CURSOR_RIGHT_SIDE
#   GLUT_CURSOR_SPRAY
#   GLUT_CURSOR_TEXT
#   GLUT_CURSOR_TOP_LEFT_CORNER
#   GLUT_CURSOR_TOP_RIGHT_CORNER
#   GLUT_CURSOR_TOP_SIDE
#   GLUT_CURSOR_UP_DOWN
#   GLUT_CURSOR_WAIT
#   GLUT_DEPTH
#   GLUT_DEVICE_IGNORE_KEY_REPEAT
#   GLUT_DEVICE_KEY_REPEAT
#   GLUT_DISPLAY_MODE_POSSIBLE
#   GLUT_DOUBLE
#   GLUT_DOWN
#   GLUT_ELAPSED_TIME
#   GLUT_ENTERED
#   GLUT_FULLY_COVERED
#   GLUT_FULLY_RETAINED
#   GLUT_GAME_MODE_ACTIVE
#   GLUT_GAME_MODE_DISPLAY_CHANGED
#   GLUT_GAME_MODE_HEIGHT
#   GLUT_GAME_MODE_PIXEL_DEPTH
#   GLUT_GAME_MODE_POSSIBLE
#   GLUT_GAME_MODE_REFRESH_RATE
#   GLUT_GAME_MODE_WIDTH
#   GLUT_GREEN
#   GLUT_HAS_DIAL_AND_BUTTON_BOX
#   GLUT_HAS_JOYSTICK
#   GLUT_HAS_KEYBOARD
#   GLUT_HAS_MOUSE
#   GLUT_HAS_OVERLAY
#   GLUT_HAS_SPACEBALL
#   GLUT_HAS_TABLET
#   GLUT_HIDDEN
#   GLUT_INDEX
#   GLUT_INIT_DISPLAY_MODE
#   GLUT_INIT_STATE
#   GLUT_INIT_WINDOW_HEIGHT
#   GLUT_INIT_WINDOW_WIDTH
#   GLUT_INIT_WINDOW_X
#   GLUT_INIT_WINDOW_Y
#   GLUT_JOYSTICK_AXES
#   GLUT_JOYSTICK_BUTTONS
#   GLUT_JOYSTICK_BUTTON_A
#   GLUT_JOYSTICK_BUTTON_B
#   GLUT_JOYSTICK_BUTTON_C
#   GLUT_JOYSTICK_BUTTON_D
#   GLUT_JOYSTICK_POLL_RATE
#   GLUT_KEY_DOWN
#   GLUT_KEY_END
#   GLUT_KEY_F1
#   GLUT_KEY_F10
#   GLUT_KEY_F11
#   GLUT_KEY_F12
#   GLUT_KEY_F2
#   GLUT_KEY_F3
#   GLUT_KEY_F4
#   GLUT_KEY_F5
#   GLUT_KEY_F6
#   GLUT_KEY_F7
#   GLUT_KEY_F8
#   GLUT_KEY_F9
#   GLUT_KEY_HOME
#   GLUT_KEY_INSERT
#   GLUT_KEY_LEFT
#   GLUT_KEY_PAGE_DOWN
#   GLUT_KEY_PAGE_UP
#   GLUT_KEY_REPEAT_DEFAULT
#   GLUT_KEY_REPEAT_OFF
#   GLUT_KEY_REPEAT_ON
#   GLUT_KEY_RIGHT
#   GLUT_KEY_UP
#   GLUT_LAYER_IN_USE
#   GLUT_LEFT
#   GLUT_LEFT_BUTTON
#   GLUT_LUMINANCE
#   GLUT_MENU_IN_USE
#   GLUT_MENU_NOT_IN_USE
#   GLUT_MENU_NUM_ITEMS
#   GLUT_MIDDLE_BUTTON
#   GLUT_MULTISAMPLE
#   GLUT_NORMAL
#   GLUT_NORMAL_DAMAGED
#   GLUT_NOT_VISIBLE
#   GLUT_NUM_BUTTON_BOX_BUTTONS
#   GLUT_NUM_DIALS
#   GLUT_NUM_MOUSE_BUTTONS
#   GLUT_NUM_SPACEBALL_BUTTONS
#   GLUT_NUM_TABLET_BUTTONS
#   GLUT_OVERLAY
#   GLUT_OVERLAY_DAMAGED
#   GLUT_OVERLAY_POSSIBLE
#   GLUT_OWNS_JOYSTICK
#   GLUT_PARTIALLY_RETAINED
#   GLUT_RED
#   GLUT_RGB
#   GLUT_RGBA
#   GLUT_RIGHT_BUTTON
#   GLUT_SCREEN_HEIGHT
#   GLUT_SCREEN_HEIGHT_MM
#   GLUT_SCREEN_WIDTH
#   GLUT_SCREEN_WIDTH_MM
#   GLUT_SINGLE
#   GLUT_STENCIL
#   GLUT_STEREO
#   GLUT_TRANSPARENT_INDEX
#   GLUT_UP
#   GLUT_VIDEO_RESIZE_HEIGHT
#   GLUT_VIDEO_RESIZE_HEIGHT_DELTA
#   GLUT_VIDEO_RESIZE_IN_USE
#   GLUT_VIDEO_RESIZE_POSSIBLE
#   GLUT_VIDEO_RESIZE_WIDTH
#   GLUT_VIDEO_RESIZE_WIDTH_DELTA
#   GLUT_VIDEO_RESIZE_X
#   GLUT_VIDEO_RESIZE_X_DELTA
#   GLUT_VIDEO_RESIZE_Y
#   GLUT_VIDEO_RESIZE_Y_DELTA
#   GLUT_VISIBLE
#   GLUT_WINDOW_ACCUM_ALPHA_SIZE
#   GLUT_WINDOW_ACCUM_BLUE_SIZE
#   GLUT_WINDOW_ACCUM_GREEN_SIZE
#   GLUT_WINDOW_ACCUM_RED_SIZE
#   GLUT_WINDOW_ALPHA_SIZE
#   GLUT_WINDOW_BLUE_SIZE
#   GLUT_WINDOW_BUFFER_SIZE
#   GLUT_WINDOW_COLORMAP_SIZE
#   GLUT_WINDOW_CURSOR
#   GLUT_WINDOW_DEPTH_SIZE
#   GLUT_WINDOW_DOUBLEBUFFER
#   GLUT_WINDOW_FORMAT_ID
#   GLUT_WINDOW_GREEN_SIZE
#   GLUT_WINDOW_HEIGHT
#   GLUT_WINDOW_NUM_CHILDREN
#   GLUT_WINDOW_NUM_SAMPLES
#   GLUT_WINDOW_PARENT
#   GLUT_WINDOW_RED_SIZE
#   GLUT_WINDOW_RGBA
#   GLUT_WINDOW_STENCIL_SIZE
#   GLUT_WINDOW_STEREO
#   GLUT_WINDOW_WIDTH
#   GLUT_WINDOW_X
#   GLUT_WINDOW_Y
#   GLUT_XLIB_IMPLEMENTATION
