from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_DRAW_PIXELS_APPLE: Incomplete
GL_FENCE_APPLE: Incomplete

@_f
def glDeleteFencesAPPLE(n, fences) -> None: ...
@_f
def glFinishFenceAPPLE(fence) -> None: ...
@_f
def glFinishObjectAPPLE(object, name) -> None: ...
@_f
def glGenFencesAPPLE(n, fences) -> None: ...
@_f
def glIsFenceAPPLE(fence) -> None: ...
@_f
def glSetFenceAPPLE(fence) -> None: ...
@_f
def glTestFenceAPPLE(fence) -> None: ...
@_f
def glTestObjectAPPLE(object, name) -> None: ...
