from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glBlendEquationIndexedAMD(buf, mode) -> None: ...
@_f
def glBlendEquationSeparateIndexedAMD(buf, modeRGB, modeAlpha) -> None: ...
@_f
def glBlendFuncIndexedAMD(buf, src, dst) -> None: ...
@_f
def glBlendFuncSeparateIndexedAMD(buf, srcRGB, dstRGB, srcAlpha, dstAlpha) -> None: ...
