from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_COUNTER_RANGE_AMD: Incomplete
GL_COUNTER_TYPE_AMD: Incomplete
GL_PERCENTAGE_AMD: Incomplete
GL_PERFMON_RESULT_AMD: Incomplete
GL_PERFMON_RESULT_AVAILABLE_AMD: Incomplete
GL_PERFMON_RESULT_SIZE_AMD: Incomplete
GL_UNSIGNED_INT64_AMD: Incomplete

@_f
def glBeginPerfMonitorAMD(monitor) -> None: ...
@_f
def glDeletePerfMonitorsAMD(n, monitors) -> None: ...
@_f
def glEndPerfMonitorAMD(monitor) -> None: ...
@_f
def glGenPerfMonitorsAMD(n, monitors) -> None: ...
@_f
def glGetPerfMonitorCounterDataAMD(monitor, pname, dataSize, data, bytesWritten) -> None: ...
@_f
def glGetPerfMonitorCounterInfoAMD(group, counter, pname, data) -> None: ...
@_f
def glGetPerfMonitorCounterStringAMD(group, counter, bufSize, length, counterString) -> None: ...
@_f
def glGetPerfMonitorCountersAMD(group, numCounters, maxActiveCounters, counterSize, counters) -> None: ...
@_f
def glGetPerfMonitorGroupStringAMD(group, bufSize, length, groupString) -> None: ...
@_f
def glGetPerfMonitorGroupsAMD(numGroups, groupsSize, groups) -> None: ...
@_f
def glSelectPerfMonitorCountersAMD(monitor, enable, group, numCounters, counterList) -> None: ...
