from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_BINORMAL_ARRAY_EXT: Incomplete
GL_BINORMAL_ARRAY_POINTER_EXT: Incomplete
GL_BINORMAL_ARRAY_STRIDE_EXT: Incomplete
GL_BINORMAL_ARRAY_TYPE_EXT: Incomplete
GL_CURRENT_BINORMAL_EXT: Incomplete
GL_CURRENT_TANGENT_EXT: Incomplete
GL_MAP1_BINORMAL_EXT: Incomplete
GL_MAP1_TANGENT_EXT: Incomplete
GL_MAP2_BINORMAL_EXT: Incomplete
GL_MAP2_TANGENT_EXT: Incomplete
GL_TANGENT_ARRAY_EXT: Incomplete
GL_TANGENT_ARRAY_POINTER_EXT: Incomplete
GL_TANGENT_ARRAY_STRIDE_EXT: Incomplete
GL_TANGENT_ARRAY_TYPE_EXT: Incomplete

@_f
def glBinormal3bEXT(bx, by, bz) -> None: ...
@_f
def glBinormal3bvEXT(v) -> None: ...
@_f
def glBinormal3dEXT(bx, by, bz) -> None: ...
@_f
def glBinormal3dvEXT(v) -> None: ...
@_f
def glBinormal3fEXT(bx, by, bz) -> None: ...
@_f
def glBinormal3fvEXT(v) -> None: ...
@_f
def glBinormal3iEXT(bx, by, bz) -> None: ...
@_f
def glBinormal3ivEXT(v) -> None: ...
@_f
def glBinormal3sEXT(bx, by, bz) -> None: ...
@_f
def glBinormal3svEXT(v) -> None: ...
@_f
def glBinormalPointerEXT(type, stride, pointer) -> None: ...
@_f
def glTangent3bEXT(tx, ty, tz) -> None: ...
@_f
def glTangent3bvEXT(v) -> None: ...
@_f
def glTangent3dEXT(tx, ty, tz) -> None: ...
@_f
def glTangent3dvEXT(v) -> None: ...
@_f
def glTangent3fEXT(tx, ty, tz) -> None: ...
@_f
def glTangent3fvEXT(v) -> None: ...
@_f
def glTangent3iEXT(tx, ty, tz) -> None: ...
@_f
def glTangent3ivEXT(v) -> None: ...
@_f
def glTangent3sEXT(tx, ty, tz) -> None: ...
@_f
def glTangent3svEXT(v) -> None: ...
@_f
def glTangentPointerEXT(type, stride, pointer) -> None: ...
