from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glCopyTexImage1DEXT(target, level, internalformat, x, y, width, border) -> None: ...
@_f
def glCopyTexImage2DEXT(target, level, internalformat, x, y, width, height, border) -> None: ...
@_f
def glCopyTexSubImage1DEXT(target, level, xoffset, x, y, width) -> None: ...
@_f
def glCopyTexSubImage2DEXT(target, level, xoffset, yoffset, x, y, width, height) -> None: ...
@_f
def glCopyTexSubImage3DEXT(target, level, xoffset, yoffset, zoffset, x, y, width, height) -> None: ...
