from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_PROGRAM_MATRIX_EXT: Incomplete
GL_PROGRAM_MATRIX_STACK_DEPTH_EXT: Incomplete
GL_TRANSPOSE_PROGRAM_MATRIX_EXT: Incomplete

@_f
def glBindMultiTextureEXT(texunit, target, texture) -> None: ...
@_f
def glCheckNamedFramebufferStatusEXT(framebuffer, target) -> None: ...
@_f
def glClearNamedBufferDataEXT(buffer, internalformat, format, type, data) -> None: ...
@_f
def glClearNamedBufferSubDataEXT(buffer, internalformat, offset, size, format, type, data) -> None: ...
@_f
def glClientAttribDefaultEXT(mask) -> None: ...
@_f
def glCompressedMultiTexImage1DEXT(texunit, target, level, internalformat, width, border, imageSize, bits) -> None: ...
@_f
def glCompressedMultiTexImage2DEXT(texunit, target, level, internalformat, width, height, border, imageSize, bits) -> None: ...
@_f
def glCompressedMultiTexImage3DEXT(texunit, target, level, internalformat, width, height, depth, border, imageSize, bits) -> None: ...
@_f
def glCompressedMultiTexSubImage1DEXT(texunit, target, level, xoffset, width, format, imageSize, bits) -> None: ...
@_f
def glCompressedMultiTexSubImage2DEXT(texunit, target, level, xoffset, yoffset, width, height, format, imageSize, bits) -> None: ...
@_f
def glCompressedMultiTexSubImage3DEXT(texunit, target, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, bits) -> None: ...
@_f
def glCompressedTextureImage1DEXT(texture, target, level, internalformat, width, border, imageSize, bits) -> None: ...
@_f
def glCompressedTextureImage2DEXT(texture, target, level, internalformat, width, height, border, imageSize, bits) -> None: ...
@_f
def glCompressedTextureImage3DEXT(texture, target, level, internalformat, width, height, depth, border, imageSize, bits) -> None: ...
@_f
def glCompressedTextureSubImage1DEXT(texture, target, level, xoffset, width, format, imageSize, bits) -> None: ...
@_f
def glCompressedTextureSubImage2DEXT(texture, target, level, xoffset, yoffset, width, height, format, imageSize, bits) -> None: ...
@_f
def glCompressedTextureSubImage3DEXT(texture, target, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, bits) -> None: ...
@_f
def glCopyMultiTexImage1DEXT(texunit, target, level, internalformat, x, y, width, border) -> None: ...
@_f
def glCopyMultiTexImage2DEXT(texunit, target, level, internalformat, x, y, width, height, border) -> None: ...
@_f
def glCopyMultiTexSubImage1DEXT(texunit, target, level, xoffset, x, y, width) -> None: ...
@_f
def glCopyMultiTexSubImage2DEXT(texunit, target, level, xoffset, yoffset, x, y, width, height) -> None: ...
@_f
def glCopyMultiTexSubImage3DEXT(texunit, target, level, xoffset, yoffset, zoffset, x, y, width, height) -> None: ...
@_f
def glCopyTextureImage1DEXT(texture, target, level, internalformat, x, y, width, border) -> None: ...
@_f
def glCopyTextureImage2DEXT(texture, target, level, internalformat, x, y, width, height, border) -> None: ...
@_f
def glCopyTextureSubImage1DEXT(texture, target, level, xoffset, x, y, width) -> None: ...
@_f
def glCopyTextureSubImage2DEXT(texture, target, level, xoffset, yoffset, x, y, width, height) -> None: ...
@_f
def glCopyTextureSubImage3DEXT(texture, target, level, xoffset, yoffset, zoffset, x, y, width, height) -> None: ...
@_f
def glDisableClientStateIndexedEXT(array, index) -> None: ...
@_f
def glDisableClientStateiEXT(array, index) -> None: ...
@_f
def glDisableIndexedEXT(target, index) -> None: ...
@_f
def glDisableVertexArrayAttribEXT(vaobj, index) -> None: ...
@_f
def glDisableVertexArrayEXT(vaobj, array) -> None: ...
@_f
def glEnableClientStateIndexedEXT(array, index) -> None: ...
@_f
def glEnableClientStateiEXT(array, index) -> None: ...
@_f
def glEnableIndexedEXT(target, index) -> None: ...
@_f
def glEnableVertexArrayAttribEXT(vaobj, index) -> None: ...
@_f
def glEnableVertexArrayEXT(vaobj, array) -> None: ...
@_f
def glFlushMappedNamedBufferRangeEXT(buffer, offset, length) -> None: ...
@_f
def glFramebufferDrawBufferEXT(framebuffer, mode) -> None: ...
@_f
def glFramebufferDrawBuffersEXT(framebuffer, n, bufs) -> None: ...
@_f
def glFramebufferReadBufferEXT(framebuffer, mode) -> None: ...
@_f
def glGenerateMultiTexMipmapEXT(texunit, target) -> None: ...
@_f
def glGenerateTextureMipmapEXT(texture, target) -> None: ...
@_f
def glGetBooleanIndexedvEXT(target, index, data) -> None: ...
@_f
def glGetCompressedMultiTexImageEXT(texunit, target, lod, img) -> None: ...
@_f
def glGetCompressedTextureImageEXT(texture, target, lod, img) -> None: ...
@_f
def glGetDoubleIndexedvEXT(target, index, data) -> None: ...
@_f
def glGetDoublei_vEXT(pname, index, params) -> None: ...
@_f
def glGetFloatIndexedvEXT(target, index, data) -> None: ...
@_f
def glGetFloati_vEXT(pname, index, params) -> None: ...
@_f
def glGetFramebufferParameterivEXT(framebuffer, pname, params) -> None: ...
@_f
def glGetIntegerIndexedvEXT(target, index, data) -> None: ...
@_f
def glGetMultiTexEnvfvEXT(texunit, target, pname, params) -> None: ...
@_f
def glGetMultiTexEnvivEXT(texunit, target, pname, params) -> None: ...
@_f
def glGetMultiTexGendvEXT(texunit, coord, pname, params) -> None: ...
@_f
def glGetMultiTexGenfvEXT(texunit, coord, pname, params) -> None: ...
@_f
def glGetMultiTexGenivEXT(texunit, coord, pname, params) -> None: ...
@_f
def glGetMultiTexImageEXT(texunit, target, level, format, type, pixels) -> None: ...
@_f
def glGetMultiTexLevelParameterfvEXT(texunit, target, level, pname, params) -> None: ...
@_f
def glGetMultiTexLevelParameterivEXT(texunit, target, level, pname, params) -> None: ...
@_f
def glGetMultiTexParameterIivEXT(texunit, target, pname, params) -> None: ...
@_f
def glGetMultiTexParameterIuivEXT(texunit, target, pname, params) -> None: ...
@_f
def glGetMultiTexParameterfvEXT(texunit, target, pname, params) -> None: ...
@_f
def glGetMultiTexParameterivEXT(texunit, target, pname, params) -> None: ...
@_f
def glGetNamedBufferParameterivEXT(buffer, pname, params) -> None: ...
@_f
def glGetNamedBufferPointervEXT(buffer, pname, params) -> None: ...
@_f
def glGetNamedBufferSubDataEXT(buffer, offset, size, data) -> None: ...
@_f
def glGetNamedFramebufferAttachmentParameterivEXT(framebuffer, attachment, pname, params) -> None: ...
@_f
def glGetNamedFramebufferParameterivEXT(framebuffer, pname, params) -> None: ...
@_f
def glGetNamedProgramLocalParameterIivEXT(program, target, index, params) -> None: ...
@_f
def glGetNamedProgramLocalParameterIuivEXT(program, target, index, params) -> None: ...
@_f
def glGetNamedProgramLocalParameterdvEXT(program, target, index, params) -> None: ...
@_f
def glGetNamedProgramLocalParameterfvEXT(program, target, index, params) -> None: ...
@_f
def glGetNamedProgramStringEXT(program, target, pname, string) -> None: ...
@_f
def glGetNamedProgramivEXT(program, target, pname, params) -> None: ...
@_f
def glGetNamedRenderbufferParameterivEXT(renderbuffer, pname, params) -> None: ...
@_f
def glGetPointerIndexedvEXT(target, index, data) -> None: ...
@_f
def glGetPointeri_vEXT(pname, index, params) -> None: ...
@_f
def glGetTextureImageEXT(texture, target, level, format, type, pixels) -> None: ...
@_f
def glGetTextureLevelParameterfvEXT(texture, target, level, pname, params) -> None: ...
@_f
def glGetTextureLevelParameterivEXT(texture, target, level, pname, params) -> None: ...
@_f
def glGetTextureParameterIivEXT(texture, target, pname, params) -> None: ...
@_f
def glGetTextureParameterIuivEXT(texture, target, pname, params) -> None: ...
@_f
def glGetTextureParameterfvEXT(texture, target, pname, params) -> None: ...
@_f
def glGetTextureParameterivEXT(texture, target, pname, params) -> None: ...
@_f
def glGetVertexArrayIntegeri_vEXT(vaobj, index, pname, param) -> None: ...
@_f
def glGetVertexArrayIntegervEXT(vaobj, pname, param) -> None: ...
@_f
def glGetVertexArrayPointeri_vEXT(vaobj, index, pname, param) -> None: ...
@_f
def glGetVertexArrayPointervEXT(vaobj, pname, param) -> None: ...
@_f
def glIsEnabledIndexedEXT(target, index) -> None: ...
@_f
def glMapNamedBufferEXT(buffer, access) -> None: ...
@_f
def glMapNamedBufferRangeEXT(buffer, offset, length, access) -> None: ...
@_f
def glMatrixFrustumEXT(mode, left, right, bottom, top, zNear, zFar) -> None: ...
@_f
def glMatrixLoadIdentityEXT(mode) -> None: ...
@_f
def glMatrixLoadTransposedEXT(mode, m) -> None: ...
@_f
def glMatrixLoadTransposefEXT(mode, m) -> None: ...
@_f
def glMatrixLoaddEXT(mode, m) -> None: ...
@_f
def glMatrixLoadfEXT(mode, m) -> None: ...
@_f
def glMatrixMultTransposedEXT(mode, m) -> None: ...
@_f
def glMatrixMultTransposefEXT(mode, m) -> None: ...
@_f
def glMatrixMultdEXT(mode, m) -> None: ...
@_f
def glMatrixMultfEXT(mode, m) -> None: ...
@_f
def glMatrixOrthoEXT(mode, left, right, bottom, top, zNear, zFar) -> None: ...
@_f
def glMatrixPopEXT(mode) -> None: ...
@_f
def glMatrixPushEXT(mode) -> None: ...
@_f
def glMatrixRotatedEXT(mode, angle, x, y, z) -> None: ...
@_f
def glMatrixRotatefEXT(mode, angle, x, y, z) -> None: ...
@_f
def glMatrixScaledEXT(mode, x, y, z) -> None: ...
@_f
def glMatrixScalefEXT(mode, x, y, z) -> None: ...
@_f
def glMatrixTranslatedEXT(mode, x, y, z) -> None: ...
@_f
def glMatrixTranslatefEXT(mode, x, y, z) -> None: ...
@_f
def glMultiTexBufferEXT(texunit, target, internalformat, buffer) -> None: ...
@_f
def glMultiTexCoordPointerEXT(texunit, size, type, stride, pointer) -> None: ...
@_f
def glMultiTexEnvfEXT(texunit, target, pname, param) -> None: ...
@_f
def glMultiTexEnvfvEXT(texunit, target, pname, params) -> None: ...
@_f
def glMultiTexEnviEXT(texunit, target, pname, param) -> None: ...
@_f
def glMultiTexEnvivEXT(texunit, target, pname, params) -> None: ...
@_f
def glMultiTexGendEXT(texunit, coord, pname, param) -> None: ...
@_f
def glMultiTexGendvEXT(texunit, coord, pname, params) -> None: ...
@_f
def glMultiTexGenfEXT(texunit, coord, pname, param) -> None: ...
@_f
def glMultiTexGenfvEXT(texunit, coord, pname, params) -> None: ...
@_f
def glMultiTexGeniEXT(texunit, coord, pname, param) -> None: ...
@_f
def glMultiTexGenivEXT(texunit, coord, pname, params) -> None: ...
@_f
def glMultiTexImage1DEXT(texunit, target, level, internalformat, width, border, format, type, pixels) -> None: ...
@_f
def glMultiTexImage2DEXT(texunit, target, level, internalformat, width, height, border, format, type, pixels) -> None: ...
@_f
def glMultiTexImage3DEXT(texunit, target, level, internalformat, width, height, depth, border, format, type, pixels) -> None: ...
@_f
def glMultiTexParameterIivEXT(texunit, target, pname, params) -> None: ...
@_f
def glMultiTexParameterIuivEXT(texunit, target, pname, params) -> None: ...
@_f
def glMultiTexParameterfEXT(texunit, target, pname, param) -> None: ...
@_f
def glMultiTexParameterfvEXT(texunit, target, pname, params) -> None: ...
@_f
def glMultiTexParameteriEXT(texunit, target, pname, param) -> None: ...
@_f
def glMultiTexParameterivEXT(texunit, target, pname, params) -> None: ...
@_f
def glMultiTexRenderbufferEXT(texunit, target, renderbuffer) -> None: ...
@_f
def glMultiTexSubImage1DEXT(texunit, target, level, xoffset, width, format, type, pixels) -> None: ...
@_f
def glMultiTexSubImage2DEXT(texunit, target, level, xoffset, yoffset, width, height, format, type, pixels) -> None: ...
@_f
def glMultiTexSubImage3DEXT(texunit, target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels) -> None: ...
@_f
def glNamedBufferDataEXT(buffer, size, data, usage) -> None: ...
@_f
def glNamedBufferStorageEXT(buffer, size, data, flags) -> None: ...
@_f
def glNamedBufferSubDataEXT(buffer, offset, size, data) -> None: ...
@_f
def glNamedCopyBufferSubDataEXT(readBuffer, writeBuffer, readOffset, writeOffset, size) -> None: ...
@_f
def glNamedFramebufferParameteriEXT(framebuffer, pname, param) -> None: ...
@_f
def glNamedFramebufferRenderbufferEXT(framebuffer, attachment, renderbuffertarget, renderbuffer) -> None: ...
@_f
def glNamedFramebufferTexture1DEXT(framebuffer, attachment, textarget, texture, level) -> None: ...
@_f
def glNamedFramebufferTexture2DEXT(framebuffer, attachment, textarget, texture, level) -> None: ...
@_f
def glNamedFramebufferTexture3DEXT(framebuffer, attachment, textarget, texture, level, zoffset) -> None: ...
@_f
def glNamedFramebufferTextureEXT(framebuffer, attachment, texture, level) -> None: ...
@_f
def glNamedFramebufferTextureFaceEXT(framebuffer, attachment, texture, level, face) -> None: ...
@_f
def glNamedFramebufferTextureLayerEXT(framebuffer, attachment, texture, level, layer) -> None: ...
@_f
def glNamedProgramLocalParameter4dEXT(program, target, index, x, y, z, w) -> None: ...
@_f
def glNamedProgramLocalParameter4dvEXT(program, target, index, params) -> None: ...
@_f
def glNamedProgramLocalParameter4fEXT(program, target, index, x, y, z, w) -> None: ...
@_f
def glNamedProgramLocalParameter4fvEXT(program, target, index, params) -> None: ...
@_f
def glNamedProgramLocalParameterI4iEXT(program, target, index, x, y, z, w) -> None: ...
@_f
def glNamedProgramLocalParameterI4ivEXT(program, target, index, params) -> None: ...
@_f
def glNamedProgramLocalParameterI4uiEXT(program, target, index, x, y, z, w) -> None: ...
@_f
def glNamedProgramLocalParameterI4uivEXT(program, target, index, params) -> None: ...
@_f
def glNamedProgramLocalParameters4fvEXT(program, target, index, count, params) -> None: ...
@_f
def glNamedProgramLocalParametersI4ivEXT(program, target, index, count, params) -> None: ...
@_f
def glNamedProgramLocalParametersI4uivEXT(program, target, index, count, params) -> None: ...
@_f
def glNamedProgramStringEXT(program, target, format, len, string) -> None: ...
@_f
def glNamedRenderbufferStorageEXT(renderbuffer, internalformat, width, height) -> None: ...
@_f
def glNamedRenderbufferStorageMultisampleCoverageEXT(renderbuffer, coverageSamples, colorSamples, internalformat, width, height) -> None: ...
@_f
def glNamedRenderbufferStorageMultisampleEXT(renderbuffer, samples, internalformat, width, height) -> None: ...
@_f
def glProgramUniform1dEXT(program, location, x) -> None: ...
@_f
def glProgramUniform1dvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform1fEXT(program, location, v0) -> None: ...
@_f
def glProgramUniform1fvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform1iEXT(program, location, v0) -> None: ...
@_f
def glProgramUniform1ivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform1uiEXT(program, location, v0) -> None: ...
@_f
def glProgramUniform1uivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform2dEXT(program, location, x, y) -> None: ...
@_f
def glProgramUniform2dvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform2fEXT(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2fvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform2iEXT(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2ivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform2uiEXT(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2uivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform3dEXT(program, location, x, y, z) -> None: ...
@_f
def glProgramUniform3dvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform3fEXT(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3fvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform3iEXT(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3ivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform3uiEXT(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3uivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform4dEXT(program, location, x, y, z, w) -> None: ...
@_f
def glProgramUniform4dvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform4fEXT(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4fvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform4iEXT(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4ivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform4uiEXT(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4uivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniformMatrix2dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x3dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x3fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x4dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x4fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x2dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x2fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x4dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x4fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x2dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x2fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x3dvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x3fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glPushClientAttribDefaultEXT(mask) -> None: ...
@_f
def glTextureBufferEXT(texture, target, internalformat, buffer) -> None: ...
@_f
def glTextureBufferRangeEXT(texture, target, internalformat, buffer, offset, size) -> None: ...
@_f
def glTextureImage1DEXT(texture, target, level, internalformat, width, border, format, type, pixels) -> None: ...
@_f
def glTextureImage2DEXT(texture, target, level, internalformat, width, height, border, format, type, pixels) -> None: ...
@_f
def glTextureImage3DEXT(texture, target, level, internalformat, width, height, depth, border, format, type, pixels) -> None: ...
@_f
def glTexturePageCommitmentEXT(texture, level, xoffset, yoffset, zoffset, width, height, depth, commit) -> None: ...
@_f
def glTextureParameterIivEXT(texture, target, pname, params) -> None: ...
@_f
def glTextureParameterIuivEXT(texture, target, pname, params) -> None: ...
@_f
def glTextureParameterfEXT(texture, target, pname, param) -> None: ...
@_f
def glTextureParameterfvEXT(texture, target, pname, params) -> None: ...
@_f
def glTextureParameteriEXT(texture, target, pname, param) -> None: ...
@_f
def glTextureParameterivEXT(texture, target, pname, params) -> None: ...
@_f
def glTextureRenderbufferEXT(texture, target, renderbuffer) -> None: ...
@_f
def glTextureStorage1DEXT(texture, target, levels, internalformat, width) -> None: ...
@_f
def glTextureStorage2DEXT(texture, target, levels, internalformat, width, height) -> None: ...
@_f
def glTextureStorage2DMultisampleEXT(texture, target, samples, internalformat, width, height, fixedsamplelocations) -> None: ...
@_f
def glTextureStorage3DEXT(texture, target, levels, internalformat, width, height, depth) -> None: ...
@_f
def glTextureStorage3DMultisampleEXT(texture, target, samples, internalformat, width, height, depth, fixedsamplelocations) -> None: ...
@_f
def glTextureSubImage1DEXT(texture, target, level, xoffset, width, format, type, pixels) -> None: ...
@_f
def glTextureSubImage2DEXT(texture, target, level, xoffset, yoffset, width, height, format, type, pixels) -> None: ...
@_f
def glTextureSubImage3DEXT(texture, target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels) -> None: ...
@_f
def glUnmapNamedBufferEXT(buffer) -> None: ...
@_f
def glVertexArrayBindVertexBufferEXT(vaobj, bindingindex, buffer, offset, stride) -> None: ...
@_f
def glVertexArrayColorOffsetEXT(vaobj, buffer, size, type, stride, offset) -> None: ...
@_f
def glVertexArrayEdgeFlagOffsetEXT(vaobj, buffer, stride, offset) -> None: ...
@_f
def glVertexArrayFogCoordOffsetEXT(vaobj, buffer, type, stride, offset) -> None: ...
@_f
def glVertexArrayIndexOffsetEXT(vaobj, buffer, type, stride, offset) -> None: ...
@_f
def glVertexArrayMultiTexCoordOffsetEXT(vaobj, buffer, texunit, size, type, stride, offset) -> None: ...
@_f
def glVertexArrayNormalOffsetEXT(vaobj, buffer, type, stride, offset) -> None: ...
@_f
def glVertexArraySecondaryColorOffsetEXT(vaobj, buffer, size, type, stride, offset) -> None: ...
@_f
def glVertexArrayTexCoordOffsetEXT(vaobj, buffer, size, type, stride, offset) -> None: ...
@_f
def glVertexArrayVertexAttribBindingEXT(vaobj, attribindex, bindingindex) -> None: ...
@_f
def glVertexArrayVertexAttribDivisorEXT(vaobj, index, divisor) -> None: ...
@_f
def glVertexArrayVertexAttribFormatEXT(vaobj, attribindex, size, type, normalized, relativeoffset) -> None: ...
@_f
def glVertexArrayVertexAttribIFormatEXT(vaobj, attribindex, size, type, relativeoffset) -> None: ...
@_f
def glVertexArrayVertexAttribIOffsetEXT(vaobj, buffer, index, size, type, stride, offset) -> None: ...
@_f
def glVertexArrayVertexAttribLFormatEXT(vaobj, attribindex, size, type, relativeoffset) -> None: ...
@_f
def glVertexArrayVertexAttribLOffsetEXT(vaobj, buffer, index, size, type, stride, offset) -> None: ...
@_f
def glVertexArrayVertexAttribOffsetEXT(vaobj, buffer, index, size, type, normalized, stride, offset) -> None: ...
@_f
def glVertexArrayVertexBindingDivisorEXT(vaobj, bindingindex, divisor) -> None: ...
@_f
def glVertexArrayVertexOffsetEXT(vaobj, buffer, size, type, stride, offset) -> None: ...
