from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glColorMaskIndexedEXT(index, r, g, b, a) -> None: ...
@_f
def glDisableIndexedEXT(target, index) -> None: ...
@_f
def glEnableIndexedEXT(target, index) -> None: ...
@_f
def glGetBooleanIndexedvEXT(target, index, data) -> None: ...
@_f
def glGetIntegerIndexedvEXT(target, index, data) -> None: ...
@_f
def glIsEnabledIndexedEXT(target, index) -> None: ...
