from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_INT_SAMPLER_1D_ARRAY_EXT: Incomplete
GL_INT_SAMPLER_1D_EXT: Incomplete
GL_INT_SAMPLER_2D_ARRAY_EXT: Incomplete
GL_INT_SAMPLER_2D_EXT: Incomplete
GL_INT_SAMPLER_2D_RECT_EXT: Incomplete
GL_INT_SAMPLER_3D_EXT: Incomplete
GL_INT_SAMPLER_BUFFER_EXT: Incomplete
GL_INT_SAMPLER_CUBE_EXT: Incomplete
GL_MAX_PROGRAM_TEXEL_OFFSET_EXT: Incomplete
GL_MIN_PROGRAM_TEXEL_OFFSET_EXT: Incomplete
GL_SAMPLER_1D_ARRAY_EXT: Incomplete
GL_SAMPLER_1D_ARRAY_SHADOW_EXT: Incomplete
GL_SAMPLER_2D_ARRAY_EXT: Incomplete
GL_SAMPLER_2D_ARRAY_SHADOW_EXT: Incomplete
GL_SAMPLER_BUFFER_EXT: Incomplete
GL_SAMPLER_CUBE_SHADOW_EXT: Incomplete
GL_UNSIGNED_INT_SAMPLER_1D_ARRAY_EXT: Incomplete
GL_UNSIGNED_INT_SAMPLER_1D_EXT: Incomplete
GL_UNSIGNED_INT_SAMPLER_2D_ARRAY_EXT: Incomplete
GL_UNSIGNED_INT_SAMPLER_2D_EXT: Incomplete
GL_UNSIGNED_INT_SAMPLER_2D_RECT_EXT: Incomplete
GL_UNSIGNED_INT_SAMPLER_3D_EXT: Incomplete
GL_UNSIGNED_INT_SAMPLER_BUFFER_EXT: Incomplete
GL_UNSIGNED_INT_SAMPLER_CUBE_EXT: Incomplete
GL_UNSIGNED_INT_VEC2_EXT: Incomplete
GL_UNSIGNED_INT_VEC3_EXT: Incomplete
GL_UNSIGNED_INT_VEC4_EXT: Incomplete
GL_VERTEX_ATTRIB_ARRAY_INTEGER_EXT: Incomplete

@_f
def glBindFragDataLocationEXT(program, color, name) -> None: ...
@_f
def glGetFragDataLocationEXT(program, name) -> None: ...
@_f
def glGetUniformuivEXT(program, location, params) -> None: ...
@_f
def glGetVertexAttribIivEXT(index, pname, params) -> None: ...
@_f
def glGetVertexAttribIuivEXT(index, pname, params) -> None: ...
@_f
def glUniform1uiEXT(location, v0) -> None: ...
@_f
def glUniform1uivEXT(location, count, value) -> None: ...
@_f
def glUniform2uiEXT(location, v0, v1) -> None: ...
@_f
def glUniform2uivEXT(location, count, value) -> None: ...
@_f
def glUniform3uiEXT(location, v0, v1, v2) -> None: ...
@_f
def glUniform3uivEXT(location, count, value) -> None: ...
@_f
def glUniform4uiEXT(location, v0, v1, v2, v3) -> None: ...
@_f
def glUniform4uivEXT(location, count, value) -> None: ...
@_f
def glVertexAttribI1iEXT(index, x) -> None: ...
@_f
def glVertexAttribI1ivEXT(index, v) -> None: ...
@_f
def glVertexAttribI1uiEXT(index, x) -> None: ...
@_f
def glVertexAttribI1uivEXT(index, v) -> None: ...
@_f
def glVertexAttribI2iEXT(index, x, y) -> None: ...
@_f
def glVertexAttribI2ivEXT(index, v) -> None: ...
@_f
def glVertexAttribI2uiEXT(index, x, y) -> None: ...
@_f
def glVertexAttribI2uivEXT(index, v) -> None: ...
@_f
def glVertexAttribI3iEXT(index, x, y, z) -> None: ...
@_f
def glVertexAttribI3ivEXT(index, v) -> None: ...
@_f
def glVertexAttribI3uiEXT(index, x, y, z) -> None: ...
@_f
def glVertexAttribI3uivEXT(index, v) -> None: ...
@_f
def glVertexAttribI4bvEXT(index, v) -> None: ...
@_f
def glVertexAttribI4iEXT(index, x, y, z, w) -> None: ...
@_f
def glVertexAttribI4ivEXT(index, v) -> None: ...
@_f
def glVertexAttribI4svEXT(index, v) -> None: ...
@_f
def glVertexAttribI4ubvEXT(index, v) -> None: ...
@_f
def glVertexAttribI4uiEXT(index, x, y, z, w) -> None: ...
@_f
def glVertexAttribI4uivEXT(index, v) -> None: ...
@_f
def glVertexAttribI4usvEXT(index, v) -> None: ...
@_f
def glVertexAttribIPointerEXT(index, size, type, stride, pointer) -> None: ...
