from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_DEDICATED_MEMORY_OBJECT_EXT: Incomplete
GL_DEVICE_UUID_EXT: Incomplete
GL_DRIVER_UUID_EXT: Incomplete
GL_LINEAR_TILING_EXT: Incomplete
GL_NUM_DEVICE_UUIDS_EXT: Incomplete
GL_NUM_TILING_TYPES_EXT: Incomplete
GL_OPTIMAL_TILING_EXT: Incomplete
GL_PROTECTED_MEMORY_OBJECT_EXT: Incomplete
GL_TEXTURE_TILING_EXT: Incomplete
GL_TILING_TYPES_EXT: Incomplete
GL_UUID_SIZE_EXT: Incomplete

@_f
def glBufferStorageMemEXT(target, size, memory, offset) -> None: ...
@_f
def glCreateMemoryObjectsEXT(n, memoryObjects) -> None: ...
@_f
def glDeleteMemoryObjectsEXT(n, memoryObjects) -> None: ...
@_f
def glGetMemoryObjectParameterivEXT(memoryObject, pname, params) -> None: ...
@_f
def glGetUnsignedBytei_vEXT(target, index, data) -> None: ...
@_f
def glGetUnsignedBytevEXT(pname, data) -> None: ...
@_f
def glIsMemoryObjectEXT(memoryObject) -> None: ...
@_f
def glMemoryObjectParameterivEXT(memoryObject, pname, params) -> None: ...
@_f
def glNamedBufferStorageMemEXT(buffer, size, memory, offset) -> None: ...
@_f
def glTexStorageMem1DEXT(target, levels, internalFormat, width, memory, offset) -> None: ...
@_f
def glTexStorageMem2DEXT(target, levels, internalFormat, width, height, memory, offset) -> None: ...
@_f
def glTexStorageMem2DMultisampleEXT(target, samples, internalFormat, width, height, fixedSampleLocations, memory, offset) -> None: ...
@_f
def glTexStorageMem3DEXT(target, levels, internalFormat, width, height, depth, memory, offset) -> None: ...
@_f
def glTexStorageMem3DMultisampleEXT(target, samples, internalFormat, width, height, depth, fixedSampleLocations, memory, offset) -> None: ...
@_f
def glTextureStorageMem1DEXT(texture, levels, internalFormat, width, memory, offset) -> None: ...
@_f
def glTextureStorageMem2DEXT(texture, levels, internalFormat, width, height, memory, offset) -> None: ...
@_f
def glTextureStorageMem2DMultisampleEXT(texture, samples, internalFormat, width, height, fixedSampleLocations, memory, offset) -> None: ...
@_f
def glTextureStorageMem3DEXT(texture, levels, internalFormat, width, height, depth, memory, offset) -> None: ...
@_f
def glTextureStorageMem3DMultisampleEXT(texture, samples, internalFormat, width, height, depth, fixedSampleLocations, memory, offset) -> None: ...
