from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_COLOR_SUM_EXT: Incomplete
GL_CURRENT_SECONDARY_COLOR_EXT: Incomplete
GL_SECONDARY_COLOR_ARRAY_EXT: Incomplete
GL_SECONDARY_COLOR_ARRAY_POINTER_EXT: Incomplete
GL_SECONDARY_COLOR_ARRAY_SIZE_EXT: Incomplete
GL_SECONDARY_COLOR_ARRAY_STRIDE_EXT: Incomplete
GL_SECONDARY_COLOR_ARRAY_TYPE_EXT: Incomplete

@_f
def glSecondaryColor3bEXT(red, green, blue) -> None: ...
@_f
def glSecondaryColor3bvEXT(v) -> None: ...
@_f
def glSecondaryColor3dEXT(red, green, blue) -> None: ...
@_f
def glSecondaryColor3dvEXT(v) -> None: ...
@_f
def glSecondaryColor3fEXT(red, green, blue) -> None: ...
@_f
def glSecondaryColor3fvEXT(v) -> None: ...
@_f
def glSecondaryColor3iEXT(red, green, blue) -> None: ...
@_f
def glSecondaryColor3ivEXT(v) -> None: ...
@_f
def glSecondaryColor3sEXT(red, green, blue) -> None: ...
@_f
def glSecondaryColor3svEXT(v) -> None: ...
@_f
def glSecondaryColor3ubEXT(red, green, blue) -> None: ...
@_f
def glSecondaryColor3ubvEXT(v) -> None: ...
@_f
def glSecondaryColor3uiEXT(red, green, blue) -> None: ...
@_f
def glSecondaryColor3uivEXT(v) -> None: ...
@_f
def glSecondaryColor3usEXT(red, green, blue) -> None: ...
@_f
def glSecondaryColor3usvEXT(v) -> None: ...
@_f
def glSecondaryColorPointerEXT(size, type, stride, pointer) -> None: ...
