from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_UNSIGNED_INT64_ARB: Incomplete

@_f
def glGetImageHandleARB(texture, level, layered, layer, format) -> None: ...
@_f
def glGetTextureHandleARB(texture) -> None: ...
@_f
def glGetTextureSamplerHandleARB(texture, sampler) -> None: ...
@_f
def glGetVertexAttribLui64vARB(index, pname, params) -> None: ...
@_f
def glIsImageHandleResidentARB(handle) -> None: ...
@_f
def glIsTextureHandleResidentARB(handle) -> None: ...
@_f
def glMakeImageHandleNonResidentARB(handle) -> None: ...
@_f
def glMakeImageHandleResidentARB(handle, access) -> None: ...
@_f
def glMakeTextureHandleNonResidentARB(handle) -> None: ...
@_f
def glMakeTextureHandleResidentARB(handle) -> None: ...
@_f
def glProgramUniformHandleui64ARB(program, location, value) -> None: ...
@_f
def glProgramUniformHandleui64vARB(program, location, count, values) -> None: ...
@_f
def glUniformHandleui64ARB(location, value) -> None: ...
@_f
def glUniformHandleui64vARB(location, count, value) -> None: ...
@_f
def glVertexAttribL1ui64ARB(index, x) -> None: ...
@_f
def glVertexAttribL1ui64vARB(index, v) -> None: ...
