from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_QUERY_TARGET: Incomplete
GL_TEXTURE_BINDING_1D: Incomplete
GL_TEXTURE_BINDING_1D_ARRAY: Incomplete
GL_TEXTURE_BINDING_2D: Incomplete
GL_TEXTURE_BINDING_2D_ARRAY: Incomplete
GL_TEXTURE_BINDING_2D_MULTISAMPLE: Incomplete
GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY: Incomplete
GL_TEXTURE_BINDING_3D: Incomplete
GL_TEXTURE_BINDING_BUFFER: Incomplete
GL_TEXTURE_BINDING_CUBE_MAP: Incomplete
GL_TEXTURE_BINDING_CUBE_MAP_ARRAY: Incomplete
GL_TEXTURE_BINDING_RECTANGLE: Incomplete
GL_TEXTURE_TARGET: Incomplete

@_f
def glBindTextureUnit(unit, texture) -> None: ...
@_f
def glBlitNamedFramebuffer(readFramebuffer, drawFramebuffer, srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter) -> None: ...
@_f
def glCheckNamedFramebufferStatus(framebuffer, target) -> None: ...
@_f
def glClearNamedBufferData(buffer, internalformat, format, type, data) -> None: ...
@_f
def glClearNamedBufferSubData(buffer, internalformat, offset, size, format, type, data) -> None: ...
@_f
def glClearNamedFramebufferfi(framebuffer, buffer, drawbuffer, depth, stencil) -> None: ...
@_f
def glClearNamedFramebufferfv(framebuffer, buffer, drawbuffer, value) -> None: ...
@_f
def glClearNamedFramebufferiv(framebuffer, buffer, drawbuffer, value) -> None: ...
@_f
def glClearNamedFramebufferuiv(framebuffer, buffer, drawbuffer, value) -> None: ...
@_f
def glCompressedTextureSubImage1D(texture, level, xoffset, width, format, imageSize, data) -> None: ...
@_f
def glCompressedTextureSubImage2D(texture, level, xoffset, yoffset, width, height, format, imageSize, data) -> None: ...
@_f
def glCompressedTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, data) -> None: ...
@_f
def glCopyNamedBufferSubData(readBuffer, writeBuffer, readOffset, writeOffset, size) -> None: ...
@_f
def glCopyTextureSubImage1D(texture, level, xoffset, x, y, width) -> None: ...
@_f
def glCopyTextureSubImage2D(texture, level, xoffset, yoffset, x, y, width, height) -> None: ...
@_f
def glCopyTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, x, y, width, height) -> None: ...
@_f
def glCreateBuffers(n, buffers) -> None: ...
@_f
def glCreateFramebuffers(n, framebuffers) -> None: ...
@_f
def glCreateProgramPipelines(n, pipelines) -> None: ...
@_f
def glCreateQueries(target, n, ids) -> None: ...
@_f
def glCreateRenderbuffers(n, renderbuffers) -> None: ...
@_f
def glCreateSamplers(n, samplers) -> None: ...
@_f
def glCreateTextures(target, n, textures) -> None: ...
@_f
def glCreateTransformFeedbacks(n, ids) -> None: ...
@_f
def glCreateVertexArrays(n, arrays) -> None: ...
@_f
def glDisableVertexArrayAttrib(vaobj, index) -> None: ...
@_f
def glEnableVertexArrayAttrib(vaobj, index) -> None: ...
@_f
def glFlushMappedNamedBufferRange(buffer, offset, length) -> None: ...
@_f
def glGenerateTextureMipmap(texture) -> None: ...
@_f
def glGetCompressedTextureImage(texture, level, bufSize, pixels) -> None: ...
@_f
def glGetNamedBufferParameteri64v(buffer, pname, params) -> None: ...
@_f
def glGetNamedBufferParameteriv(buffer, pname, params) -> None: ...
@_f
def glGetNamedBufferPointerv(buffer, pname, params) -> None: ...
@_f
def glGetNamedBufferSubData(buffer, offset, size, data) -> None: ...
@_f
def glGetNamedFramebufferAttachmentParameteriv(framebuffer, attachment, pname, params) -> None: ...
@_f
def glGetNamedFramebufferParameteriv(framebuffer, pname, param) -> None: ...
@_f
def glGetNamedRenderbufferParameteriv(renderbuffer, pname, params) -> None: ...
@_f
def glGetQueryBufferObjecti64v(id, buffer, pname, offset) -> None: ...
@_f
def glGetQueryBufferObjectiv(id, buffer, pname, offset) -> None: ...
@_f
def glGetQueryBufferObjectui64v(id, buffer, pname, offset) -> None: ...
@_f
def glGetQueryBufferObjectuiv(id, buffer, pname, offset) -> None: ...
@_f
def glGetTextureImage(texture, level, format, type, bufSize, pixels) -> None: ...
@_f
def glGetTextureLevelParameterfv(texture, level, pname, params) -> None: ...
@_f
def glGetTextureLevelParameteriv(texture, level, pname, params) -> None: ...
@_f
def glGetTextureParameterIiv(texture, pname, params) -> None: ...
@_f
def glGetTextureParameterIuiv(texture, pname, params) -> None: ...
@_f
def glGetTextureParameterfv(texture, pname, params) -> None: ...
@_f
def glGetTextureParameteriv(texture, pname, params) -> None: ...
@_f
def glGetTransformFeedbacki64_v(xfb, pname, index, param) -> None: ...
@_f
def glGetTransformFeedbacki_v(xfb, pname, index, param) -> None: ...
@_f
def glGetTransformFeedbackiv(xfb, pname, param) -> None: ...
@_f
def glGetVertexArrayIndexed64iv(vaobj, index, pname, param) -> None: ...
@_f
def glGetVertexArrayIndexediv(vaobj, index, pname, param) -> None: ...
@_f
def glGetVertexArrayiv(vaobj, pname, param) -> None: ...
@_f
def glInvalidateNamedFramebufferData(framebuffer, numAttachments, attachments) -> None: ...
@_f
def glInvalidateNamedFramebufferSubData(framebuffer, numAttachments, attachments, x, y, width, height) -> None: ...
@_f
def glMapNamedBuffer(buffer, access) -> None: ...
@_f
def glMapNamedBufferRange(buffer, offset, length, access) -> None: ...
@_f
def glNamedBufferData(buffer, size, data, usage) -> None: ...
@_f
def glNamedBufferStorage(buffer, size, data, flags) -> None: ...
@_f
def glNamedBufferSubData(buffer, offset, size, data) -> None: ...
@_f
def glNamedFramebufferDrawBuffer(framebuffer, buf) -> None: ...
@_f
def glNamedFramebufferDrawBuffers(framebuffer, n, bufs) -> None: ...
@_f
def glNamedFramebufferParameteri(framebuffer, pname, param) -> None: ...
@_f
def glNamedFramebufferReadBuffer(framebuffer, src) -> None: ...
@_f
def glNamedFramebufferRenderbuffer(framebuffer, attachment, renderbuffertarget, renderbuffer) -> None: ...
@_f
def glNamedFramebufferTexture(framebuffer, attachment, texture, level) -> None: ...
@_f
def glNamedFramebufferTextureLayer(framebuffer, attachment, texture, level, layer) -> None: ...
@_f
def glNamedRenderbufferStorage(renderbuffer, internalformat, width, height) -> None: ...
@_f
def glNamedRenderbufferStorageMultisample(renderbuffer, samples, internalformat, width, height) -> None: ...
@_f
def glTextureBuffer(texture, internalformat, buffer) -> None: ...
@_f
def glTextureBufferRange(texture, internalformat, buffer, offset, size) -> None: ...
@_f
def glTextureParameterIiv(texture, pname, params) -> None: ...
@_f
def glTextureParameterIuiv(texture, pname, params) -> None: ...
@_f
def glTextureParameterf(texture, pname, param) -> None: ...
@_f
def glTextureParameterfv(texture, pname, param) -> None: ...
@_f
def glTextureParameteri(texture, pname, param) -> None: ...
@_f
def glTextureParameteriv(texture, pname, param) -> None: ...
@_f
def glTextureStorage1D(texture, levels, internalformat, width) -> None: ...
@_f
def glTextureStorage2D(texture, levels, internalformat, width, height) -> None: ...
@_f
def glTextureStorage2DMultisample(texture, samples, internalformat, width, height, fixedsamplelocations) -> None: ...
@_f
def glTextureStorage3D(texture, levels, internalformat, width, height, depth) -> None: ...
@_f
def glTextureStorage3DMultisample(texture, samples, internalformat, width, height, depth, fixedsamplelocations) -> None: ...
@_f
def glTextureSubImage1D(texture, level, xoffset, width, format, type, pixels) -> None: ...
@_f
def glTextureSubImage2D(texture, level, xoffset, yoffset, width, height, format, type, pixels) -> None: ...
@_f
def glTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels) -> None: ...
@_f
def glTransformFeedbackBufferBase(xfb, index, buffer) -> None: ...
@_f
def glTransformFeedbackBufferRange(xfb, index, buffer, offset, size) -> None: ...
@_f
def glUnmapNamedBuffer(buffer) -> None: ...
@_f
def glVertexArrayAttribBinding(vaobj, attribindex, bindingindex) -> None: ...
@_f
def glVertexArrayAttribFormat(vaobj, attribindex, size, type, normalized, relativeoffset) -> None: ...
@_f
def glVertexArrayAttribIFormat(vaobj, attribindex, size, type, relativeoffset) -> None: ...
@_f
def glVertexArrayAttribLFormat(vaobj, attribindex, size, type, relativeoffset) -> None: ...
@_f
def glVertexArrayBindingDivisor(vaobj, bindingindex, divisor) -> None: ...
@_f
def glVertexArrayElementBuffer(vaobj, buffer) -> None: ...
@_f
def glVertexArrayVertexBuffer(vaobj, bindingindex, buffer, offset, stride) -> None: ...
@_f
def glVertexArrayVertexBuffers(vaobj, first, count, buffers, offsets, strides) -> None: ...
