from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glBlendEquationSeparateiARB(buf, modeRGB, modeAlpha) -> None: ...
@_f
def glBlendEquationiARB(buf, mode) -> None: ...
@_f
def glBlendFuncSeparateiARB(buf, srcRGB, dstRGB, srcAlpha, dstAlpha) -> None: ...
@_f
def glBlendFunciARB(buf, src, dst) -> None: ...
