from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glDrawElementsBaseVertex(mode, count, type, indices, basevertex) -> None: ...
@_f
def glDrawElementsInstancedBaseVertex(mode, count, type, indices, instancecount, basevertex) -> None: ...
@_f
def glDrawRangeElementsBaseVertex(mode, start, end, count, type, indices, basevertex) -> None: ...
@_f
def glMultiDrawElementsBaseVertex(mode, count, type, indices, drawcount, basevertex) -> None: ...
