from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_DOUBLE: Incomplete
GL_DOUBLE_MAT2: Incomplete
GL_DOUBLE_MAT2x3: Incomplete
GL_DOUBLE_MAT2x4: Incomplete
GL_DOUBLE_MAT3: Incomplete
GL_DOUBLE_MAT3x2: Incomplete
GL_DOUBLE_MAT3x4: Incomplete
GL_DOUBLE_MAT4: Incomplete
GL_DOUBLE_MAT4x2: Incomplete
GL_DOUBLE_MAT4x3: Incomplete
GL_DOUBLE_VEC2: Incomplete
GL_DOUBLE_VEC3: Incomplete
GL_DOUBLE_VEC4: Incomplete

@_f
def glGetUniformdv(program, location, params) -> None: ...
@_f
def glUniform1d(location, x) -> None: ...
@_f
def glUniform1dv(location, count, value) -> None: ...
@_f
def glUniform2d(location, x, y) -> None: ...
@_f
def glUniform2dv(location, count, value) -> None: ...
@_f
def glUniform3d(location, x, y, z) -> None: ...
@_f
def glUniform3dv(location, count, value) -> None: ...
@_f
def glUniform4d(location, x, y, z, w) -> None: ...
@_f
def glUniform4dv(location, count, value) -> None: ...
@_f
def glUniformMatrix2dv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix2x3dv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix2x4dv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix3dv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix3x2dv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix3x4dv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix4dv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix4x2dv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix4x3dv(location, count, transpose, value) -> None: ...
