from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_INT64_ARB: Incomplete
GL_INT64_VEC2_ARB: Incomplete
GL_INT64_VEC3_ARB: Incomplete
GL_INT64_VEC4_ARB: Incomplete
GL_UNSIGNED_INT64_ARB: Incomplete
GL_UNSIGNED_INT64_VEC2_ARB: Incomplete
GL_UNSIGNED_INT64_VEC3_ARB: Incomplete
GL_UNSIGNED_INT64_VEC4_ARB: Incomplete

@_f
def glGetUniformi64vARB(program, location, params) -> None: ...
@_f
def glGetUniformui64vARB(program, location, params) -> None: ...
@_f
def glGetnUniformi64vARB(program, location, bufSize, params) -> None: ...
@_f
def glGetnUniformui64vARB(program, location, bufSize, params) -> None: ...
@_f
def glProgramUniform1i64ARB(program, location, x) -> None: ...
@_f
def glProgramUniform1i64vARB(program, location, count, value) -> None: ...
@_f
def glProgramUniform1ui64ARB(program, location, x) -> None: ...
@_f
def glProgramUniform1ui64vARB(program, location, count, value) -> None: ...
@_f
def glProgramUniform2i64ARB(program, location, x, y) -> None: ...
@_f
def glProgramUniform2i64vARB(program, location, count, value) -> None: ...
@_f
def glProgramUniform2ui64ARB(program, location, x, y) -> None: ...
@_f
def glProgramUniform2ui64vARB(program, location, count, value) -> None: ...
@_f
def glProgramUniform3i64ARB(program, location, x, y, z) -> None: ...
@_f
def glProgramUniform3i64vARB(program, location, count, value) -> None: ...
@_f
def glProgramUniform3ui64ARB(program, location, x, y, z) -> None: ...
@_f
def glProgramUniform3ui64vARB(program, location, count, value) -> None: ...
@_f
def glProgramUniform4i64ARB(program, location, x, y, z, w) -> None: ...
@_f
def glProgramUniform4i64vARB(program, location, count, value) -> None: ...
@_f
def glProgramUniform4ui64ARB(program, location, x, y, z, w) -> None: ...
@_f
def glProgramUniform4ui64vARB(program, location, count, value) -> None: ...
@_f
def glUniform1i64ARB(location, x) -> None: ...
@_f
def glUniform1i64vARB(location, count, value) -> None: ...
@_f
def glUniform1ui64ARB(location, x) -> None: ...
@_f
def glUniform1ui64vARB(location, count, value) -> None: ...
@_f
def glUniform2i64ARB(location, x, y) -> None: ...
@_f
def glUniform2i64vARB(location, count, value) -> None: ...
@_f
def glUniform2ui64ARB(location, x, y) -> None: ...
@_f
def glUniform2ui64vARB(location, count, value) -> None: ...
@_f
def glUniform3i64ARB(location, x, y, z) -> None: ...
@_f
def glUniform3i64vARB(location, count, value) -> None: ...
@_f
def glUniform3ui64ARB(location, x, y, z) -> None: ...
@_f
def glUniform3ui64vARB(location, count, value) -> None: ...
@_f
def glUniform4i64ARB(location, x, y, z, w) -> None: ...
@_f
def glUniform4i64vARB(location, count, value) -> None: ...
@_f
def glUniform4ui64ARB(location, x, y, z, w) -> None: ...
@_f
def glUniform4ui64vARB(location, count, value) -> None: ...
