from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glInvalidateBufferData(buffer) -> None: ...
@_f
def glInvalidateBufferSubData(buffer, offset, length) -> None: ...
@_f
def glInvalidateFramebuffer(target, numAttachments, attachments) -> None: ...
@_f
def glInvalidateSubFramebuffer(target, numAttachments, attachments, x, y, width, height) -> None: ...
@_f
def glInvalidateTexImage(texture, level) -> None: ...
@_f
def glInvalidateTexSubImage(texture, level, xoffset, yoffset, zoffset, width, height, depth) -> None: ...
