from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glBindBuffersBase(target, first, count, buffers) -> None: ...
@_f
def glBindBuffersRange(target, first, count, buffers, offsets, sizes) -> None: ...
@_f
def glBindImageTextures(first, count, textures) -> None: ...
@_f
def glBindSamplers(first, count, samplers) -> None: ...
@_f
def glBindTextures(first, count, textures) -> None: ...
@_f
def glBindVertexBuffers(first, count, buffers, offsets, strides) -> None: ...
