from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ACTIVE_TEXTURE_ARB: Incomplete
GL_CLIENT_ACTIVE_TEXTURE_ARB: Incomplete
GL_MAX_TEXTURE_UNITS_ARB: Incomplete
GL_TEXTURE0_ARB: Incomplete
GL_TEXTURE10_ARB: Incomplete
GL_TEXTURE11_ARB: Incomplete
GL_TEXTURE12_ARB: Incomplete
GL_TEXTURE13_ARB: Incomplete
GL_TEXTURE14_ARB: Incomplete
GL_TEXTURE15_ARB: Incomplete
GL_TEXTURE16_ARB: Incomplete
GL_TEXTURE17_ARB: Incomplete
GL_TEXTURE18_ARB: Incomplete
GL_TEXTURE19_ARB: Incomplete
GL_TEXTURE1_ARB: Incomplete
GL_TEXTURE20_ARB: Incomplete
GL_TEXTURE21_ARB: Incomplete
GL_TEXTURE22_ARB: Incomplete
GL_TEXTURE23_ARB: Incomplete
GL_TEXTURE24_ARB: Incomplete
GL_TEXTURE25_ARB: Incomplete
GL_TEXTURE26_ARB: Incomplete
GL_TEXTURE27_ARB: Incomplete
GL_TEXTURE28_ARB: Incomplete
GL_TEXTURE29_ARB: Incomplete
GL_TEXTURE2_ARB: Incomplete
GL_TEXTURE30_ARB: Incomplete
GL_TEXTURE31_ARB: Incomplete
GL_TEXTURE3_ARB: Incomplete
GL_TEXTURE4_ARB: Incomplete
GL_TEXTURE5_ARB: Incomplete
GL_TEXTURE6_ARB: Incomplete
GL_TEXTURE7_ARB: Incomplete
GL_TEXTURE8_ARB: Incomplete
GL_TEXTURE9_ARB: Incomplete

@_f
def glActiveTextureARB(texture) -> None: ...
@_f
def glClientActiveTextureARB(texture) -> None: ...
@_f
def glMultiTexCoord1dARB(target, s) -> None: ...
@_f
def glMultiTexCoord1dvARB(target, v) -> None: ...
@_f
def glMultiTexCoord1fARB(target, s) -> None: ...
@_f
def glMultiTexCoord1fvARB(target, v) -> None: ...
@_f
def glMultiTexCoord1iARB(target, s) -> None: ...
@_f
def glMultiTexCoord1ivARB(target, v) -> None: ...
@_f
def glMultiTexCoord1sARB(target, s) -> None: ...
@_f
def glMultiTexCoord1svARB(target, v) -> None: ...
@_f
def glMultiTexCoord2dARB(target, s, t) -> None: ...
@_f
def glMultiTexCoord2dvARB(target, v) -> None: ...
@_f
def glMultiTexCoord2fARB(target, s, t) -> None: ...
@_f
def glMultiTexCoord2fvARB(target, v) -> None: ...
@_f
def glMultiTexCoord2iARB(target, s, t) -> None: ...
@_f
def glMultiTexCoord2ivARB(target, v) -> None: ...
@_f
def glMultiTexCoord2sARB(target, s, t) -> None: ...
@_f
def glMultiTexCoord2svARB(target, v) -> None: ...
@_f
def glMultiTexCoord3dARB(target, s, t, r) -> None: ...
@_f
def glMultiTexCoord3dvARB(target, v) -> None: ...
@_f
def glMultiTexCoord3fARB(target, s, t, r) -> None: ...
@_f
def glMultiTexCoord3fvARB(target, v) -> None: ...
@_f
def glMultiTexCoord3iARB(target, s, t, r) -> None: ...
@_f
def glMultiTexCoord3ivARB(target, v) -> None: ...
@_f
def glMultiTexCoord3sARB(target, s, t, r) -> None: ...
@_f
def glMultiTexCoord3svARB(target, v) -> None: ...
@_f
def glMultiTexCoord4dARB(target, s, t, r, q) -> None: ...
@_f
def glMultiTexCoord4dvARB(target, v) -> None: ...
@_f
def glMultiTexCoord4fARB(target, s, t, r, q) -> None: ...
@_f
def glMultiTexCoord4fvARB(target, v) -> None: ...
@_f
def glMultiTexCoord4iARB(target, s, t, r, q) -> None: ...
@_f
def glMultiTexCoord4ivARB(target, v) -> None: ...
@_f
def glMultiTexCoord4sARB(target, s, t, r, q) -> None: ...
@_f
def glMultiTexCoord4svARB(target, v) -> None: ...
