from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT_ARB: Incomplete
GL_GUILTY_CONTEXT_RESET_ARB: Incomplete
GL_INNOCENT_CONTEXT_RESET_ARB: Incomplete
GL_LOSE_CONTEXT_ON_RESET_ARB: Incomplete
GL_NO_ERROR: Incomplete
GL_NO_RESET_NOTIFICATION_ARB: Incomplete
GL_RESET_NOTIFICATION_STRATEGY_ARB: Incomplete
GL_UNKNOWN_CONTEXT_RESET_ARB: Incomplete

@_f
def glGetGraphicsResetStatusARB() -> None: ...
@_f
def glGetnColorTableARB(target, format, type, bufSize, table) -> None: ...
@_f
def glGetnCompressedTexImageARB(target, lod, bufSize, img) -> None: ...
@_f
def glGetnConvolutionFilterARB(target, format, type, bufSize, image) -> None: ...
@_f
def glGetnHistogramARB(target, reset, format, type, bufSize, values) -> None: ...
@_f
def glGetnMapdvARB(target, query, bufSize, v) -> None: ...
@_f
def glGetnMapfvARB(target, query, bufSize, v) -> None: ...
@_f
def glGetnMapivARB(target, query, bufSize, v) -> None: ...
@_f
def glGetnMinmaxARB(target, reset, format, type, bufSize, values) -> None: ...
@_f
def glGetnPixelMapfvARB(map, bufSize, values) -> None: ...
@_f
def glGetnPixelMapuivARB(map, bufSize, values) -> None: ...
@_f
def glGetnPixelMapusvARB(map, bufSize, values) -> None: ...
@_f
def glGetnPolygonStippleARB(bufSize, pattern) -> None: ...
@_f
def glGetnSeparableFilterARB(target, format, type, rowBufSize, row, columnBufSize, column, span) -> None: ...
@_f
def glGetnTexImageARB(target, level, format, type, bufSize, img) -> None: ...
@_f
def glGetnUniformdvARB(program, location, bufSize, params) -> None: ...
@_f
def glGetnUniformfvARB(program, location, bufSize, params) -> None: ...
@_f
def glGetnUniformivARB(program, location, bufSize, params) -> None: ...
@_f
def glGetnUniformuivARB(program, location, bufSize, params) -> None: ...
@_f
def glReadnPixelsARB(x, y, width, height, format, type, bufSize, data) -> None: ...
