from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ACTIVE_PROGRAM: Incomplete
GL_ALL_SHADER_BITS: Incomplete
GL_FRAGMENT_SHADER_BIT: Incomplete
GL_GEOMETRY_SHADER_BIT: Incomplete
GL_PROGRAM_PIPELINE_BINDING: Incomplete
GL_PROGRAM_SEPARABLE: Incomplete
GL_TESS_CONTROL_SHADER_BIT: Incomplete
GL_TESS_EVALUATION_SHADER_BIT: Incomplete
GL_VERTEX_SHADER_BIT: Incomplete

@_f
def glActiveShaderProgram(pipeline, program) -> None: ...
@_f
def glBindProgramPipeline(pipeline) -> None: ...
@_f
def glCreateShaderProgramv(type, count, strings) -> None: ...
@_f
def glDeleteProgramPipelines(n, pipelines) -> None: ...
@_f
def glGenProgramPipelines(n, pipelines) -> None: ...
@_f
def glGetProgramPipelineInfoLog(pipeline, bufSize, length, infoLog) -> None: ...
@_f
def glGetProgramPipelineiv(pipeline, pname, params) -> None: ...
@_f
def glIsProgramPipeline(pipeline) -> None: ...
@_f
def glProgramParameteri(program, pname, value) -> None: ...
@_f
def glProgramUniform1d(program, location, v0) -> None: ...
@_f
def glProgramUniform1dv(program, location, count, value) -> None: ...
@_f
def glProgramUniform1f(program, location, v0) -> None: ...
@_f
def glProgramUniform1fv(program, location, count, value) -> None: ...
@_f
def glProgramUniform1i(program, location, v0) -> None: ...
@_f
def glProgramUniform1iv(program, location, count, value) -> None: ...
@_f
def glProgramUniform1ui(program, location, v0) -> None: ...
@_f
def glProgramUniform1uiv(program, location, count, value) -> None: ...
@_f
def glProgramUniform2d(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2dv(program, location, count, value) -> None: ...
@_f
def glProgramUniform2f(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2fv(program, location, count, value) -> None: ...
@_f
def glProgramUniform2i(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2iv(program, location, count, value) -> None: ...
@_f
def glProgramUniform2ui(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2uiv(program, location, count, value) -> None: ...
@_f
def glProgramUniform3d(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3dv(program, location, count, value) -> None: ...
@_f
def glProgramUniform3f(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3fv(program, location, count, value) -> None: ...
@_f
def glProgramUniform3i(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3iv(program, location, count, value) -> None: ...
@_f
def glProgramUniform3ui(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3uiv(program, location, count, value) -> None: ...
@_f
def glProgramUniform4d(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4dv(program, location, count, value) -> None: ...
@_f
def glProgramUniform4f(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4fv(program, location, count, value) -> None: ...
@_f
def glProgramUniform4i(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4iv(program, location, count, value) -> None: ...
@_f
def glProgramUniform4ui(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4uiv(program, location, count, value) -> None: ...
@_f
def glProgramUniformMatrix2dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x3dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x3fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x4dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x4fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x2dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x2fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x4dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x4fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x2dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x2fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x3dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x3fv(program, location, count, transpose, value) -> None: ...
@_f
def glUseProgramStages(pipeline, stages, program) -> None: ...
@_f
def glValidateProgramPipeline(pipeline) -> None: ...
