from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_BOOL_ARB: Incomplete
GL_BOOL_VEC2_ARB: Incomplete
GL_BOOL_VEC3_ARB: Incomplete
GL_BOOL_VEC4_ARB: Incomplete
GL_FLOAT_MAT2_ARB: Incomplete
GL_FLOAT_MAT3_ARB: Incomplete
GL_FLOAT_MAT4_ARB: Incomplete
GL_FLOAT_VEC2_ARB: Incomplete
GL_FLOAT_VEC3_ARB: Incomplete
GL_FLOAT_VEC4_ARB: Incomplete
GL_INT_VEC2_ARB: Incomplete
GL_INT_VEC3_ARB: Incomplete
GL_INT_VEC4_ARB: Incomplete
GL_OBJECT_ACTIVE_UNIFORMS_ARB: Incomplete
GL_OBJECT_ACTIVE_UNIFORM_MAX_LENGTH_ARB: Incomplete
GL_OBJECT_ATTACHED_OBJECTS_ARB: Incomplete
GL_OBJECT_COMPILE_STATUS_ARB: Incomplete
GL_OBJECT_DELETE_STATUS_ARB: Incomplete
GL_OBJECT_INFO_LOG_LENGTH_ARB: Incomplete
GL_OBJECT_LINK_STATUS_ARB: Incomplete
GL_OBJECT_SHADER_SOURCE_LENGTH_ARB: Incomplete
GL_OBJECT_SUBTYPE_ARB: Incomplete
GL_OBJECT_TYPE_ARB: Incomplete
GL_OBJECT_VALIDATE_STATUS_ARB: Incomplete
GL_PROGRAM_OBJECT_ARB: Incomplete
GL_SAMPLER_1D_ARB: Incomplete
GL_SAMPLER_1D_SHADOW_ARB: Incomplete
GL_SAMPLER_2D_ARB: Incomplete
GL_SAMPLER_2D_RECT_ARB: Incomplete
GL_SAMPLER_2D_RECT_SHADOW_ARB: Incomplete
GL_SAMPLER_2D_SHADOW_ARB: Incomplete
GL_SAMPLER_3D_ARB: Incomplete
GL_SAMPLER_CUBE_ARB: Incomplete
GL_SHADER_OBJECT_ARB: Incomplete

@_f
def glAttachObjectARB(containerObj, obj) -> None: ...
@_f
def glCompileShaderARB(shaderObj) -> None: ...
@_f
def glCreateProgramObjectARB() -> None: ...
@_f
def glCreateShaderObjectARB(shaderType) -> None: ...
@_f
def glDeleteObjectARB(obj) -> None: ...
@_f
def glDetachObjectARB(containerObj, attachedObj) -> None: ...
@_f
def glGetActiveUniformARB(programObj, index, maxLength, length, size, type, name) -> None: ...
@_f
def glGetAttachedObjectsARB(containerObj, maxCount, count, obj) -> None: ...
@_f
def glGetHandleARB(pname) -> None: ...
@_f
def glGetInfoLogARB(obj, maxLength, length, infoLog) -> None: ...
@_f
def glGetObjectParameterfvARB(obj, pname, params) -> None: ...
@_f
def glGetObjectParameterivARB(obj, pname, params) -> None: ...
@_f
def glGetShaderSourceARB(obj, maxLength, length, source) -> None: ...
@_f
def glGetUniformLocationARB(programObj, name) -> None: ...
@_f
def glGetUniformfvARB(programObj, location, params) -> None: ...
@_f
def glGetUniformivARB(programObj, location, params) -> None: ...
@_f
def glLinkProgramARB(programObj) -> None: ...
@_f
def glShaderSourceARB(shaderObj, count, string, length) -> None: ...
@_f
def glUniform1fARB(location, v0) -> None: ...
@_f
def glUniform1fvARB(location, count, value) -> None: ...
@_f
def glUniform1iARB(location, v0) -> None: ...
@_f
def glUniform1ivARB(location, count, value) -> None: ...
@_f
def glUniform2fARB(location, v0, v1) -> None: ...
@_f
def glUniform2fvARB(location, count, value) -> None: ...
@_f
def glUniform2iARB(location, v0, v1) -> None: ...
@_f
def glUniform2ivARB(location, count, value) -> None: ...
@_f
def glUniform3fARB(location, v0, v1, v2) -> None: ...
@_f
def glUniform3fvARB(location, count, value) -> None: ...
@_f
def glUniform3iARB(location, v0, v1, v2) -> None: ...
@_f
def glUniform3ivARB(location, count, value) -> None: ...
@_f
def glUniform4fARB(location, v0, v1, v2, v3) -> None: ...
@_f
def glUniform4fvARB(location, count, value) -> None: ...
@_f
def glUniform4iARB(location, v0, v1, v2, v3) -> None: ...
@_f
def glUniform4ivARB(location, count, value) -> None: ...
@_f
def glUniformMatrix2fvARB(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix3fvARB(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix4fvARB(location, count, transpose, value) -> None: ...
@_f
def glUseProgramObjectARB(programObj) -> None: ...
@_f
def glValidateProgramARB(programObj) -> None: ...
