from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_INT_SAMPLER_CUBE_MAP_ARRAY_ARB: Incomplete
GL_PROXY_TEXTURE_CUBE_MAP_ARRAY_ARB: Incomplete
GL_SAMPLER_CUBE_MAP_ARRAY_ARB: Incomplete
GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW_ARB: Incomplete
GL_TEXTURE_BINDING_CUBE_MAP_ARRAY_ARB: Incomplete
GL_TEXTURE_CUBE_MAP_ARRAY_ARB: Incomplete
GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY_ARB: Incomplete
