from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_INT_2_10_10_10_REV: Incomplete
GL_UNSIGNED_INT_2_10_10_10_REV: Incomplete

@_f
def glColorP3ui(type, color) -> None: ...
@_f
def glColorP3uiv(type, color) -> None: ...
@_f
def glColorP4ui(type, color) -> None: ...
@_f
def glColorP4uiv(type, color) -> None: ...
@_f
def glMultiTexCoordP1ui(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP1uiv(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP2ui(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP2uiv(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP3ui(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP3uiv(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP4ui(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP4uiv(texture, type, coords) -> None: ...
@_f
def glNormalP3ui(type, coords) -> None: ...
@_f
def glNormalP3uiv(type, coords) -> None: ...
@_f
def glSecondaryColorP3ui(type, color) -> None: ...
@_f
def glSecondaryColorP3uiv(type, color) -> None: ...
@_f
def glTexCoordP1ui(type, coords) -> None: ...
@_f
def glTexCoordP1uiv(type, coords) -> None: ...
@_f
def glTexCoordP2ui(type, coords) -> None: ...
@_f
def glTexCoordP2uiv(type, coords) -> None: ...
@_f
def glTexCoordP3ui(type, coords) -> None: ...
@_f
def glTexCoordP3uiv(type, coords) -> None: ...
@_f
def glTexCoordP4ui(type, coords) -> None: ...
@_f
def glTexCoordP4uiv(type, coords) -> None: ...
@_f
def glVertexAttribP1ui(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP1uiv(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP2ui(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP2uiv(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP3ui(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP3uiv(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP4ui(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP4uiv(index, type, normalized, value) -> None: ...
@_f
def glVertexP2ui(type, value) -> None: ...
@_f
def glVertexP2uiv(type, value) -> None: ...
@_f
def glVertexP3ui(type, value) -> None: ...
@_f
def glVertexP3uiv(type, value) -> None: ...
@_f
def glVertexP4ui(type, value) -> None: ...
@_f
def glVertexP4uiv(type, value) -> None: ...
