from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_CURRENT_VERTEX_ATTRIB_ARB: Incomplete
GL_FLOAT: Incomplete
GL_FLOAT_MAT2_ARB: Incomplete
GL_FLOAT_MAT3_ARB: Incomplete
GL_FLOAT_MAT4_ARB: Incomplete
GL_FLOAT_VEC2_ARB: Incomplete
GL_FLOAT_VEC3_ARB: Incomplete
GL_FLOAT_VEC4_ARB: Incomplete
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS_ARB: Incomplete
GL_MAX_TEXTURE_COORDS_ARB: Incomplete
GL_MAX_TEXTURE_IMAGE_UNITS_ARB: Incomplete
GL_MAX_VARYING_FLOATS_ARB: Incomplete
GL_MAX_VERTEX_ATTRIBS_ARB: Incomplete
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS_ARB: Incomplete
GL_MAX_VERTEX_UNIFORM_COMPONENTS_ARB: Incomplete
GL_OBJECT_ACTIVE_ATTRIBUTES_ARB: Incomplete
GL_OBJECT_ACTIVE_ATTRIBUTE_MAX_LENGTH_ARB: Incomplete
GL_VERTEX_ATTRIB_ARRAY_ENABLED_ARB: Incomplete
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB: Incomplete
GL_VERTEX_ATTRIB_ARRAY_POINTER_ARB: Incomplete
GL_VERTEX_ATTRIB_ARRAY_SIZE_ARB: Incomplete
GL_VERTEX_ATTRIB_ARRAY_STRIDE_ARB: Incomplete
GL_VERTEX_ATTRIB_ARRAY_TYPE_ARB: Incomplete
GL_VERTEX_PROGRAM_POINT_SIZE_ARB: Incomplete
GL_VERTEX_PROGRAM_TWO_SIDE_ARB: Incomplete
GL_VERTEX_SHADER_ARB: Incomplete

@_f
def glBindAttribLocationARB(programObj, index, name) -> None: ...
@_f
def glDisableVertexAttribArrayARB(index) -> None: ...
@_f
def glEnableVertexAttribArrayARB(index) -> None: ...
@_f
def glGetActiveAttribARB(programObj, index, maxLength, length, size, type, name) -> None: ...
@_f
def glGetAttribLocationARB(programObj, name) -> None: ...
@_f
def glGetVertexAttribPointervARB(index, pname, pointer) -> None: ...
@_f
def glGetVertexAttribdvARB(index, pname, params) -> None: ...
@_f
def glGetVertexAttribfvARB(index, pname, params) -> None: ...
@_f
def glGetVertexAttribivARB(index, pname, params) -> None: ...
@_f
def glVertexAttrib1dARB(index, x) -> None: ...
@_f
def glVertexAttrib1dvARB(index, v) -> None: ...
@_f
def glVertexAttrib1fARB(index, x) -> None: ...
@_f
def glVertexAttrib1fvARB(index, v) -> None: ...
@_f
def glVertexAttrib1sARB(index, x) -> None: ...
@_f
def glVertexAttrib1svARB(index, v) -> None: ...
@_f
def glVertexAttrib2dARB(index, x, y) -> None: ...
@_f
def glVertexAttrib2dvARB(index, v) -> None: ...
@_f
def glVertexAttrib2fARB(index, x, y) -> None: ...
@_f
def glVertexAttrib2fvARB(index, v) -> None: ...
@_f
def glVertexAttrib2sARB(index, x, y) -> None: ...
@_f
def glVertexAttrib2svARB(index, v) -> None: ...
@_f
def glVertexAttrib3dARB(index, x, y, z) -> None: ...
@_f
def glVertexAttrib3dvARB(index, v) -> None: ...
@_f
def glVertexAttrib3fARB(index, x, y, z) -> None: ...
@_f
def glVertexAttrib3fvARB(index, v) -> None: ...
@_f
def glVertexAttrib3sARB(index, x, y, z) -> None: ...
@_f
def glVertexAttrib3svARB(index, v) -> None: ...
@_f
def glVertexAttrib4NbvARB(index, v) -> None: ...
@_f
def glVertexAttrib4NivARB(index, v) -> None: ...
@_f
def glVertexAttrib4NsvARB(index, v) -> None: ...
@_f
def glVertexAttrib4NubARB(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4NubvARB(index, v) -> None: ...
@_f
def glVertexAttrib4NuivARB(index, v) -> None: ...
@_f
def glVertexAttrib4NusvARB(index, v) -> None: ...
@_f
def glVertexAttrib4bvARB(index, v) -> None: ...
@_f
def glVertexAttrib4dARB(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4dvARB(index, v) -> None: ...
@_f
def glVertexAttrib4fARB(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4fvARB(index, v) -> None: ...
@_f
def glVertexAttrib4ivARB(index, v) -> None: ...
@_f
def glVertexAttrib4sARB(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4svARB(index, v) -> None: ...
@_f
def glVertexAttrib4ubvARB(index, v) -> None: ...
@_f
def glVertexAttrib4uivARB(index, v) -> None: ...
@_f
def glVertexAttrib4usvARB(index, v) -> None: ...
@_f
def glVertexAttribPointerARB(index, size, type, normalized, stride, pointer) -> None: ...
