from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glWindowPos2dARB(x, y) -> None: ...
@_f
def glWindowPos2dvARB(v) -> None: ...
@_f
def glWindowPos2fARB(x, y) -> None: ...
@_f
def glWindowPos2fvARB(v) -> None: ...
@_f
def glWindowPos2iARB(x, y) -> None: ...
@_f
def glWindowPos2ivARB(v) -> None: ...
@_f
def glWindowPos2sARB(x, y) -> None: ...
@_f
def glWindowPos2svARB(v) -> None: ...
@_f
def glWindowPos3dARB(x, y, z) -> None: ...
@_f
def glWindowPos3dvARB(v) -> None: ...
@_f
def glWindowPos3fARB(x, y, z) -> None: ...
@_f
def glWindowPos3fvARB(v) -> None: ...
@_f
def glWindowPos3iARB(x, y, z) -> None: ...
@_f
def glWindowPos3ivARB(v) -> None: ...
@_f
def glWindowPos3sARB(x, y, z) -> None: ...
@_f
def glWindowPos3svARB(v) -> None: ...
