from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_COLOR_ATTACHMENT0_EXT: Incomplete
GL_COLOR_ATTACHMENT10_EXT: Incomplete
GL_COLOR_ATTACHMENT11_EXT: Incomplete
GL_COLOR_ATTACHMENT12_EXT: Incomplete
GL_COLOR_ATTACHMENT13_EXT: Incomplete
GL_COLOR_ATTACHMENT14_EXT: Incomplete
GL_COLOR_ATTACHMENT15_EXT: Incomplete
GL_COLOR_ATTACHMENT1_EXT: Incomplete
GL_COLOR_ATTACHMENT2_EXT: Incomplete
GL_COLOR_ATTACHMENT3_EXT: Incomplete
GL_COLOR_ATTACHMENT4_EXT: Incomplete
GL_COLOR_ATTACHMENT5_EXT: Incomplete
GL_COLOR_ATTACHMENT6_EXT: Incomplete
GL_COLOR_ATTACHMENT7_EXT: Incomplete
GL_COLOR_ATTACHMENT8_EXT: Incomplete
GL_COLOR_ATTACHMENT9_EXT: Incomplete
GL_DRAW_BUFFER0_EXT: Incomplete
GL_DRAW_BUFFER10_EXT: Incomplete
GL_DRAW_BUFFER11_EXT: Incomplete
GL_DRAW_BUFFER12_EXT: Incomplete
GL_DRAW_BUFFER13_EXT: Incomplete
GL_DRAW_BUFFER14_EXT: Incomplete
GL_DRAW_BUFFER15_EXT: Incomplete
GL_DRAW_BUFFER1_EXT: Incomplete
GL_DRAW_BUFFER2_EXT: Incomplete
GL_DRAW_BUFFER3_EXT: Incomplete
GL_DRAW_BUFFER4_EXT: Incomplete
GL_DRAW_BUFFER5_EXT: Incomplete
GL_DRAW_BUFFER6_EXT: Incomplete
GL_DRAW_BUFFER7_EXT: Incomplete
GL_DRAW_BUFFER8_EXT: Incomplete
GL_DRAW_BUFFER9_EXT: Incomplete
GL_MAX_COLOR_ATTACHMENTS_EXT: Incomplete
GL_MAX_DRAW_BUFFERS_EXT: Incomplete

@_f
def glDrawBuffersEXT(n, bufs) -> None: ...
