from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ACTIVE_PROGRAM_EXT: Incomplete
GL_ALL_SHADER_BITS_EXT: Incomplete
GL_FRAGMENT_SHADER_BIT_EXT: Incomplete
GL_PROGRAM_PIPELINE_BINDING_EXT: Incomplete
GL_PROGRAM_SEPARABLE_EXT: Incomplete
GL_VERTEX_SHADER_BIT_EXT: Incomplete

@_f
def glActiveProgramEXT(program) -> None: ...
@_f
def glActiveShaderProgramEXT(pipeline, program) -> None: ...
@_f
def glBindProgramPipelineEXT(pipeline) -> None: ...
@_f
def glCreateShaderProgramEXT(type, string) -> None: ...
@_f
def glCreateShaderProgramvEXT(type, count, strings) -> None: ...
@_f
def glDeleteProgramPipelinesEXT(n, pipelines) -> None: ...
@_f
def glGenProgramPipelinesEXT(n, pipelines) -> None: ...
@_f
def glGetProgramPipelineInfoLogEXT(pipeline, bufSize, length, infoLog) -> None: ...
@_f
def glGetProgramPipelineivEXT(pipeline, pname, params) -> None: ...
@_f
def glIsProgramPipelineEXT(pipeline) -> None: ...
@_f
def glProgramParameteriEXT(program, pname, value) -> None: ...
@_f
def glProgramUniform1fEXT(program, location, v0) -> None: ...
@_f
def glProgramUniform1fvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform1iEXT(program, location, v0) -> None: ...
@_f
def glProgramUniform1ivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform1uiEXT(program, location, v0) -> None: ...
@_f
def glProgramUniform1uivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform2fEXT(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2fvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform2iEXT(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2ivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform2uiEXT(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2uivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform3fEXT(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3fvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform3iEXT(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3ivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform3uiEXT(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3uivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform4fEXT(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4fvEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform4iEXT(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4ivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniform4uiEXT(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4uivEXT(program, location, count, value) -> None: ...
@_f
def glProgramUniformMatrix2fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x3fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x4fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x2fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x4fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x2fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x3fvEXT(program, location, count, transpose, value) -> None: ...
@_f
def glUseProgramStagesEXT(pipeline, stages, program) -> None: ...
@_f
def glUseShaderProgramEXT(type, program) -> None: ...
@_f
def glValidateProgramPipelineEXT(pipeline) -> None: ...
