from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_CLAMP_TO_BORDER_EXT: Incomplete
GL_TEXTURE_BORDER_COLOR_EXT: Incomplete

@_f
def glGetSamplerParameterIivEXT(sampler, pname, params) -> None: ...
@_f
def glGetSamplerParameterIuivEXT(sampler, pname, params) -> None: ...
@_f
def glGetTexParameterIivEXT(target, pname, params) -> None: ...
@_f
def glGetTexParameterIuivEXT(target, pname, params) -> None: ...
@_f
def glSamplerParameterIivEXT(sampler, pname, param) -> None: ...
@_f
def glSamplerParameterIuivEXT(sampler, pname, param) -> None: ...
@_f
def glTexParameterIivEXT(target, pname, params) -> None: ...
@_f
def glTexParameterIuivEXT(target, pname, params) -> None: ...
