from OpenGL.raw.WGL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

WGL_ACCESS_READ_ONLY_NV: Incomplete
WGL_ACCESS_READ_WRITE_NV: Incomplete
WGL_ACCESS_WRITE_DISCARD_NV: Incomplete

@_f
def wglDXCloseDeviceNV(hDevice) -> None: ...
@_f
def wglDXLockObjectsNV(hDevice, count, hObjects) -> None: ...
@_f
def wglDXObjectAccessNV(hObject, access) -> None: ...
@_f
def wglDXOpenDeviceNV(dxDevice) -> None: ...
@_f
def wglDXRegisterObjectNV(hDevice, dxObject, name, type, access) -> None: ...
@_f
def wglDXSetResourceShareHandleNV(dxObject, shareHandle) -> None: ...
@_f
def wglDXUnlockObjectsNV(hDevice, count, hObjects) -> None: ...
@_f
def wglDXUnregisterObjectNV(hDevice, hObject) -> None: ...
