from OpenGL.raw.WGL._types import *
from OpenGL import arrays as arrays

@_f
def wglBindSwapBarrierNV(group, barrier) -> None: ...
@_f
def wglJoinSwapGroupNV(hDC, group) -> None: ...
@_f
def wglQueryFrameCountNV(hDC, count) -> None: ...
@_f
def wglQueryMaxSwapGroupsNV(hDC, maxGroups, maxBarriers) -> None: ...
@_f
def wglQuerySwapGroupNV(hDC, group, barrier) -> None: ...
@_f
def wglResetFrameCountNV(hDC) -> None: ...
