from OpenGL.raw.EGL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

EGL_BAD_OUTPUT_LAYER_EXT: Incomplete
EGL_BAD_OUTPUT_PORT_EXT: Incomplete
EGL_SWAP_INTERVAL_EXT: Incomplete

@_f
def eglGetOutputLayersEXT(dpy, attrib_list, layers, max_layers, num_layers) -> None: ...
@_f
def eglGetOutputPortsEXT(dpy, attrib_list, ports, max_ports, num_ports) -> None: ...
@_f
def eglOutputLayerAttribEXT(dpy, layer, attribute, value) -> None: ...
@_f
def eglOutputPortAttribEXT(dpy, port, attribute, value) -> None: ...
@_f
def eglQueryOutputLayerAttribEXT(dpy, layer, attribute, value) -> None: ...
@_f
def eglQueryOutputLayerStringEXT(dpy, layer, name) -> None: ...
@_f
def eglQueryOutputPortAttribEXT(dpy, port, attribute, value) -> None: ...
@_f
def eglQueryOutputPortStringEXT(dpy, port, name) -> None: ...
