from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ASYNC_MARKER_SGIX: Incomplete

@_f
def glAsyncMarkerSGIX(marker) -> None: ...
@_f
def glDeleteAsyncMarkersSGIX(marker, range) -> None: ...
@_f
def glFinishAsyncSGIX(markerp) -> None: ...
@_f
def glGenAsyncMarkersSGIX(range) -> None: ...
@_f
def glIsAsyncMarkerSGIX(marker) -> None: ...
@_f
def glPollAsyncSGIX(markerp) -> None: ...
