from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_LIST_PRIORITY_SGIX: Incomplete

@_f
def glGetListParameterfvSGIX(list, pname, params) -> None: ...
@_f
def glGetListParameterivSGIX(list, pname, params) -> None: ...
@_f
def glListParameterfSGIX(list, pname, param) -> None: ...
@_f
def glListParameterfvSGIX(list, pname, params) -> None: ...
@_f
def glListParameteriSGIX(list, pname, param) -> None: ...
@_f
def glListParameterivSGIX(list, pname, params) -> None: ...
