from _typeshed import Incomplete

__all__ = ['glBegin', 'glCallLists', 'glColor', 'glDeleteTextures', 'glEnd', 'glMap1d', 'glMap1f', 'glMap2d', 'glMap2f', 'glMaterial', 'glRasterPos', 'glTexParameter', 'glVertex', 'glAreTexturesResident']

def glBegin(baseFunction, mode): ...
def glEnd(baseFunction): ...

glBegin: Incomplete
glEnd: Incomplete

def glDeleteTextures(baseFunction, size, array=...): ...

glMap2d: Incomplete
glMap2f: Incomplete
glMap1d: Incomplete
glMap1f: Incomplete

def glRasterPos(*args): ...
def glVertex(*args): ...
def glCallLists(baseFunction, lists, *args): ...
def glTexParameter(target, pname, parameter): ...
def glMaterial(faces, constant, *args): ...
def glColor(*args): ...
def glAreTexturesResident(baseFunction, *args): ...
