from OpenGL._bytes import integer_types as integer_types
from _typeshed import Incomplete

def uintToLong(value): ...

class GLSelectRecord:
    DISTANCE_DIVISOR: Incomplete
    def fromArray(cls, array, total): ...
    fromArray: Incomplete
    near: Incomplete
    far: Incomplete
    names: Incomplete
    def __init__(self, near, far, names) -> None: ...
    def convertDistance(self, value): ...
    def __getitem__(self, key): ...
