import types
from _typeshed import Incomplete

__all__ = ['glAttachShader', 'glDeleteShader', 'glGetProgramInfoLog', 'glGetShaderInfoLog', 'glGetProgramiv', 'glGetShaderiv', 'compileProgram', 'compileShader', 'GL_VALIDATE_STATUS', 'GL_LINK_STATUS', 'ShaderCompilationError', 'ShaderValidationError', 'ShaderLinkError', 'GLDEBUGPROC', 'GL_BOOL', 'GL_BOOL_VEC2', 'GL_BOOL_VEC3', 'GL_BOOL_VEC4', 'GL_FLOAT_MAT2', 'GL_FLOAT_MAT3', 'GL_FLOAT_MAT4', 'GL_FLOAT_VEC2', 'GL_FLOAT_VEC3', 'GL_FLOAT_VEC4', 'GL_INFO_LOG_LENGTH', 'GL_INT_VEC2', 'GL_INT_VEC3', 'GL_INT_VEC4', 'GL_OBJECT_ACTIVE_UNIFORMS', 'GL_OBJECT_ACTIVE_UNIFORM_MAX_LENGTH', 'GL_OBJECT_COMPILE_STATUS', 'GL_OBJECT_LINK_STATUS', 'GL_OBJECT_TYPE', 'GL_SAMPLER_1D', 'GL_SAMPLER_1D_SHADOW', 'GL_SAMPLER_2D', 'GL_SAMPLER_2D_RECT', 'GL_SAMPLER_2D_RECT_SHADOW', 'GL_SAMPLER_2D_SHADOW', 'GL_SAMPLER_3D', 'GL_SAMPLER_CUBE', 'GLchar', 'GLhandle', 'GLintptr', 'GLsizeiptr', 'glCompileShader', 'glCreateProgram', 'glCreateShader', 'glGetActiveUniform', 'glGetShaderSource', 'glGetUniformLocation', 'glGetUniformfv', 'glGetUniformiv', 'glLinkProgram', 'glShaderSource', 'glUniform1f', 'glUniform1fv', 'glUniform1i', 'glUniform1iv', 'glUniform2f', 'glUniform2fv', 'glUniform2i', 'glUniform2iv', 'glUniform3f', 'glUniform3fv', 'glUniform3i', 'glUniform3iv', 'glUniform4f', 'glUniform4fv', 'glUniform4i', 'glUniform4iv', 'glUniformMatrix2fv', 'glUniformMatrix3fv', 'glUniformMatrix4fv', 'glUseProgram', 'glValidateProgram', 'GLDEBUGPROC', 'GL_FRAGMENT_SHADER', 'GL_FRAGMENT_SHADER_DERIVATIVE_HINT', 'GL_MAX_FRAGMENT_UNIFORM_COMPONENTS', 'GLchar', 'GLhandle', 'GLintptr', 'GLsizeiptr', 'GLDEBUGPROC', 'GL_CURRENT_VERTEX_ATTRIB', 'GL_FLOAT_MAT2', 'GL_FLOAT_MAT3', 'GL_FLOAT_MAT4', 'GL_FLOAT_VEC2', 'GL_FLOAT_VEC3', 'GL_FLOAT_VEC4', 'GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS', 'GL_MAX_TEXTURE_COORDS', 'GL_MAX_TEXTURE_IMAGE_UNITS', 'GL_MAX_VARYING_FLOATS', 'GL_MAX_VERTEX_ATTRIBS', 'GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS', 'GL_MAX_VERTEX_UNIFORM_COMPONENTS', 'GL_VERTEX_ATTRIB_ARRAY_ENABLED', 'GL_VERTEX_ATTRIB_ARRAY_NORMALIZED', 'GL_VERTEX_ATTRIB_ARRAY_POINTER', 'GL_VERTEX_ATTRIB_ARRAY_SIZE', 'GL_VERTEX_ATTRIB_ARRAY_STRIDE', 'GL_VERTEX_ATTRIB_ARRAY_TYPE', 'GL_VERTEX_PROGRAM_POINT_SIZE', 'GL_VERTEX_PROGRAM_TWO_SIDE', 'GL_VERTEX_SHADER', 'GLchar', 'GLhandle', 'GLintptr', 'GLsizeiptr', 'glBindAttribLocation', 'glDisableVertexAttribArray', 'glEnableVertexAttribArray', 'glGetActiveAttrib', 'glGetAttribLocation', 'glGetVertexAttribPointerv', 'glGetVertexAttribdv', 'glGetVertexAttribfv', 'glGetVertexAttribiv', 'glVertexAttrib1d', 'glVertexAttrib1dv', 'glVertexAttrib1f', 'glVertexAttrib1fv', 'glVertexAttrib1s', 'glVertexAttrib1sv', 'glVertexAttrib2d', 'glVertexAttrib2dv', 'glVertexAttrib2f', 'glVertexAttrib2fv', 'glVertexAttrib2s', 'glVertexAttrib2sv', 'glVertexAttrib3d', 'glVertexAttrib3dv', 'glVertexAttrib3f', 'glVertexAttrib3fv', 'glVertexAttrib3s', 'glVertexAttrib3sv', 'glVertexAttrib4Nbv', 'glVertexAttrib4Niv', 'glVertexAttrib4Nsv', 'glVertexAttrib4Nub', 'glVertexAttrib4Nubv', 'glVertexAttrib4Nuiv', 'glVertexAttrib4Nusv', 'glVertexAttrib4bv', 'glVertexAttrib4d', 'glVertexAttrib4dv', 'glVertexAttrib4f', 'glVertexAttrib4fv', 'glVertexAttrib4iv', 'glVertexAttrib4s', 'glVertexAttrib4sv', 'glVertexAttrib4ubv', 'glVertexAttrib4uiv', 'glVertexAttrib4usv', 'glVertexAttribPointer', 'GLDEBUGPROC', 'GL_COLOR_SUM', 'GL_CURRENT_VERTEX_ATTRIB', 'GL_MAX_VERTEX_ATTRIBS', 'GL_VERTEX_ATTRIB_ARRAY_ENABLED', 'GL_VERTEX_ATTRIB_ARRAY_NORMALIZED', 'GL_VERTEX_ATTRIB_ARRAY_POINTER', 'GL_VERTEX_ATTRIB_ARRAY_SIZE', 'GL_VERTEX_ATTRIB_ARRAY_STRIDE', 'GL_VERTEX_ATTRIB_ARRAY_TYPE', 'GL_VERTEX_PROGRAM_POINT_SIZE', 'GL_VERTEX_PROGRAM_TWO_SIDE', 'GLchar', 'GLhandle', 'GLintptr', 'GLsizeiptr', 'glDisableVertexAttribArray', 'glEnableVertexAttribArray', 'glGetVertexAttribPointerv', 'glGetVertexAttribdv', 'glGetVertexAttribfv', 'glGetVertexAttribiv', 'glIsProgram', 'glVertexAttrib1d', 'glVertexAttrib1dv', 'glVertexAttrib1f', 'glVertexAttrib1fv', 'glVertexAttrib1s', 'glVertexAttrib1sv', 'glVertexAttrib2d', 'glVertexAttrib2dv', 'glVertexAttrib2f', 'glVertexAttrib2fv', 'glVertexAttrib2s', 'glVertexAttrib2sv', 'glVertexAttrib3d', 'glVertexAttrib3dv', 'glVertexAttrib3f', 'glVertexAttrib3fv', 'glVertexAttrib3s', 'glVertexAttrib3sv', 'glVertexAttrib4Nbv', 'glVertexAttrib4Niv', 'glVertexAttrib4Nsv', 'glVertexAttrib4Nub', 'glVertexAttrib4Nubv', 'glVertexAttrib4Nuiv', 'glVertexAttrib4Nusv', 'glVertexAttrib4bv', 'glVertexAttrib4d', 'glVertexAttrib4dv', 'glVertexAttrib4f', 'glVertexAttrib4fv', 'glVertexAttrib4iv', 'glVertexAttrib4s', 'glVertexAttrib4sv', 'glVertexAttrib4ubv', 'glVertexAttrib4uiv', 'glVertexAttrib4usv', 'glVertexAttribPointer', 'GLDEBUGPROC', 'GL_FRAMEBUFFER_ATTACHMENT_LAYERED', 'GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS', 'GL_GEOMETRY_INPUT_TYPE', 'GL_GEOMETRY_OUTPUT_TYPE', 'GL_GEOMETRY_SHADER', 'GL_GEOMETRY_VERTICES_OUT', 'GL_LINES_ADJACENCY', 'GL_LINE_STRIP_ADJACENCY', 'GL_MAX_GEOMETRY_OUTPUT_VERTICES', 'GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS', 'GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS', 'GL_MAX_GEOMETRY_UNIFORM_COMPONENTS', 'GL_PROGRAM_POINT_SIZE', 'GL_TRIANGLES_ADJACENCY', 'GL_TRIANGLE_STRIP_ADJACENCY', 'GLchar', 'GLhandle', 'GLintptr', 'GLsizeiptr', 'glFramebufferTexture', 'glFramebufferTextureLayer', 'glProgramParameteri']

glAttachShader: Incomplete
glDeleteShader: Incomplete
glGetProgramInfoLog: Incomplete
glGetShaderInfoLog: Incomplete
glGetShaderiv: Incomplete
glGetProgramiv: Incomplete
GL_VALIDATE_STATUS: Incomplete
GL_LINK_STATUS: Incomplete

class ShaderProgram(int):
    validated: bool
    def __enter__(self) -> None: ...
    def __exit__(self, typ: type[BaseException] | None, val: BaseException | None, tb: types.TracebackType | None) -> None: ...
    def check_validate(self): ...
    def check_linked(self): ...
    def retrieve(self): ...
    def load(self, format, binary, validate: bool = True): ...

def compileProgram(*shaders, **named): ...
def compileShader(source, shaderType): ...

class ShaderCompilationError(RuntimeError): ...
class ShaderValidationError(RuntimeError): ...
class ShaderLinkError(RuntimeError): ...

# Names in __all__ with no definition:
#   GLDEBUGPROC
#   GLDEBUGPROC
#   GLDEBUGPROC
#   GLDEBUGPROC
#   GLDEBUGPROC
#   GL_BOOL
#   GL_BOOL_VEC2
#   GL_BOOL_VEC3
#   GL_BOOL_VEC4
#   GL_COLOR_SUM
#   GL_CURRENT_VERTEX_ATTRIB
#   GL_CURRENT_VERTEX_ATTRIB
#   GL_FLOAT_MAT2
#   GL_FLOAT_MAT2
#   GL_FLOAT_MAT3
#   GL_FLOAT_MAT3
#   GL_FLOAT_MAT4
#   GL_FLOAT_MAT4
#   GL_FLOAT_VEC2
#   GL_FLOAT_VEC2
#   GL_FLOAT_VEC3
#   GL_FLOAT_VEC3
#   GL_FLOAT_VEC4
#   GL_FLOAT_VEC4
#   GL_FRAGMENT_SHADER
#   GL_FRAGMENT_SHADER_DERIVATIVE_HINT
#   GL_FRAMEBUFFER_ATTACHMENT_LAYERED
#   GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS
#   GL_GEOMETRY_INPUT_TYPE
#   GL_GEOMETRY_OUTPUT_TYPE
#   GL_GEOMETRY_SHADER
#   GL_GEOMETRY_VERTICES_OUT
#   GL_INFO_LOG_LENGTH
#   GL_INT_VEC2
#   GL_INT_VEC3
#   GL_INT_VEC4
#   GL_LINES_ADJACENCY
#   GL_LINE_STRIP_ADJACENCY
#   GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
#   GL_MAX_FRAGMENT_UNIFORM_COMPONENTS
#   GL_MAX_GEOMETRY_OUTPUT_VERTICES
#   GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS
#   GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS
#   GL_MAX_GEOMETRY_UNIFORM_COMPONENTS
#   GL_MAX_TEXTURE_COORDS
#   GL_MAX_TEXTURE_IMAGE_UNITS
#   GL_MAX_VARYING_FLOATS
#   GL_MAX_VERTEX_ATTRIBS
#   GL_MAX_VERTEX_ATTRIBS
#   GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
#   GL_MAX_VERTEX_UNIFORM_COMPONENTS
#   GL_OBJECT_ACTIVE_UNIFORMS
#   GL_OBJECT_ACTIVE_UNIFORM_MAX_LENGTH
#   GL_OBJECT_COMPILE_STATUS
#   GL_OBJECT_LINK_STATUS
#   GL_OBJECT_TYPE
#   GL_PROGRAM_POINT_SIZE
#   GL_SAMPLER_1D
#   GL_SAMPLER_1D_SHADOW
#   GL_SAMPLER_2D
#   GL_SAMPLER_2D_RECT
#   GL_SAMPLER_2D_RECT_SHADOW
#   GL_SAMPLER_2D_SHADOW
#   GL_SAMPLER_3D
#   GL_SAMPLER_CUBE
#   GL_TRIANGLES_ADJACENCY
#   GL_TRIANGLE_STRIP_ADJACENCY
#   GL_VERTEX_ATTRIB_ARRAY_ENABLED
#   GL_VERTEX_ATTRIB_ARRAY_ENABLED
#   GL_VERTEX_ATTRIB_ARRAY_NORMALIZED
#   GL_VERTEX_ATTRIB_ARRAY_NORMALIZED
#   GL_VERTEX_ATTRIB_ARRAY_POINTER
#   GL_VERTEX_ATTRIB_ARRAY_POINTER
#   GL_VERTEX_ATTRIB_ARRAY_SIZE
#   GL_VERTEX_ATTRIB_ARRAY_SIZE
#   GL_VERTEX_ATTRIB_ARRAY_STRIDE
#   GL_VERTEX_ATTRIB_ARRAY_STRIDE
#   GL_VERTEX_ATTRIB_ARRAY_TYPE
#   GL_VERTEX_ATTRIB_ARRAY_TYPE
#   GL_VERTEX_PROGRAM_POINT_SIZE
#   GL_VERTEX_PROGRAM_POINT_SIZE
#   GL_VERTEX_PROGRAM_TWO_SIDE
#   GL_VERTEX_PROGRAM_TWO_SIDE
#   GL_VERTEX_SHADER
#   GLchar
#   GLchar
#   GLchar
#   GLchar
#   GLchar
#   GLhandle
#   GLhandle
#   GLhandle
#   GLhandle
#   GLhandle
#   GLintptr
#   GLintptr
#   GLintptr
#   GLintptr
#   GLintptr
#   GLsizeiptr
#   GLsizeiptr
#   GLsizeiptr
#   GLsizeiptr
#   GLsizeiptr
#   glBindAttribLocation
#   glCompileShader
#   glCreateProgram
#   glCreateShader
#   glDisableVertexAttribArray
#   glDisableVertexAttribArray
#   glEnableVertexAttribArray
#   glEnableVertexAttribArray
#   glFramebufferTexture
#   glFramebufferTextureLayer
#   glGetActiveAttrib
#   glGetActiveUniform
#   glGetAttribLocation
#   glGetShaderSource
#   glGetUniformLocation
#   glGetUniformfv
#   glGetUniformiv
#   glGetVertexAttribPointerv
#   glGetVertexAttribPointerv
#   glGetVertexAttribdv
#   glGetVertexAttribdv
#   glGetVertexAttribfv
#   glGetVertexAttribfv
#   glGetVertexAttribiv
#   glGetVertexAttribiv
#   glIsProgram
#   glLinkProgram
#   glProgramParameteri
#   glShaderSource
#   glUniform1f
#   glUniform1fv
#   glUniform1i
#   glUniform1iv
#   glUniform2f
#   glUniform2fv
#   glUniform2i
#   glUniform2iv
#   glUniform3f
#   glUniform3fv
#   glUniform3i
#   glUniform3iv
#   glUniform4f
#   glUniform4fv
#   glUniform4i
#   glUniform4iv
#   glUniformMatrix2fv
#   glUniformMatrix3fv
#   glUniformMatrix4fv
#   glUseProgram
#   glValidateProgram
#   glVertexAttrib1d
#   glVertexAttrib1d
#   glVertexAttrib1dv
#   glVertexAttrib1dv
#   glVertexAttrib1f
#   glVertexAttrib1f
#   glVertexAttrib1fv
#   glVertexAttrib1fv
#   glVertexAttrib1s
#   glVertexAttrib1s
#   glVertexAttrib1sv
#   glVertexAttrib1sv
#   glVertexAttrib2d
#   glVertexAttrib2d
#   glVertexAttrib2dv
#   glVertexAttrib2dv
#   glVertexAttrib2f
#   glVertexAttrib2f
#   glVertexAttrib2fv
#   glVertexAttrib2fv
#   glVertexAttrib2s
#   glVertexAttrib2s
#   glVertexAttrib2sv
#   glVertexAttrib2sv
#   glVertexAttrib3d
#   glVertexAttrib3d
#   glVertexAttrib3dv
#   glVertexAttrib3dv
#   glVertexAttrib3f
#   glVertexAttrib3f
#   glVertexAttrib3fv
#   glVertexAttrib3fv
#   glVertexAttrib3s
#   glVertexAttrib3s
#   glVertexAttrib3sv
#   glVertexAttrib3sv
#   glVertexAttrib4Nbv
#   glVertexAttrib4Nbv
#   glVertexAttrib4Niv
#   glVertexAttrib4Niv
#   glVertexAttrib4Nsv
#   glVertexAttrib4Nsv
#   glVertexAttrib4Nub
#   glVertexAttrib4Nub
#   glVertexAttrib4Nubv
#   glVertexAttrib4Nubv
#   glVertexAttrib4Nuiv
#   glVertexAttrib4Nuiv
#   glVertexAttrib4Nusv
#   glVertexAttrib4Nusv
#   glVertexAttrib4bv
#   glVertexAttrib4bv
#   glVertexAttrib4d
#   glVertexAttrib4d
#   glVertexAttrib4dv
#   glVertexAttrib4dv
#   glVertexAttrib4f
#   glVertexAttrib4f
#   glVertexAttrib4fv
#   glVertexAttrib4fv
#   glVertexAttrib4iv
#   glVertexAttrib4iv
#   glVertexAttrib4s
#   glVertexAttrib4s
#   glVertexAttrib4sv
#   glVertexAttrib4sv
#   glVertexAttrib4ubv
#   glVertexAttrib4ubv
#   glVertexAttrib4uiv
#   glVertexAttrib4uiv
#   glVertexAttrib4usv
#   glVertexAttrib4usv
#   glVertexAttribPointer
#   glVertexAttribPointer
