import tkinter as tk
from _typeshed import Incomplete

class BaseOpenGLFrame(tk.Frame):
    animate: int
    cb: Incomplete
    context_created: bool
    def __init__(self, *args, **kw) -> None: ...
    def tkMap(self, evt) -> None: ...
    def printContext(self, extns: bool = False) -> None: ...
    def tkCreateContext(self) -> None: ...
    def tkMakeCurrent(self) -> None: ...
    def tkSwapBuffers(self) -> None: ...
    def tkExpose(self, evt) -> None: ...
    def tkResize(self, evt) -> None: ...
    def initgl(self) -> None: ...
    def redraw(self) -> None: ...
