from _typeshed import Incomplete
from pyopengltk import OpenGLFrame as OpenGLFrame

def glTranslateScene(s, x, y, mousex, mousey) -> None: ...
def glRotateScene(s, xcenter, ycenter, zcenter, x, y, mousex, mousey) -> None: ...
def v3distsq(a, b): ...

class RawOpengl(OpenGLFrame):
    def __init__(self, master=None, cnf={}, **kw) -> None: ...
    def tkRedraw(self, *dummy) -> None: ...

class Opengl(RawOpengl):
    initialised: int
    xmouse: int
    ymouse: int
    xcenter: float
    ycenter: float
    zcenter: float
    r_back: float
    g_back: float
    b_back: float
    distance: float
    fovy: float
    near: float
    far: float
    autospin_allowed: int
    autospin: int
    def __init__(self, master=None, cnf={}, **kw) -> None: ...
    def help(self) -> None: ...
    def activate(self) -> None: ...
    def basic_lighting(self) -> None: ...
    def initgl(self) -> None: ...
    def set_background(self, r, g, b) -> None: ...
    def set_centerpoint(self, x, y, z) -> None: ...
    def set_eyepoint(self, distance) -> None: ...
    def reset(self) -> None: ...
    def tkHandlePick(self, event) -> None: ...
    def tkRecordMouse(self, event) -> None: ...
    def StartRotate(self, event) -> None: ...
    def tkScale(self, event) -> None: ...
    def do_AutoSpin(self) -> None: ...
    yspin: Incomplete
    xspin: Incomplete
    def tkAutoSpin(self, event) -> None: ...
    def tkRotate(self, event) -> None: ...
    def tkTranslate(self, event) -> None: ...
    def tkRedraw(self, *dummy) -> None: ...
    def redraw(self, *args, **named) -> None: ...
    def tkExpose(self, *dummy) -> None: ...
    def tkPrint(self, file) -> None: ...
