from OpenGL.GLU import glustruct
from OpenGL.raw import GLU as _simple
from _typeshed import Incomplete

__all__ = ['GLUnurbs', 'gluNewNurbsRenderer', 'gluNurbsCallback', 'gluNurbsCallbackData', 'gluNurbsCallbackDataEXT', 'gluNurbsCurve', 'gluNurbsSurface', 'gluPwlCurve']

class GLUnurbs(glustruct.GLUStruct, _simple.GLUnurbs):
    FUNCTION_TYPE: Incomplete
    CALLBACK_FUNCTION_REGISTRARS: Incomplete
    CALLBACK_TYPES: Incomplete
    WRAPPER_METHODS: Incomplete

def gluNurbsCallback(nurb, which, CallBackFunc): ...
def gluNewNurbsRenderer(baseFunction): ...
def gluNurbsCallbackData(baseFunction, nurb, userData): ...
def gluNurbsCallbackDataEXT(baseFunction, nurb, userData): ...
def gluNurbsCurve(baseFunction, nurb, knots, control, type): ...
def gluNurbsSurface(baseFunction, nurb, sKnots, tKnots, control, type): ...
def gluPwlCurve(baseFunction, nurb, data, type): ...
