from OpenGL._bytes import integer_types as integer_types, long as long
from _typeshed import Incomplete

class GLUStruct:
    def getAsParam(self): ...
    CALLBACK_TYPES: Incomplete
    CALLBACK_FUNCTION_REGISTRARS: Incomplete
    WRAPPER_METHODS: Incomplete
    dataPointers: Incomplete
    def noteObject(self, object): ...
    def originalObject(self, voidPointer): ...
    callbacks: Incomplete
    def addCallback(self, which, function): ...
    def ptrAsArray(self, ptr, length, type): ...
