__all__ = ['gluProject', 'gluUnProject', 'gluUnProject4']

def gluProject(baseFunction, objX, objY, objZ, model=None, proj=None, view=None): ...
def gluUnProject(baseFunction, winX, winY, winZ, model=None, proj=None, view=None): ...
def gluUnProject4(baseFunction, winX, winY, winZ, clipW, model=None, proj=None, view=None, near: float = 0.0, far: float = 1.0): ...
