from OpenGL.GLU import glustruct
from OpenGL.raw import GLU as _simple
from _typeshed import Incomplete

__all__ = ['gluNewTess', 'gluGetTessProperty', 'gluTessBeginPolygon', 'gluTessCallback', 'gluTessVertex']

class GLUtesselator(glustruct.GLUStruct, _simple.GLUtesselator):
    FUNCTION_TYPE: Incomplete
    CALLBACK_TYPES: Incomplete
    WRAPPER_METHODS: Incomplete
    vertexCache: Incomplete
    def gluTessVertex(self, location, data=None): ...
    def gluTessBeginPolygon(self, data): ...
    def combineWrapper(self, function): ...
    def dataWrapper(self, function): ...
    def dataWrapper2(self, function): ...
    def vertexWrapper(self, function): ...

def gluTessCallback(tess, which, function): ...
def gluTessBeginPolygon(tess, data): ...
def gluTessVertex(tess, location, data=None): ...
def gluNewTess(baseFunction): ...
def gluGetTessProperty(baseFunction, tess, which, data=None): ...
