from OpenGL.raw.GL.ARB.separate_shader_objects import *
from OpenGL import arrays as arrays, constant as constant, extensions as extensions, platform as platform, wrapper as wrapper
from _typeshed import Incomplete

def glInitSeparateShaderObjectsARB(): ...

glCreateShaderProgramv: Incomplete
glDeleteProgramPipelines: Incomplete
glGenProgramPipelines: Incomplete
glGetProgramPipelineiv: Incomplete
glProgramUniform1iv: Incomplete
glProgramUniform1fv: Incomplete
glProgramUniform1dv: Incomplete
glProgramUniform1uiv: Incomplete
glProgramUniform2iv: Incomplete
glProgramUniform2fv: Incomplete
glProgramUniform2dv: Incomplete
glProgramUniform2uiv: Incomplete
glProgramUniform3iv: Incomplete
glProgramUniform3fv: Incomplete
glProgramUniform3dv: Incomplete
glProgramUniform3uiv: Incomplete
glProgramUniform4iv: Incomplete
glProgramUniform4fv: Incomplete
glProgramUniform4dv: Incomplete
glProgramUniform4uiv: Incomplete
glProgramUniformMatrix2fv: Incomplete
glProgramUniformMatrix3fv: Incomplete
glProgramUniformMatrix4fv: Incomplete
glProgramUniformMatrix2dv: Incomplete
glProgramUniformMatrix3dv: Incomplete
glProgramUniformMatrix4dv: Incomplete
glProgramUniformMatrix2x3fv: Incomplete
glProgramUniformMatrix3x2fv: Incomplete
glProgramUniformMatrix2x4fv: Incomplete
glProgramUniformMatrix4x2fv: Incomplete
glProgramUniformMatrix3x4fv: Incomplete
glProgramUniformMatrix4x3fv: Incomplete
glProgramUniformMatrix2x3dv: Incomplete
glProgramUniformMatrix3x2dv: Incomplete
glProgramUniformMatrix2x4dv: Incomplete
glProgramUniformMatrix4x2dv: Incomplete
glProgramUniformMatrix3x4dv: Incomplete
glProgramUniformMatrix4x3dv: Incomplete
glGetProgramPipelineInfoLog: Incomplete
