from OpenGL.raw.GLX._types import *
from OpenGL import arrays as arrays

@_f
def glXGetMscRateOML(dpy, drawable, numerator, denominator) -> None: ...
@_f
def glXGetSyncValuesOML(dpy, drawable, ust, msc, sbc) -> None: ...
@_f
def glXSwapBuffersMscOML(dpy, drawable, target_msc, divisor, remainder) -> None: ...
@_f
def glXWaitForMscOML(dpy, drawable, target_msc, divisor, remainder, ust, msc, sbc) -> None: ...
@_f
def glXWaitForSbcOML(dpy, drawable, target_sbc, ust, msc, sbc) -> None: ...
