from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_GLOBAL_ALPHA_FACTOR_SUN: Incomplete
GL_GLOBAL_ALPHA_SUN: Incomplete

@_f
def glGlobalAlphaFactorbSUN(factor) -> None: ...
@_f
def glGlobalAlphaFactordSUN(factor) -> None: ...
@_f
def glGlobalAlphaFactorfSUN(factor) -> None: ...
@_f
def glGlobalAlphaFactoriSUN(factor) -> None: ...
@_f
def glGlobalAlphaFactorsSUN(factor) -> None: ...
@_f
def glGlobalAlphaFactorubSUN(factor) -> None: ...
@_f
def glGlobalAlphaFactoruiSUN(factor) -> None: ...
@_f
def glGlobalAlphaFactorusSUN(factor) -> None: ...
