from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glColor3fVertex3fSUN(r, g, b, x, y, z) -> None: ...
@_f
def glColor3fVertex3fvSUN(c, v) -> None: ...
@_f
def glColor4fNormal3fVertex3fSUN(r, g, b, a, nx, ny, nz, x, y, z) -> None: ...
@_f
def glColor4fNormal3fVertex3fvSUN(c, n, v) -> None: ...
@_f
def glColor4ubVertex2fSUN(r, g, b, a, x, y) -> None: ...
@_f
def glColor4ubVertex2fvSUN(c, v) -> None: ...
@_f
def glColor4ubVertex3fSUN(r, g, b, a, x, y, z) -> None: ...
@_f
def glColor4ubVertex3fvSUN(c, v) -> None: ...
@_f
def glNormal3fVertex3fSUN(nx, ny, nz, x, y, z) -> None: ...
@_f
def glNormal3fVertex3fvSUN(n, v) -> None: ...
@_f
def glReplacementCodeuiColor3fVertex3fSUN(rc, r, g, b, x, y, z) -> None: ...
@_f
def glReplacementCodeuiColor3fVertex3fvSUN(rc, c, v) -> None: ...
@_f
def glReplacementCodeuiColor4fNormal3fVertex3fSUN(rc, r, g, b, a, nx, ny, nz, x, y, z) -> None: ...
@_f
def glReplacementCodeuiColor4fNormal3fVertex3fvSUN(rc, c, n, v) -> None: ...
@_f
def glReplacementCodeuiColor4ubVertex3fSUN(rc, r, g, b, a, x, y, z) -> None: ...
@_f
def glReplacementCodeuiColor4ubVertex3fvSUN(rc, c, v) -> None: ...
@_f
def glReplacementCodeuiNormal3fVertex3fSUN(rc, nx, ny, nz, x, y, z) -> None: ...
@_f
def glReplacementCodeuiNormal3fVertex3fvSUN(rc, n, v) -> None: ...
@_f
def glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN(rc, s, t, r, g, b, a, nx, ny, nz, x, y, z) -> None: ...
@_f
def glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN(rc, tc, c, n, v) -> None: ...
@_f
def glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN(rc, s, t, nx, ny, nz, x, y, z) -> None: ...
@_f
def glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN(rc, tc, n, v) -> None: ...
@_f
def glReplacementCodeuiTexCoord2fVertex3fSUN(rc, s, t, x, y, z) -> None: ...
@_f
def glReplacementCodeuiTexCoord2fVertex3fvSUN(rc, tc, v) -> None: ...
@_f
def glReplacementCodeuiVertex3fSUN(rc, x, y, z) -> None: ...
@_f
def glReplacementCodeuiVertex3fvSUN(rc, v) -> None: ...
@_f
def glTexCoord2fColor3fVertex3fSUN(s, t, r, g, b, x, y, z) -> None: ...
@_f
def glTexCoord2fColor3fVertex3fvSUN(tc, c, v) -> None: ...
@_f
def glTexCoord2fColor4fNormal3fVertex3fSUN(s, t, r, g, b, a, nx, ny, nz, x, y, z) -> None: ...
@_f
def glTexCoord2fColor4fNormal3fVertex3fvSUN(tc, c, n, v) -> None: ...
@_f
def glTexCoord2fColor4ubVertex3fSUN(s, t, r, g, b, a, x, y, z) -> None: ...
@_f
def glTexCoord2fColor4ubVertex3fvSUN(tc, c, v) -> None: ...
@_f
def glTexCoord2fNormal3fVertex3fSUN(s, t, nx, ny, nz, x, y, z) -> None: ...
@_f
def glTexCoord2fNormal3fVertex3fvSUN(tc, n, v) -> None: ...
@_f
def glTexCoord2fVertex3fSUN(s, t, x, y, z) -> None: ...
@_f
def glTexCoord2fVertex3fvSUN(tc, v) -> None: ...
@_f
def glTexCoord4fColor4fNormal3fVertex4fSUN(s, t, p, q, r, g, b, a, nx, ny, nz, x, y, z, w) -> None: ...
@_f
def glTexCoord4fColor4fNormal3fVertex4fvSUN(tc, c, n, v) -> None: ...
@_f
def glTexCoord4fVertex4fSUN(s, t, p, q, x, y, z, w) -> None: ...
@_f
def glTexCoord4fVertex4fvSUN(tc, v) -> None: ...
