from OpenGL.raw.GLX._types import *
from OpenGL import arrays as arrays

@_f
def glXBindSwapBarrierNV(dpy, group, barrier) -> None: ...
@_f
def glXJoinSwapGroupNV(dpy, drawable, group) -> None: ...
@_f
def glXQueryFrameCountNV(dpy, screen, count) -> None: ...
@_f
def glXQueryMaxSwapGroupsNV(dpy, screen, maxGroups, maxBarriers) -> None: ...
@_f
def glXQuerySwapGroupNV(dpy, drawable, group, barrier) -> None: ...
@_f
def glXResetFrameCountNV(dpy, screen) -> None: ...
