from OpenGL.raw.WGL._types import *
from OpenGL import arrays as arrays

@_f
def wglGetMscRateOML(hdc, numerator, denominator) -> None: ...
@_f
def wglGetSyncValuesOML(hdc, ust, msc, sbc) -> None: ...
@_f
def wglSwapBuffersMscOML(hdc, target_msc, divisor, remainder) -> None: ...
@_f
def wglSwapLayerBuffersMscOML(hdc, fuPlanes, target_msc, divisor, remainder) -> None: ...
@_f
def wglWaitForMscOML(hdc, target_msc, divisor, remainder, ust, msc, sbc) -> None: ...
@_f
def wglWaitForSbcOML(hdc, target_sbc, ust, msc, sbc) -> None: ...
