from OpenGL.GL import *
from OpenGL.GLU import *
from tkinter import *
from Tkinter import *
from _typeshed import Incomplete

def glTranslateScene(s, x, y, mousex, mousey) -> None: ...
def glRotateScene(s, xcenter, ycenter, zcenter, x, y, mousex, mousey) -> None: ...
def sub(x, y): ...
def dot(x, y): ...
def glDistFromLine(x, p1, p2): ...

TOGL_NORMAL: int
TOGL_OVERLAY: int

def v3distsq(a, b): ...

suffix: str
TOGL_DLL_PATH: Incomplete

def cleanup() -> None: ...

class Togl(Widget):
    def __init__(self, master=None, cnf={}, **kw) -> None: ...
    def render(self) -> None: ...
    def swapbuffers(self) -> None: ...
    def makecurrent(self) -> None: ...
    def alloccolor(self, red, green, blue): ...
    def freecolor(self, index) -> None: ...
    def setcolor(self, index, red, green, blue) -> None: ...
    def loadbitmapfont(self, fontname): ...
    def unloadbitmapfont(self, fontbase) -> None: ...
    def uselayer(self, layer) -> None: ...
    def showoverlay(self) -> None: ...
    def hideoverlay(self) -> None: ...
    def existsoverlay(self): ...
    def getoverlaytransparentvalue(self): ...
    def ismappedoverlay(self): ...
    def alloccoloroverlay(self, red, green, blue): ...
    def freecoloroverlay(self, index) -> None: ...

class RawOpengl(Widget, Misc):
    def __init__(self, master=None, cnf={}, **kw) -> None: ...
    def tkRedraw(self, *dummy) -> None: ...
    def tkMap(self, *dummy) -> None: ...
    def tkExpose(self, *dummy) -> None: ...

class Opengl(RawOpengl):
    initialised: int
    xmouse: int
    ymouse: int
    xcenter: float
    ycenter: float
    zcenter: float
    r_back: float
    g_back: float
    b_back: float
    distance: float
    fovy: float
    near: float
    far: float
    autospin_allowed: int
    autospin: int
    def __init__(self, master=None, cnf={}, **kw) -> None: ...
    def help(self) -> None: ...
    def activate(self) -> None: ...
    def basic_lighting(self) -> None: ...
    def set_background(self, r, g, b) -> None: ...
    def set_centerpoint(self, x, y, z) -> None: ...
    def set_eyepoint(self, distance) -> None: ...
    def reset(self) -> None: ...
    def tkHandlePick(self, event) -> None: ...
    def tkRecordMouse(self, event) -> None: ...
    def StartRotate(self, event) -> None: ...
    def tkScale(self, event) -> None: ...
    def do_AutoSpin(self) -> None: ...
    yspin: Incomplete
    xspin: Incomplete
    def tkAutoSpin(self, event) -> None: ...
    def tkRotate(self, event) -> None: ...
    def tkTranslate(self, event) -> None: ...
    def tkRedraw(self, *dummy) -> None: ...
    def redraw(self, *args, **named) -> None: ...
    def tkMap(self, *dummy) -> None: ...
    def tkExpose(self, *dummy) -> None: ...
    def tkPrint(self, file) -> None: ...
