from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glGetImageHandleNV(texture, level, layered, layer, format) -> None: ...
@_f
def glGetTextureHandleNV(texture) -> None: ...
@_f
def glGetTextureSamplerHandleNV(texture, sampler) -> None: ...
@_f
def glIsImageHandleResidentNV(handle) -> None: ...
@_f
def glIsTextureHandleResidentNV(handle) -> None: ...
@_f
def glMakeImageHandleNonResidentNV(handle) -> None: ...
@_f
def glMakeImageHandleResidentNV(handle, access) -> None: ...
@_f
def glMakeTextureHandleNonResidentNV(handle) -> None: ...
@_f
def glMakeTextureHandleResidentNV(handle) -> None: ...
@_f
def glProgramUniformHandleui64NV(program, location, value) -> None: ...
@_f
def glProgramUniformHandleui64vNV(program, location, count, values) -> None: ...
@_f
def glUniformHandleui64NV(location, value) -> None: ...
@_f
def glUniformHandleui64vNV(location, count, value) -> None: ...
