from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_MULTICAST_GPUS_NV: Incomplete
GL_MULTICAST_PROGRAMMABLE_SAMPLE_LOCATION_NV: Incomplete
GL_PER_GPU_STORAGE_BIT_NV: Incomplete
GL_PER_GPU_STORAGE_NV: Incomplete
GL_RENDER_GPU_MASK_NV: Incomplete

@_f
def glMulticastBarrierNV() -> None: ...
@_f
def glMulticastBlitFramebufferNV(srcGpu, dstGpu, srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter) -> None: ...
@_f
def glMulticastBufferSubDataNV(gpuMask, buffer, offset, size, data) -> None: ...
@_f
def glMulticastCopyBufferSubDataNV(readGpu, writeGpuMask, readBuffer, writeBuffer, readOffset, writeOffset, size) -> None: ...
@_f
def glMulticastCopyImageSubDataNV(srcGpu, dstGpuMask, srcName, srcTarget, srcLevel, srcX, srcY, srcZ, dstName, dstTarget, dstLevel, dstX, dstY, dstZ, srcWidth, srcHeight, srcDepth) -> None: ...
@_f
def glMulticastFramebufferSampleLocationsfvNV(gpu, framebuffer, start, count, v) -> None: ...
@_f
def glMulticastGetQueryObjecti64vNV(gpu, id, pname, params) -> None: ...
@_f
def glMulticastGetQueryObjectivNV(gpu, id, pname, params) -> None: ...
@_f
def glMulticastGetQueryObjectui64vNV(gpu, id, pname, params) -> None: ...
@_f
def glMulticastGetQueryObjectuivNV(gpu, id, pname, params) -> None: ...
@_f
def glMulticastWaitSyncNV(signalGpu, waitGpuMask) -> None: ...
@_f
def glRenderGpuMaskNV(mask) -> None: ...
