from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_MAX_PROGRAM_ATTRIB_COMPONENTS_NV: Incomplete
GL_MAX_PROGRAM_GENERIC_ATTRIBS_NV: Incomplete
GL_MAX_PROGRAM_GENERIC_RESULTS_NV: Incomplete
GL_MAX_PROGRAM_RESULT_COMPONENTS_NV: Incomplete
GL_MAX_PROGRAM_TEXEL_OFFSET_NV: Incomplete
GL_MIN_PROGRAM_TEXEL_OFFSET_NV: Incomplete
GL_PROGRAM_ATTRIB_COMPONENTS_NV: Incomplete
GL_PROGRAM_RESULT_COMPONENTS_NV: Incomplete

@_f
def glGetProgramEnvParameterIivNV(target, index, params) -> None: ...
@_f
def glGetProgramEnvParameterIuivNV(target, index, params) -> None: ...
@_f
def glGetProgramLocalParameterIivNV(target, index, params) -> None: ...
@_f
def glGetProgramLocalParameterIuivNV(target, index, params) -> None: ...
@_f
def glProgramEnvParameterI4iNV(target, index, x, y, z, w) -> None: ...
@_f
def glProgramEnvParameterI4ivNV(target, index, params) -> None: ...
@_f
def glProgramEnvParameterI4uiNV(target, index, x, y, z, w) -> None: ...
@_f
def glProgramEnvParameterI4uivNV(target, index, params) -> None: ...
@_f
def glProgramEnvParametersI4ivNV(target, index, count, params) -> None: ...
@_f
def glProgramEnvParametersI4uivNV(target, index, count, params) -> None: ...
@_f
def glProgramLocalParameterI4iNV(target, index, x, y, z, w) -> None: ...
@_f
def glProgramLocalParameterI4ivNV(target, index, params) -> None: ...
@_f
def glProgramLocalParameterI4uiNV(target, index, x, y, z, w) -> None: ...
@_f
def glProgramLocalParameterI4uivNV(target, index, params) -> None: ...
@_f
def glProgramLocalParametersI4ivNV(target, index, count, params) -> None: ...
@_f
def glProgramLocalParametersI4uivNV(target, index, count, params) -> None: ...
