from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_FLOAT16_NV: Incomplete
GL_FLOAT16_VEC2_NV: Incomplete
GL_FLOAT16_VEC3_NV: Incomplete
GL_FLOAT16_VEC4_NV: Incomplete
GL_INT16_NV: Incomplete
GL_INT16_VEC2_NV: Incomplete
GL_INT16_VEC3_NV: Incomplete
GL_INT16_VEC4_NV: Incomplete
GL_INT64_NV: Incomplete
GL_INT64_VEC2_NV: Incomplete
GL_INT64_VEC3_NV: Incomplete
GL_INT64_VEC4_NV: Incomplete
GL_INT8_NV: Incomplete
GL_INT8_VEC2_NV: Incomplete
GL_INT8_VEC3_NV: Incomplete
GL_INT8_VEC4_NV: Incomplete
GL_PATCHES: Incomplete
GL_UNSIGNED_INT16_NV: Incomplete
GL_UNSIGNED_INT16_VEC2_NV: Incomplete
GL_UNSIGNED_INT16_VEC3_NV: Incomplete
GL_UNSIGNED_INT16_VEC4_NV: Incomplete
GL_UNSIGNED_INT64_NV: Incomplete
GL_UNSIGNED_INT64_VEC2_NV: Incomplete
GL_UNSIGNED_INT64_VEC3_NV: Incomplete
GL_UNSIGNED_INT64_VEC4_NV: Incomplete
GL_UNSIGNED_INT8_NV: Incomplete
GL_UNSIGNED_INT8_VEC2_NV: Incomplete
GL_UNSIGNED_INT8_VEC3_NV: Incomplete
GL_UNSIGNED_INT8_VEC4_NV: Incomplete

@_f
def glGetUniformi64vNV(program, location, params) -> None: ...
@_f
def glProgramUniform1i64NV(program, location, x) -> None: ...
@_f
def glProgramUniform1i64vNV(program, location, count, value) -> None: ...
@_f
def glProgramUniform1ui64NV(program, location, x) -> None: ...
@_f
def glProgramUniform1ui64vNV(program, location, count, value) -> None: ...
@_f
def glProgramUniform2i64NV(program, location, x, y) -> None: ...
@_f
def glProgramUniform2i64vNV(program, location, count, value) -> None: ...
@_f
def glProgramUniform2ui64NV(program, location, x, y) -> None: ...
@_f
def glProgramUniform2ui64vNV(program, location, count, value) -> None: ...
@_f
def glProgramUniform3i64NV(program, location, x, y, z) -> None: ...
@_f
def glProgramUniform3i64vNV(program, location, count, value) -> None: ...
@_f
def glProgramUniform3ui64NV(program, location, x, y, z) -> None: ...
@_f
def glProgramUniform3ui64vNV(program, location, count, value) -> None: ...
@_f
def glProgramUniform4i64NV(program, location, x, y, z, w) -> None: ...
@_f
def glProgramUniform4i64vNV(program, location, count, value) -> None: ...
@_f
def glProgramUniform4ui64NV(program, location, x, y, z, w) -> None: ...
@_f
def glProgramUniform4ui64vNV(program, location, count, value) -> None: ...
@_f
def glUniform1i64NV(location, x) -> None: ...
@_f
def glUniform1i64vNV(location, count, value) -> None: ...
@_f
def glUniform1ui64NV(location, x) -> None: ...
@_f
def glUniform1ui64vNV(location, count, value) -> None: ...
@_f
def glUniform2i64NV(location, x, y) -> None: ...
@_f
def glUniform2i64vNV(location, count, value) -> None: ...
@_f
def glUniform2ui64NV(location, x, y) -> None: ...
@_f
def glUniform2ui64vNV(location, count, value) -> None: ...
@_f
def glUniform3i64NV(location, x, y, z) -> None: ...
@_f
def glUniform3i64vNV(location, count, value) -> None: ...
@_f
def glUniform3ui64NV(location, x, y, z) -> None: ...
@_f
def glUniform3ui64vNV(location, count, value) -> None: ...
@_f
def glUniform4i64NV(location, x, y, z, w) -> None: ...
@_f
def glUniform4i64vNV(location, count, value) -> None: ...
@_f
def glUniform4ui64NV(location, x, y, z, w) -> None: ...
@_f
def glUniform4ui64vNV(location, count, value) -> None: ...
