from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_HALF_FLOAT_NV: Incomplete

@_f
def glColor3hNV(red, green, blue) -> None: ...
@_f
def glColor3hvNV(v) -> None: ...
@_f
def glColor4hNV(red, green, blue, alpha) -> None: ...
@_f
def glColor4hvNV(v) -> None: ...
@_f
def glFogCoordhNV(fog) -> None: ...
@_f
def glFogCoordhvNV(fog) -> None: ...
@_f
def glMultiTexCoord1hNV(target, s) -> None: ...
@_f
def glMultiTexCoord1hvNV(target, v) -> None: ...
@_f
def glMultiTexCoord2hNV(target, s, t) -> None: ...
@_f
def glMultiTexCoord2hvNV(target, v) -> None: ...
@_f
def glMultiTexCoord3hNV(target, s, t, r) -> None: ...
@_f
def glMultiTexCoord3hvNV(target, v) -> None: ...
@_f
def glMultiTexCoord4hNV(target, s, t, r, q) -> None: ...
@_f
def glMultiTexCoord4hvNV(target, v) -> None: ...
@_f
def glNormal3hNV(nx, ny, nz) -> None: ...
@_f
def glNormal3hvNV(v) -> None: ...
@_f
def glSecondaryColor3hNV(red, green, blue) -> None: ...
@_f
def glSecondaryColor3hvNV(v) -> None: ...
@_f
def glTexCoord1hNV(s) -> None: ...
@_f
def glTexCoord1hvNV(v) -> None: ...
@_f
def glTexCoord2hNV(s, t) -> None: ...
@_f
def glTexCoord2hvNV(v) -> None: ...
@_f
def glTexCoord3hNV(s, t, r) -> None: ...
@_f
def glTexCoord3hvNV(v) -> None: ...
@_f
def glTexCoord4hNV(s, t, r, q) -> None: ...
@_f
def glTexCoord4hvNV(v) -> None: ...
@_f
def glVertex2hNV(x, y) -> None: ...
@_f
def glVertex2hvNV(v) -> None: ...
@_f
def glVertex3hNV(x, y, z) -> None: ...
@_f
def glVertex3hvNV(v) -> None: ...
@_f
def glVertex4hNV(x, y, z, w) -> None: ...
@_f
def glVertex4hvNV(v) -> None: ...
@_f
def glVertexAttrib1hNV(index, x) -> None: ...
@_f
def glVertexAttrib1hvNV(index, v) -> None: ...
@_f
def glVertexAttrib2hNV(index, x, y) -> None: ...
@_f
def glVertexAttrib2hvNV(index, v) -> None: ...
@_f
def glVertexAttrib3hNV(index, x, y, z) -> None: ...
@_f
def glVertexAttrib3hvNV(index, v) -> None: ...
@_f
def glVertexAttrib4hNV(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4hvNV(index, v) -> None: ...
@_f
def glVertexAttribs1hvNV(index, n, v) -> None: ...
@_f
def glVertexAttribs2hvNV(index, n, v) -> None: ...
@_f
def glVertexAttribs3hvNV(index, n, v) -> None: ...
@_f
def glVertexAttribs4hvNV(index, n, v) -> None: ...
@_f
def glVertexWeighthNV(weight) -> None: ...
@_f
def glVertexWeighthvNV(weight) -> None: ...
