from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_CURRENT_OCCLUSION_QUERY_ID_NV: Incomplete
GL_PIXEL_COUNTER_BITS_NV: Incomplete
GL_PIXEL_COUNT_AVAILABLE_NV: Incomplete
GL_PIXEL_COUNT_NV: Incomplete

@_f
def glBeginOcclusionQueryNV(id) -> None: ...
@_f
def glDeleteOcclusionQueriesNV(n, ids) -> None: ...
@_f
def glEndOcclusionQueryNV() -> None: ...
@_f
def glGenOcclusionQueriesNV(n, ids) -> None: ...
@_f
def glGetOcclusionQueryivNV(id, pname, params) -> None: ...
@_f
def glGetOcclusionQueryuivNV(id, pname, params) -> None: ...
@_f
def glIsOcclusionQueryNV(id) -> None: ...
