from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_BUFFER_GPU_ADDRESS_NV: Incomplete
GL_GPU_ADDRESS_NV: Incomplete
GL_MAX_SHADER_BUFFER_ADDRESS_NV: Incomplete

@_f
def glGetBufferParameterui64vNV(target, pname, params) -> None: ...
@_f
def glGetIntegerui64vNV(value, result) -> None: ...
@_f
def glGetNamedBufferParameterui64vNV(buffer, pname, params) -> None: ...
@_f
def glGetUniformui64vNV(program, location, params) -> None: ...
@_f
def glIsBufferResidentNV(target) -> None: ...
@_f
def glIsNamedBufferResidentNV(buffer) -> None: ...
@_f
def glMakeBufferNonResidentNV(target) -> None: ...
@_f
def glMakeBufferResidentNV(target, access) -> None: ...
@_f
def glMakeNamedBufferNonResidentNV(buffer) -> None: ...
@_f
def glMakeNamedBufferResidentNV(buffer, access) -> None: ...
@_f
def glProgramUniformui64NV(program, location, value) -> None: ...
@_f
def glProgramUniformui64vNV(program, location, count, value) -> None: ...
@_f
def glUniformui64NV(location, value) -> None: ...
@_f
def glUniformui64vNV(location, count, value) -> None: ...
