from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_TRANSFORM_FEEDBACK_BINDING_NV: Incomplete
GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE_NV: Incomplete
GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED_NV: Incomplete
GL_TRANSFORM_FEEDBACK_NV: Incomplete

@_f
def glBindTransformFeedbackNV(target, id) -> None: ...
@_f
def glDeleteTransformFeedbacksNV(n, ids) -> None: ...
@_f
def glDrawTransformFeedbackNV(mode, id) -> None: ...
@_f
def glGenTransformFeedbacksNV(n, ids) -> None: ...
@_f
def glIsTransformFeedbackNV(id) -> None: ...
@_f
def glPauseTransformFeedbackNV() -> None: ...
@_f
def glResumeTransformFeedbackNV() -> None: ...
