from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_SURFACE_MAPPED_NV: Incomplete
GL_SURFACE_REGISTERED_NV: Incomplete
GL_SURFACE_STATE_NV: Incomplete
GL_WRITE_DISCARD_NV: Incomplete

@_f
def glVDPAUFiniNV() -> None: ...
@_f
def glVDPAUGetSurfaceivNV(surface, pname, count, length, values) -> None: ...
@_f
def glVDPAUInitNV(vdpDevice, getProcAddress) -> None: ...
@_f
def glVDPAUIsSurfaceNV(surface) -> None: ...
@_f
def glVDPAUMapSurfacesNV(numSurfaces, surfaces) -> None: ...
@_f
def glVDPAURegisterOutputSurfaceNV(vdpSurface, target, numTextureNames, textureNames) -> None: ...
@_f
def glVDPAURegisterVideoSurfaceNV(vdpSurface, target, numTextureNames, textureNames) -> None: ...
@_f
def glVDPAUSurfaceAccessNV(surface, access) -> None: ...
@_f
def glVDPAUUnmapSurfacesNV(numSurface, surfaces) -> None: ...
@_f
def glVDPAUUnregisterSurfaceNV(surface) -> None: ...
