from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_VERTEX_ATTRIB_ARRAY_INTEGER_NV: Incomplete

@_f
def glGetVertexAttribIivEXT(index, pname, params) -> None: ...
@_f
def glGetVertexAttribIuivEXT(index, pname, params) -> None: ...
@_f
def glVertexAttribI1iEXT(index, x) -> None: ...
@_f
def glVertexAttribI1ivEXT(index, v) -> None: ...
@_f
def glVertexAttribI1uiEXT(index, x) -> None: ...
@_f
def glVertexAttribI1uivEXT(index, v) -> None: ...
@_f
def glVertexAttribI2iEXT(index, x, y) -> None: ...
@_f
def glVertexAttribI2ivEXT(index, v) -> None: ...
@_f
def glVertexAttribI2uiEXT(index, x, y) -> None: ...
@_f
def glVertexAttribI2uivEXT(index, v) -> None: ...
@_f
def glVertexAttribI3iEXT(index, x, y, z) -> None: ...
@_f
def glVertexAttribI3ivEXT(index, v) -> None: ...
@_f
def glVertexAttribI3uiEXT(index, x, y, z) -> None: ...
@_f
def glVertexAttribI3uivEXT(index, v) -> None: ...
@_f
def glVertexAttribI4bvEXT(index, v) -> None: ...
@_f
def glVertexAttribI4iEXT(index, x, y, z, w) -> None: ...
@_f
def glVertexAttribI4ivEXT(index, v) -> None: ...
@_f
def glVertexAttribI4svEXT(index, v) -> None: ...
@_f
def glVertexAttribI4ubvEXT(index, v) -> None: ...
@_f
def glVertexAttribI4uiEXT(index, x, y, z, w) -> None: ...
@_f
def glVertexAttribI4uivEXT(index, v) -> None: ...
@_f
def glVertexAttribI4usvEXT(index, v) -> None: ...
@_f
def glVertexAttribIPointerEXT(index, size, type, stride, pointer) -> None: ...
