from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_INT64_NV: Incomplete
GL_UNSIGNED_INT64_NV: Incomplete

@_f
def glGetVertexAttribLi64vNV(index, pname, params) -> None: ...
@_f
def glGetVertexAttribLui64vNV(index, pname, params) -> None: ...
@_f
def glVertexAttribL1i64NV(index, x) -> None: ...
@_f
def glVertexAttribL1i64vNV(index, v) -> None: ...
@_f
def glVertexAttribL1ui64NV(index, x) -> None: ...
@_f
def glVertexAttribL1ui64vNV(index, v) -> None: ...
@_f
def glVertexAttribL2i64NV(index, x, y) -> None: ...
@_f
def glVertexAttribL2i64vNV(index, v) -> None: ...
@_f
def glVertexAttribL2ui64NV(index, x, y) -> None: ...
@_f
def glVertexAttribL2ui64vNV(index, v) -> None: ...
@_f
def glVertexAttribL3i64NV(index, x, y, z) -> None: ...
@_f
def glVertexAttribL3i64vNV(index, v) -> None: ...
@_f
def glVertexAttribL3ui64NV(index, x, y, z) -> None: ...
@_f
def glVertexAttribL3ui64vNV(index, v) -> None: ...
@_f
def glVertexAttribL4i64NV(index, x, y, z, w) -> None: ...
@_f
def glVertexAttribL4i64vNV(index, v) -> None: ...
@_f
def glVertexAttribL4ui64NV(index, x, y, z, w) -> None: ...
@_f
def glVertexAttribL4ui64vNV(index, v) -> None: ...
@_f
def glVertexAttribLFormatNV(index, size, type, stride) -> None: ...
