from OpenGL import MODULE_ANNOTATIONS as MODULE_ANNOTATIONS, logs as logs
from OpenGL._bytes import as_8_bit as as_8_bit
from OpenGL.platform import ctypesloader as ctypesloader
from _typeshed import Incomplete

log: Incomplete

class lazy_property:
    fget: Incomplete
    def __init__(self, function) -> None: ...
    def __get__(self, obj, cls): ...

class _CheckContext:
    func: Incomplete
    ccisvalid: Incomplete
    def __init__(self, func, ccisvalid) -> None: ...
    def __setattr__(self, key, value): ...
    def __getattr__(self, key): ...
    def __call__(self, *args, **named): ...

class BasePlatform:
    EXPORTED_NAMES: Incomplete
    DEFAULT_FUNCTION_TYPE: Incomplete
    GLUT_GUARD_CALLBACKS: bool
    EXTENSIONS_USE_BASE_FUNCTIONS: bool
    def install(self, namespace): ...
    def functionTypeFor(self, dll): ...
    def errorChecking(self, func, dll, error_checker=None): ...
    def wrapContextCheck(self, func, dll): ...
    def wrapLogging(self, func): ...
    def finalArgType(self, typ): ...
    def constructFunction(self, functionName, dll, resultType=..., argTypes=(), doc=None, argNames=(), extension=None, deprecated: bool = False, module=None, force_extension: bool = False, error_checker=None): ...
    def createBaseFunction(self, functionName, dll, resultType=..., argTypes=(), doc=None, argNames=(), extension=None, deprecated: bool = False, module=None, error_checker=None): ...
    def checkExtension(self, name): ...
    createExtensionFunction = createBaseFunction
    def copyBaseFunction(self, original): ...
    def nullFunction(self, functionName, dll, resultType=..., argTypes=(), doc=None, argNames=(), extension=None, deprecated: bool = False, module=None, error_checker=None, force_extension: bool = False): ...
    def GetCurrentContext(self) -> None: ...
    def getGLUTFontPointer(self, constant) -> None: ...
    @lazy_property
    def CurrentContextIsValid(self): ...
    @lazy_property
    def OpenGL(self): ...

class _NullFunctionPointer:
    DLL: Incomplete
    argNames: Incomplete
    argtypes: Incomplete
    errcheck: Incomplete
    restype: Incomplete
    extension: Incomplete
    doc: Incomplete
    deprecated: Incomplete
    error_checker: Incomplete
    force_extension: Incomplete
    def __init__(self, name, dll, resultType, argTypes, argNames, extension=None, doc=None, deprecated: bool = False, error_checker=None, force_extension=None) -> None: ...
    resolved: bool
    def __nonzero__(self): ...
    __bool__ = __nonzero__
    def load(self): ...
    def __call__(self, *args, **named): ...

class _DeprecatedFunctionPointer(_NullFunctionPointer):
    deprecated: bool
    def __call__(self, *args, **named) -> None: ...
