from OpenGL.platform import baseplatform as baseplatform, ctypesloader as ctypesloader
from _typeshed import Incomplete

class DarwinPlatform(baseplatform.BasePlatform):
    DEFAULT_FUNCTION_TYPE: Incomplete
    EXTENSIONS_USE_BASE_FUNCTIONS: bool
    @baseplatform.lazy_property
    def GL(self): ...
    @baseplatform.lazy_property
    def GLU(self): ...
    @baseplatform.lazy_property
    def CGL(self): ...
    @baseplatform.lazy_property
    def GLUT(self): ...
    @baseplatform.lazy_property
    def GLE(self): ...
    @baseplatform.lazy_property
    def GetCurrentContext(self): ...
    def getGLUTFontPointer(self, constant): ...
    @baseplatform.lazy_property
    def glGetError(self): ...
