from OpenGL.platform import baseplatform as baseplatform, ctypesloader as ctypesloader
from _typeshed import Incomplete

class EGLPlatform(baseplatform.BasePlatform):
    @baseplatform.lazy_property
    def GLES1(self): ...
    @baseplatform.lazy_property
    def GLES2(self): ...
    @baseplatform.lazy_property
    def GLES3(self): ...
    @baseplatform.lazy_property
    def GL(self): ...
    @baseplatform.lazy_property
    def GLU(self): ...
    @baseplatform.lazy_property
    def GLUT(self): ...
    @baseplatform.lazy_property
    def OpenGL(self): ...
    @baseplatform.lazy_property
    def EGL(self): ...
    @baseplatform.lazy_property
    def getExtensionProcedure(self): ...
    @baseplatform.lazy_property
    def GLE(self): ...
    DEFAULT_FUNCTION_TYPE: Incomplete
    @baseplatform.lazy_property
    def GetCurrentContext(self): ...
    def getGLUTFontPointer(self, constant): ...
    def install(self, namespace): ...
