from OpenGL.constant import Constant as Constant
from OpenGL.platform import baseplatform as baseplatform, ctypesloader as ctypesloader
from _typeshed import Incomplete

class OSMesaPlatform(baseplatform.BasePlatform):
    EXPORTED_NAMES: Incomplete
    @baseplatform.lazy_property
    def GL(self): ...
    @baseplatform.lazy_property
    def GLU(self): ...
    @baseplatform.lazy_property
    def GLUT(self): ...
    @baseplatform.lazy_property
    def GLE(self): ...
    @baseplatform.lazy_property
    def OSMesa(self): ...
    DEFAULT_FUNCTION_TYPE: Incomplete
    @baseplatform.lazy_property
    def GetCurrentContext(self): ...
    @baseplatform.lazy_property
    def CurrentContextIsValid(self): ...
    @baseplatform.lazy_property
    def getExtensionProcedure(self): ...
    def getGLUTFontPointer(self, constant): ...
