from OpenGL.platform import baseplatform as baseplatform, ctypesloader as ctypesloader
from _typeshed import Incomplete

vc: str
size: Incomplete

class Win32Platform(baseplatform.BasePlatform):
    GLUT_GUARD_CALLBACKS: bool
    @baseplatform.lazy_property
    def GL(self): ...
    @baseplatform.lazy_property
    def GLU(self): ...
    @baseplatform.lazy_property
    def GLUT(self): ...
    @baseplatform.lazy_property
    def GLE(self): ...
    DEFAULT_FUNCTION_TYPE: Incomplete
    GLUT_CALLBACK_TYPE: Incomplete
    GDI32: Incomplete
    @baseplatform.lazy_property
    def WGL(self): ...
    @baseplatform.lazy_property
    def getExtensionProcedure(self): ...
    GLUT_FONT_CONSTANTS: Incomplete
    def getGLUTFontPointer(self, constant): ...
    @baseplatform.lazy_property
    def GetCurrentContext(self): ...
    def constructFunction(self, functionName, dll, resultType=..., argTypes=(), doc=None, argNames=(), extension=None, deprecated: bool = False, module=None, force_extension: bool = False, error_checker=None): ...
