from OpenGL.raw.GLES1._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_BYTE: Incomplete

@_f
def glMultiTexCoord1bOES(texture, s) -> None: ...
@_f
def glMultiTexCoord1bvOES(texture, coords) -> None: ...
@_f
def glMultiTexCoord2bOES(texture, s, t) -> None: ...
@_f
def glMultiTexCoord2bvOES(texture, coords) -> None: ...
@_f
def glMultiTexCoord3bOES(texture, s, t, r) -> None: ...
@_f
def glMultiTexCoord3bvOES(texture, coords) -> None: ...
@_f
def glMultiTexCoord4bOES(texture, s, t, r, q) -> None: ...
@_f
def glMultiTexCoord4bvOES(texture, coords) -> None: ...
@_f
def glTexCoord1bOES(s) -> None: ...
@_f
def glTexCoord1bvOES(coords) -> None: ...
@_f
def glTexCoord2bOES(s, t) -> None: ...
@_f
def glTexCoord2bvOES(coords) -> None: ...
@_f
def glTexCoord3bOES(s, t, r) -> None: ...
@_f
def glTexCoord3bvOES(coords) -> None: ...
@_f
def glTexCoord4bOES(s, t, r, q) -> None: ...
@_f
def glTexCoord4bvOES(coords) -> None: ...
@_f
def glVertex2bOES(x, y) -> None: ...
@_f
def glVertex2bvOES(coords) -> None: ...
@_f
def glVertex3bOES(x, y, z) -> None: ...
@_f
def glVertex3bvOES(coords) -> None: ...
@_f
def glVertex4bOES(x, y, z, w) -> None: ...
@_f
def glVertex4bvOES(coords) -> None: ...
