from OpenGL.raw.GLES1._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_TEXTURE_CROP_RECT_OES: Incomplete

@_f
def glDrawTexfOES(x, y, z, width, height) -> None: ...
@_f
def glDrawTexfvOES(coords) -> None: ...
@_f
def glDrawTexiOES(x, y, z, width, height) -> None: ...
@_f
def glDrawTexivOES(coords) -> None: ...
@_f
def glDrawTexsOES(x, y, z, width, height) -> None: ...
@_f
def glDrawTexsvOES(coords) -> None: ...
@_f
def glDrawTexxOES(x, y, z, width, height) -> None: ...
@_f
def glDrawTexxvOES(coords) -> None: ...
