from OpenGL.raw.GLES1._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_FIXED_OES: Incomplete

@_f
def glAccumxOES(op, value) -> None: ...
@_f
def glAlphaFuncxOES(func, ref) -> None: ...
@_f
def glBitmapxOES(width, height, xorig, yorig, xmove, ymove, bitmap) -> None: ...
@_f
def glBlendColorxOES(red, green, blue, alpha) -> None: ...
@_f
def glClearAccumxOES(red, green, blue, alpha) -> None: ...
@_f
def glClearColorxOES(red, green, blue, alpha) -> None: ...
@_f
def glClearDepthxOES(depth) -> None: ...
@_f
def glClipPlanexOES(plane, equation) -> None: ...
@_f
def glColor3xOES(red, green, blue) -> None: ...
@_f
def glColor3xvOES(components) -> None: ...
@_f
def glColor4xOES(red, green, blue, alpha) -> None: ...
@_f
def glColor4xvOES(components) -> None: ...
@_f
def glConvolutionParameterxOES(target, pname, param) -> None: ...
@_f
def glConvolutionParameterxvOES(target, pname, params) -> None: ...
@_f
def glDepthRangexOES(n, f) -> None: ...
@_f
def glEvalCoord1xOES(u) -> None: ...
@_f
def glEvalCoord1xvOES(coords) -> None: ...
@_f
def glEvalCoord2xOES(u, v) -> None: ...
@_f
def glEvalCoord2xvOES(coords) -> None: ...
@_f
def glFeedbackBufferxOES(n, type, buffer) -> None: ...
@_f
def glFogxOES(pname, param) -> None: ...
@_f
def glFogxvOES(pname, param) -> None: ...
@_f
def glFrustumxOES(l, r, b, t, n, f) -> None: ...
@_f
def glGetClipPlanexOES(plane, equation) -> None: ...
@_f
def glGetConvolutionParameterxvOES(target, pname, params) -> None: ...
@_f
def glGetFixedvOES(pname, params) -> None: ...
@_f
def glGetHistogramParameterxvOES(target, pname, params) -> None: ...
@_f
def glGetLightxOES(light, pname, params) -> None: ...
@_f
def glGetLightxvOES(light, pname, params) -> None: ...
@_f
def glGetMapxvOES(target, query, v) -> None: ...
@_f
def glGetMaterialxOES(face, pname, param) -> None: ...
@_f
def glGetMaterialxvOES(face, pname, params) -> None: ...
@_f
def glGetPixelMapxv(map, size, values) -> None: ...
@_f
def glGetTexEnvxvOES(target, pname, params) -> None: ...
@_f
def glGetTexGenxvOES(coord, pname, params) -> None: ...
@_f
def glGetTexLevelParameterxvOES(target, level, pname, params) -> None: ...
@_f
def glGetTexParameterxvOES(target, pname, params) -> None: ...
@_f
def glIndexxOES(component) -> None: ...
@_f
def glIndexxvOES(component) -> None: ...
@_f
def glLightModelxOES(pname, param) -> None: ...
@_f
def glLightModelxvOES(pname, param) -> None: ...
@_f
def glLightxOES(light, pname, param) -> None: ...
@_f
def glLightxvOES(light, pname, params) -> None: ...
@_f
def glLineWidthxOES(width) -> None: ...
@_f
def glLoadMatrixxOES(m) -> None: ...
@_f
def glLoadTransposeMatrixxOES(m) -> None: ...
@_f
def glMap1xOES(target, u1, u2, stride, order, points) -> None: ...
@_f
def glMap2xOES(target, u1, u2, ustride, uorder, v1, v2, vstride, vorder, points) -> None: ...
@_f
def glMapGrid1xOES(n, u1, u2) -> None: ...
@_f
def glMapGrid2xOES(n, u1, u2, v1, v2) -> None: ...
@_f
def glMaterialxOES(face, pname, param) -> None: ...
@_f
def glMaterialxvOES(face, pname, param) -> None: ...
@_f
def glMultMatrixxOES(m) -> None: ...
@_f
def glMultTransposeMatrixxOES(m) -> None: ...
@_f
def glMultiTexCoord1xOES(texture, s) -> None: ...
@_f
def glMultiTexCoord1xvOES(texture, coords) -> None: ...
@_f
def glMultiTexCoord2xOES(texture, s, t) -> None: ...
@_f
def glMultiTexCoord2xvOES(texture, coords) -> None: ...
@_f
def glMultiTexCoord3xOES(texture, s, t, r) -> None: ...
@_f
def glMultiTexCoord3xvOES(texture, coords) -> None: ...
@_f
def glMultiTexCoord4xOES(texture, s, t, r, q) -> None: ...
@_f
def glMultiTexCoord4xvOES(texture, coords) -> None: ...
@_f
def glNormal3xOES(nx, ny, nz) -> None: ...
@_f
def glNormal3xvOES(coords) -> None: ...
@_f
def glOrthoxOES(l, r, b, t, n, f) -> None: ...
@_f
def glPassThroughxOES(token) -> None: ...
@_f
def glPixelMapx(map, size, values) -> None: ...
@_f
def glPixelStorex(pname, param) -> None: ...
@_f
def glPixelTransferxOES(pname, param) -> None: ...
@_f
def glPixelZoomxOES(xfactor, yfactor) -> None: ...
@_f
def glPointParameterxOES(pname, param) -> None: ...
@_f
def glPointParameterxvOES(pname, params) -> None: ...
@_f
def glPointSizexOES(size) -> None: ...
@_f
def glPolygonOffsetxOES(factor, units) -> None: ...
@_f
def glPrioritizeTexturesxOES(n, textures, priorities) -> None: ...
@_f
def glRasterPos2xOES(x, y) -> None: ...
@_f
def glRasterPos2xvOES(coords) -> None: ...
@_f
def glRasterPos3xOES(x, y, z) -> None: ...
@_f
def glRasterPos3xvOES(coords) -> None: ...
@_f
def glRasterPos4xOES(x, y, z, w) -> None: ...
@_f
def glRasterPos4xvOES(coords) -> None: ...
@_f
def glRectxOES(x1, y1, x2, y2) -> None: ...
@_f
def glRectxvOES(v1, v2) -> None: ...
@_f
def glRotatexOES(angle, x, y, z) -> None: ...
@_f
def glSampleCoveragexOES(value, invert) -> None: ...
@_f
def glScalexOES(x, y, z) -> None: ...
@_f
def glTexCoord1xOES(s) -> None: ...
@_f
def glTexCoord1xvOES(coords) -> None: ...
@_f
def glTexCoord2xOES(s, t) -> None: ...
@_f
def glTexCoord2xvOES(coords) -> None: ...
@_f
def glTexCoord3xOES(s, t, r) -> None: ...
@_f
def glTexCoord3xvOES(coords) -> None: ...
@_f
def glTexCoord4xOES(s, t, r, q) -> None: ...
@_f
def glTexCoord4xvOES(coords) -> None: ...
@_f
def glTexEnvxOES(target, pname, param) -> None: ...
@_f
def glTexEnvxvOES(target, pname, params) -> None: ...
@_f
def glTexGenxOES(coord, pname, param) -> None: ...
@_f
def glTexGenxvOES(coord, pname, params) -> None: ...
@_f
def glTexParameterxOES(target, pname, param) -> None: ...
@_f
def glTexParameterxvOES(target, pname, params) -> None: ...
@_f
def glTranslatexOES(x, y, z) -> None: ...
@_f
def glVertex2xOES(x) -> None: ...
@_f
def glVertex2xvOES(coords) -> None: ...
@_f
def glVertex3xOES(x, y) -> None: ...
@_f
def glVertex3xvOES(coords) -> None: ...
@_f
def glVertex4xOES(x, y, z) -> None: ...
@_f
def glVertex4xvOES(coords) -> None: ...
