from OpenGL.raw.GLES1._types import *
from OpenGL import arrays as arrays

@_f
def glClearDepthfOES(depth) -> None: ...
@_f
def glClipPlanefOES(plane, equation) -> None: ...
@_f
def glDepthRangefOES(n, f) -> None: ...
@_f
def glFrustumfOES(l, r, b, t, n, f) -> None: ...
@_f
def glGetClipPlanefOES(plane, equation) -> None: ...
@_f
def glOrthofOES(l, r, b, t, n, f) -> None: ...
