import ctypes
from _typeshed import Incomplete

pointer: Incomplete

class _Opaque(ctypes.Structure): ...

class _opaque_pointer(Incomplete):
    @classmethod
    def from_param(cls, value): ...
    @property
    def address(self): ...
    @property
    def as_voidp(self): ...
    def __hash__(self): ...

def opaque_pointer_cls(name): ...
