from OpenGL._bytes import as_8_bit as as_8_bit, bytes as bytes, integer_types as integer_types, long as long, maxsize as maxsize, unicode as unicode

class Constant:
    def __new__(cls, name, value=None): ...
    def __getnewargs__(self): ...

class NumericConstant(Constant): ...
class IntConstant(NumericConstant, int): ...
class LongConstant(NumericConstant, long): ...
LongConstant = IntConstant

class FloatConstant(NumericConstant, float): ...
class StringConstant(Constant, bytes): ...
