from OpenGL import platform as platform
from _typeshed import Incomplete

storedPointers: Incomplete
storedWeakPointers: Incomplete
STORAGES: Incomplete

def getContext(context=None): ...
def setValue(constant, value, context=None, weak: bool = False): ...
def delValue(constant, context=None): ...
def getValue(constant, context=None): ...
def cleanupContext(context=None): ...
