from _typeshed import Incomplete
from ctypes import ArgumentError as ArgumentError

__all__ = ['Error', 'GLError', 'GLUError', 'GLUTError', 'GLerror', 'GLUerror', 'GLUTerror', 'ArgumentError']

class Error(Exception): ...
class NoContext(Error): ...
class CopyError(Error): ...
class NullFunctionError(Error): ...

class GLError(Error):
    def __init__(self, err=None, result=None, cArguments=None, baseOperation=None, pyArgs=None, cArgs=None, description=None) -> None: ...
    DISPLAY_ORDER: Incomplete
    description: Incomplete
    def format_description(self, property, value): ...
    def shortRepr(self, value, firstLevel: bool = True): ...
    def format_baseOperation(self, property, value): ...

class GLUError(Error): ...
class GLUTError(Error): ...
class EGLError(GLError): ...

class _ErrorChecker:
    def __init__(self, platform, baseOperation=None, noErrorResult: int = 0, errorClass=...) -> None: ...
    def __bool__(self) -> bool: ...
    def safeGetError(self): ...
    def nullGetError(self): ...
    def glCheckError(self, result, baseOperation=None, cArguments=None, *args): ...
    def onBegin(self) -> None: ...
    def onEnd(self) -> None: ...
GLUerror = GLUError
GLerror = GLError
GLUTerror = GLUTError
