from OpenGL import arrays as arrays, error as error
from _typeshed import Incomplete

def SetupPixelRead(format, dims, type): ...
def setupDefaultTransferMode() -> None: ...
def rankPacking(rank) -> None: ...
def createTargetArray(format, dims, type): ...
def formatToComponentCount(format): ...
def returnFormat(data, type): ...

COMPONENT_COUNTS: Incomplete
TYPE_TO_BITS: Incomplete
TYPE_TO_ARRAYTYPE: Incomplete
TIGHT_PACK_FORMATS: Incomplete
RANK_PACKINGS: Incomplete
