from OpenGL import acceleratesupport as acceleratesupport
from _typeshed import Incomplete

LateBind: Incomplete
Curry: Incomplete

class LateBind:
    def setFinalCall(self, finalCall) -> None: ...
    def getFinalCall(self): ...
    def finalise(self) -> None: ...
    def __nonzero__(self): ...
    def __call__(self, *args, **named): ...

class Curry:
    wrapperFunction: Incomplete
    baseFunction: Incomplete
    def __init__(self, wrapperFunction, baseFunction) -> None: ...
    def __call__(self, *args, **named): ...
