import logging
from OpenGL._configflags import ERROR_LOGGING as ERROR_LOGGING, FULL_LOGGING as FULL_LOGGING

getLog = logging.getLogger

def getException(error): ...

class _LoggedFunction:
    def __init__(self, base, log) -> None: ...
    def __setattr__(self, key, value) -> None: ...
    def __getattr__(self, key): ...

class _FullLoggedFunction(_LoggedFunction):
    def __call__(self, *args, **named): ...

class _ErrorLoggedFunction(_LoggedFunction):
    def __call__(self, *args, **named): ...

def logOnFail(function, log): ...
