from OpenGL import acceleratesupport as acceleratesupport, converters as converters, error as error, platform as platform
from OpenGL._configflags import ERROR_ON_COPY as ERROR_ON_COPY, SIZE_1_ARRAY_UNPACK as SIZE_1_ARRAY_UNPACK, STORE_POINTERS as STORE_POINTERS
from OpenGL._null import NULL as NULL
from OpenGL.arrays import arraydatatype as arraydatatype, arrayhelpers as arrayhelpers
from OpenGL.converters import DefaultCConverter as DefaultCConverter, returnCArgument as returnCArgument, returnPyArgument as returnPyArgument
from OpenGL_accelerate.latebind import LateBind as LateBind
from _typeshed import Incomplete

cWrapper: Incomplete

def asList(o): ...
def none_or_pass(incoming, function, arguments): ...

class Wrapper(LateBind):
    localProperties: Incomplete
    wrappedOperation: Incomplete
    def __init__(self, wrappedOperation) -> None: ...
    def __getattr__(self, key): ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__
    def __setattr__(self, key, value): ...
    def pyArgIndex(self, argName): ...
    def cArgIndex(self, argName): ...
    def setOutput(self, outArg, size=(1,), pnameArg=None, arrayType=None, oldStyleReturn=..., orPassIn: bool = False): ...
    def typeOfArg(self, outArg): ...
    def setInputArraySize(self, argName, size=None): ...
    def setInputArraySize(self, argName, size=None): ...
    pyConverters: Incomplete
    pyConverterNames: Incomplete
    def setPyConverter(self, argName, function=...): ...
    cConverters: Incomplete
    def setCConverter(self, argName, function): ...
    cResolvers: Incomplete
    def setCResolver(self, argName, function=...): ...
    storeValues: Incomplete
    def setStoreValues(self, function=...): ...
    returnValues: Incomplete
    def setReturnValues(self, function=...): ...
    def finalise(self): ...
    def finaliseCall(self): ...

class MultiReturn:
    children: Incomplete
    def __init__(self, *children) -> None: ...
    def append(self, child) -> None: ...
    def __call__(self, *args, **named): ...

def wrapper(wrappedOperation): ...
