from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_BLEND_COLOR: Incomplete
GL_BLEND_DST_ALPHA: Incomplete
GL_BLEND_DST_RGB: Incomplete
GL_BLEND_EQUATION: Incomplete
GL_BLEND_SRC_ALPHA: Incomplete
GL_BLEND_SRC_RGB: Incomplete
GL_COLOR_SUM: Incomplete
GL_COMPARE_R_TO_TEXTURE: Incomplete
GL_CONSTANT_ALPHA: Incomplete
GL_CONSTANT_COLOR: Incomplete
GL_CURRENT_FOG_COORDINATE: Incomplete
GL_CURRENT_SECONDARY_COLOR: Incomplete
GL_DECR_WRAP: Incomplete
GL_DEPTH_COMPONENT16: Incomplete
GL_DEPTH_COMPONENT24: Incomplete
GL_DEPTH_COMPONENT32: Incomplete
GL_DEPTH_TEXTURE_MODE: Incomplete
GL_FOG_COORDINATE: Incomplete
GL_FOG_COORDINATE_ARRAY: Incomplete
GL_FOG_COORDINATE_ARRAY_POINTER: Incomplete
GL_FOG_COORDINATE_ARRAY_STRIDE: Incomplete
GL_FOG_COORDINATE_ARRAY_TYPE: Incomplete
GL_FOG_COORDINATE_SOURCE: Incomplete
GL_FRAGMENT_DEPTH: Incomplete
GL_FUNC_ADD: Incomplete
GL_FUNC_REVERSE_SUBTRACT: Incomplete
GL_FUNC_SUBTRACT: Incomplete
GL_GENERATE_MIPMAP: Incomplete
GL_GENERATE_MIPMAP_HINT: Incomplete
GL_INCR_WRAP: Incomplete
GL_MAX: Incomplete
GL_MAX_TEXTURE_LOD_BIAS: Incomplete
GL_MIN: Incomplete
GL_MIRRORED_REPEAT: Incomplete
GL_ONE_MINUS_CONSTANT_ALPHA: Incomplete
GL_ONE_MINUS_CONSTANT_COLOR: Incomplete
GL_POINT_DISTANCE_ATTENUATION: Incomplete
GL_POINT_FADE_THRESHOLD_SIZE: Incomplete
GL_POINT_SIZE_MAX: Incomplete
GL_POINT_SIZE_MIN: Incomplete
GL_SECONDARY_COLOR_ARRAY: Incomplete
GL_SECONDARY_COLOR_ARRAY_POINTER: Incomplete
GL_SECONDARY_COLOR_ARRAY_SIZE: Incomplete
GL_SECONDARY_COLOR_ARRAY_STRIDE: Incomplete
GL_SECONDARY_COLOR_ARRAY_TYPE: Incomplete
GL_TEXTURE_COMPARE_FUNC: Incomplete
GL_TEXTURE_COMPARE_MODE: Incomplete
GL_TEXTURE_DEPTH_SIZE: Incomplete
GL_TEXTURE_FILTER_CONTROL: Incomplete
GL_TEXTURE_LOD_BIAS: Incomplete

@_f
def glBlendColor(red, green, blue, alpha) -> None: ...
@_f
def glBlendEquation(mode) -> None: ...
@_f
def glBlendFuncSeparate(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha) -> None: ...
@_f
def glFogCoordPointer(type, stride, pointer) -> None: ...
@_f
def glFogCoordd(coord) -> None: ...
@_f
def glFogCoorddv(coord) -> None: ...
@_f
def glFogCoordf(coord) -> None: ...
@_f
def glFogCoordfv(coord) -> None: ...
@_f
def glMultiDrawArrays(mode, first, count, drawcount) -> None: ...
@_f
def glMultiDrawElements(mode, count, type, indices, drawcount) -> None: ...
@_f
def glPointParameterf(pname, param) -> None: ...
@_f
def glPointParameterfv(pname, params) -> None: ...
@_f
def glPointParameteri(pname, param) -> None: ...
@_f
def glPointParameteriv(pname, params) -> None: ...
@_f
def glSecondaryColor3b(red, green, blue) -> None: ...
@_f
def glSecondaryColor3bv(v) -> None: ...
@_f
def glSecondaryColor3d(red, green, blue) -> None: ...
@_f
def glSecondaryColor3dv(v) -> None: ...
@_f
def glSecondaryColor3f(red, green, blue) -> None: ...
@_f
def glSecondaryColor3fv(v) -> None: ...
@_f
def glSecondaryColor3i(red, green, blue) -> None: ...
@_f
def glSecondaryColor3iv(v) -> None: ...
@_f
def glSecondaryColor3s(red, green, blue) -> None: ...
@_f
def glSecondaryColor3sv(v) -> None: ...
@_f
def glSecondaryColor3ub(red, green, blue) -> None: ...
@_f
def glSecondaryColor3ubv(v) -> None: ...
@_f
def glSecondaryColor3ui(red, green, blue) -> None: ...
@_f
def glSecondaryColor3uiv(v) -> None: ...
@_f
def glSecondaryColor3us(red, green, blue) -> None: ...
@_f
def glSecondaryColor3usv(v) -> None: ...
@_f
def glSecondaryColorPointer(size, type, stride, pointer) -> None: ...
@_f
def glWindowPos2d(x, y) -> None: ...
@_f
def glWindowPos2dv(v) -> None: ...
@_f
def glWindowPos2f(x, y) -> None: ...
@_f
def glWindowPos2fv(v) -> None: ...
@_f
def glWindowPos2i(x, y) -> None: ...
@_f
def glWindowPos2iv(v) -> None: ...
@_f
def glWindowPos2s(x, y) -> None: ...
@_f
def glWindowPos2sv(v) -> None: ...
@_f
def glWindowPos3d(x, y, z) -> None: ...
@_f
def glWindowPos3dv(v) -> None: ...
@_f
def glWindowPos3f(x, y, z) -> None: ...
@_f
def glWindowPos3fv(v) -> None: ...
@_f
def glWindowPos3i(x, y, z) -> None: ...
@_f
def glWindowPos3iv(v) -> None: ...
@_f
def glWindowPos3s(x, y, z) -> None: ...
@_f
def glWindowPos3sv(v) -> None: ...
