from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ACTIVE_ATTRIBUTES: Incomplete
GL_ACTIVE_ATTRIBUTE_MAX_LENGTH: Incomplete
GL_ACTIVE_UNIFORMS: Incomplete
GL_ACTIVE_UNIFORM_MAX_LENGTH: Incomplete
GL_ATTACHED_SHADERS: Incomplete
GL_BLEND_EQUATION_ALPHA: Incomplete
GL_BLEND_EQUATION_RGB: Incomplete
GL_BOOL: Incomplete
GL_BOOL_VEC2: Incomplete
GL_BOOL_VEC3: Incomplete
GL_BOOL_VEC4: Incomplete
GL_COMPILE_STATUS: Incomplete
GL_COORD_REPLACE: Incomplete
GL_CURRENT_PROGRAM: Incomplete
GL_CURRENT_VERTEX_ATTRIB: Incomplete
GL_DELETE_STATUS: Incomplete
GL_DRAW_BUFFER0: Incomplete
GL_DRAW_BUFFER1: Incomplete
GL_DRAW_BUFFER10: Incomplete
GL_DRAW_BUFFER11: Incomplete
GL_DRAW_BUFFER12: Incomplete
GL_DRAW_BUFFER13: Incomplete
GL_DRAW_BUFFER14: Incomplete
GL_DRAW_BUFFER15: Incomplete
GL_DRAW_BUFFER2: Incomplete
GL_DRAW_BUFFER3: Incomplete
GL_DRAW_BUFFER4: Incomplete
GL_DRAW_BUFFER5: Incomplete
GL_DRAW_BUFFER6: Incomplete
GL_DRAW_BUFFER7: Incomplete
GL_DRAW_BUFFER8: Incomplete
GL_DRAW_BUFFER9: Incomplete
GL_FLOAT_MAT2: Incomplete
GL_FLOAT_MAT3: Incomplete
GL_FLOAT_MAT4: Incomplete
GL_FLOAT_VEC2: Incomplete
GL_FLOAT_VEC3: Incomplete
GL_FLOAT_VEC4: Incomplete
GL_FRAGMENT_SHADER: Incomplete
GL_FRAGMENT_SHADER_DERIVATIVE_HINT: Incomplete
GL_INFO_LOG_LENGTH: Incomplete
GL_INT_VEC2: Incomplete
GL_INT_VEC3: Incomplete
GL_INT_VEC4: Incomplete
GL_LINK_STATUS: Incomplete
GL_LOWER_LEFT: Incomplete
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS: Incomplete
GL_MAX_DRAW_BUFFERS: Incomplete
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS: Incomplete
GL_MAX_TEXTURE_COORDS: Incomplete
GL_MAX_TEXTURE_IMAGE_UNITS: Incomplete
GL_MAX_VARYING_FLOATS: Incomplete
GL_MAX_VERTEX_ATTRIBS: Incomplete
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS: Incomplete
GL_MAX_VERTEX_UNIFORM_COMPONENTS: Incomplete
GL_POINT_SPRITE: Incomplete
GL_POINT_SPRITE_COORD_ORIGIN: Incomplete
GL_SAMPLER_1D: Incomplete
GL_SAMPLER_1D_SHADOW: Incomplete
GL_SAMPLER_2D: Incomplete
GL_SAMPLER_2D_SHADOW: Incomplete
GL_SAMPLER_3D: Incomplete
GL_SAMPLER_CUBE: Incomplete
GL_SHADER_SOURCE_LENGTH: Incomplete
GL_SHADER_TYPE: Incomplete
GL_SHADING_LANGUAGE_VERSION: Incomplete
GL_STENCIL_BACK_FAIL: Incomplete
GL_STENCIL_BACK_FUNC: Incomplete
GL_STENCIL_BACK_PASS_DEPTH_FAIL: Incomplete
GL_STENCIL_BACK_PASS_DEPTH_PASS: Incomplete
GL_STENCIL_BACK_REF: Incomplete
GL_STENCIL_BACK_VALUE_MASK: Incomplete
GL_STENCIL_BACK_WRITEMASK: Incomplete
GL_UPPER_LEFT: Incomplete
GL_VALIDATE_STATUS: Incomplete
GL_VERTEX_ATTRIB_ARRAY_ENABLED: Incomplete
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED: Incomplete
GL_VERTEX_ATTRIB_ARRAY_POINTER: Incomplete
GL_VERTEX_ATTRIB_ARRAY_SIZE: Incomplete
GL_VERTEX_ATTRIB_ARRAY_STRIDE: Incomplete
GL_VERTEX_ATTRIB_ARRAY_TYPE: Incomplete
GL_VERTEX_PROGRAM_POINT_SIZE: Incomplete
GL_VERTEX_PROGRAM_TWO_SIDE: Incomplete
GL_VERTEX_SHADER: Incomplete

@_f
def glAttachShader(program, shader) -> None: ...
@_f
def glBindAttribLocation(program, index, name) -> None: ...
@_f
def glBlendEquationSeparate(modeRGB, modeAlpha) -> None: ...
@_f
def glCompileShader(shader) -> None: ...
@_f
def glCreateProgram() -> None: ...
@_f
def glCreateShader(type) -> None: ...
@_f
def glDeleteProgram(program) -> None: ...
@_f
def glDeleteShader(shader) -> None: ...
@_f
def glDetachShader(program, shader) -> None: ...
@_f
def glDisableVertexAttribArray(index) -> None: ...
@_f
def glDrawBuffers(n, bufs) -> None: ...
@_f
def glEnableVertexAttribArray(index) -> None: ...
@_f
def glGetActiveAttrib(program, index, bufSize, length, size, type, name) -> None: ...
@_f
def glGetActiveUniform(program, index, bufSize, length, size, type, name) -> None: ...
@_f
def glGetAttachedShaders(program, maxCount, count, shaders) -> None: ...
@_f
def glGetAttribLocation(program, name) -> None: ...
@_f
def glGetProgramInfoLog(program, bufSize, length, infoLog) -> None: ...
@_f
def glGetProgramiv(program, pname, params) -> None: ...
@_f
def glGetShaderInfoLog(shader, bufSize, length, infoLog) -> None: ...
@_f
def glGetShaderSource(shader, bufSize, length, source) -> None: ...
@_f
def glGetShaderiv(shader, pname, params) -> None: ...
@_f
def glGetUniformLocation(program, name) -> None: ...
@_f
def glGetUniformfv(program, location, params) -> None: ...
@_f
def glGetUniformiv(program, location, params) -> None: ...
@_f
def glGetVertexAttribPointerv(index, pname, pointer) -> None: ...
@_f
def glGetVertexAttribdv(index, pname, params) -> None: ...
@_f
def glGetVertexAttribfv(index, pname, params) -> None: ...
@_f
def glGetVertexAttribiv(index, pname, params) -> None: ...
@_f
def glIsProgram(program) -> None: ...
@_f
def glIsShader(shader) -> None: ...
@_f
def glLinkProgram(program) -> None: ...
@_f
def glShaderSource(shader, count, string, length) -> None: ...
@_f
def glStencilFuncSeparate(face, func, ref, mask) -> None: ...
@_f
def glStencilMaskSeparate(face, mask) -> None: ...
@_f
def glStencilOpSeparate(face, sfail, dpfail, dppass) -> None: ...
@_f
def glUniform1f(location, v0) -> None: ...
@_f
def glUniform1fv(location, count, value) -> None: ...
@_f
def glUniform1i(location, v0) -> None: ...
@_f
def glUniform1iv(location, count, value) -> None: ...
@_f
def glUniform2f(location, v0, v1) -> None: ...
@_f
def glUniform2fv(location, count, value) -> None: ...
@_f
def glUniform2i(location, v0, v1) -> None: ...
@_f
def glUniform2iv(location, count, value) -> None: ...
@_f
def glUniform3f(location, v0, v1, v2) -> None: ...
@_f
def glUniform3fv(location, count, value) -> None: ...
@_f
def glUniform3i(location, v0, v1, v2) -> None: ...
@_f
def glUniform3iv(location, count, value) -> None: ...
@_f
def glUniform4f(location, v0, v1, v2, v3) -> None: ...
@_f
def glUniform4fv(location, count, value) -> None: ...
@_f
def glUniform4i(location, v0, v1, v2, v3) -> None: ...
@_f
def glUniform4iv(location, count, value) -> None: ...
@_f
def glUniformMatrix2fv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix3fv(location, count, transpose, value) -> None: ...
@_f
def glUniformMatrix4fv(location, count, transpose, value) -> None: ...
@_f
def glUseProgram(program) -> None: ...
@_f
def glValidateProgram(program) -> None: ...
@_f
def glVertexAttrib1d(index, x) -> None: ...
@_f
def glVertexAttrib1dv(index, v) -> None: ...
@_f
def glVertexAttrib1f(index, x) -> None: ...
@_f
def glVertexAttrib1fv(index, v) -> None: ...
@_f
def glVertexAttrib1s(index, x) -> None: ...
@_f
def glVertexAttrib1sv(index, v) -> None: ...
@_f
def glVertexAttrib2d(index, x, y) -> None: ...
@_f
def glVertexAttrib2dv(index, v) -> None: ...
@_f
def glVertexAttrib2f(index, x, y) -> None: ...
@_f
def glVertexAttrib2fv(index, v) -> None: ...
@_f
def glVertexAttrib2s(index, x, y) -> None: ...
@_f
def glVertexAttrib2sv(index, v) -> None: ...
@_f
def glVertexAttrib3d(index, x, y, z) -> None: ...
@_f
def glVertexAttrib3dv(index, v) -> None: ...
@_f
def glVertexAttrib3f(index, x, y, z) -> None: ...
@_f
def glVertexAttrib3fv(index, v) -> None: ...
@_f
def glVertexAttrib3s(index, x, y, z) -> None: ...
@_f
def glVertexAttrib3sv(index, v) -> None: ...
@_f
def glVertexAttrib4Nbv(index, v) -> None: ...
@_f
def glVertexAttrib4Niv(index, v) -> None: ...
@_f
def glVertexAttrib4Nsv(index, v) -> None: ...
@_f
def glVertexAttrib4Nub(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4Nubv(index, v) -> None: ...
@_f
def glVertexAttrib4Nuiv(index, v) -> None: ...
@_f
def glVertexAttrib4Nusv(index, v) -> None: ...
@_f
def glVertexAttrib4bv(index, v) -> None: ...
@_f
def glVertexAttrib4d(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4dv(index, v) -> None: ...
@_f
def glVertexAttrib4f(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4fv(index, v) -> None: ...
@_f
def glVertexAttrib4iv(index, v) -> None: ...
@_f
def glVertexAttrib4s(index, x, y, z, w) -> None: ...
@_f
def glVertexAttrib4sv(index, v) -> None: ...
@_f
def glVertexAttrib4ubv(index, v) -> None: ...
@_f
def glVertexAttrib4uiv(index, v) -> None: ...
@_f
def glVertexAttrib4usv(index, v) -> None: ...
@_f
def glVertexAttribPointer(index, size, type, normalized, stride, pointer) -> None: ...
