from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ANY_SAMPLES_PASSED: Incomplete
GL_INT_2_10_10_10_REV: Incomplete
GL_MAX_DUAL_SOURCE_DRAW_BUFFERS: Incomplete
GL_ONE_MINUS_SRC1_ALPHA: Incomplete
GL_ONE_MINUS_SRC1_COLOR: Incomplete
GL_RGB10_A2UI: Incomplete
GL_SAMPLER_BINDING: Incomplete
GL_SRC1_COLOR: Incomplete
GL_TEXTURE_SWIZZLE_A: Incomplete
GL_TEXTURE_SWIZZLE_B: Incomplete
GL_TEXTURE_SWIZZLE_G: Incomplete
GL_TEXTURE_SWIZZLE_R: Incomplete
GL_TEXTURE_SWIZZLE_RGBA: Incomplete
GL_TIMESTAMP: Incomplete
GL_TIME_ELAPSED: Incomplete
GL_VERTEX_ATTRIB_ARRAY_DIVISOR: Incomplete

@_f
def glBindFragDataLocationIndexed(program, colorNumber, index, name) -> None: ...
@_f
def glBindSampler(unit, sampler) -> None: ...
@_f
def glColorP3ui(type, color) -> None: ...
@_f
def glColorP3uiv(type, color) -> None: ...
@_f
def glColorP4ui(type, color) -> None: ...
@_f
def glColorP4uiv(type, color) -> None: ...
@_f
def glDeleteSamplers(count, samplers) -> None: ...
@_f
def glGenSamplers(count, samplers) -> None: ...
@_f
def glGetFragDataIndex(program, name) -> None: ...
@_f
def glGetQueryObjecti64v(id, pname, params) -> None: ...
@_f
def glGetQueryObjectui64v(id, pname, params) -> None: ...
@_f
def glGetSamplerParameterIiv(sampler, pname, params) -> None: ...
@_f
def glGetSamplerParameterIuiv(sampler, pname, params) -> None: ...
@_f
def glGetSamplerParameterfv(sampler, pname, params) -> None: ...
@_f
def glGetSamplerParameteriv(sampler, pname, params) -> None: ...
@_f
def glIsSampler(sampler) -> None: ...
@_f
def glMultiTexCoordP1ui(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP1uiv(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP2ui(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP2uiv(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP3ui(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP3uiv(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP4ui(texture, type, coords) -> None: ...
@_f
def glMultiTexCoordP4uiv(texture, type, coords) -> None: ...
@_f
def glNormalP3ui(type, coords) -> None: ...
@_f
def glNormalP3uiv(type, coords) -> None: ...
@_f
def glQueryCounter(id, target) -> None: ...
@_f
def glSamplerParameterIiv(sampler, pname, param) -> None: ...
@_f
def glSamplerParameterIuiv(sampler, pname, param) -> None: ...
@_f
def glSamplerParameterf(sampler, pname, param) -> None: ...
@_f
def glSamplerParameterfv(sampler, pname, param) -> None: ...
@_f
def glSamplerParameteri(sampler, pname, param) -> None: ...
@_f
def glSamplerParameteriv(sampler, pname, param) -> None: ...
@_f
def glSecondaryColorP3ui(type, color) -> None: ...
@_f
def glSecondaryColorP3uiv(type, color) -> None: ...
@_f
def glTexCoordP1ui(type, coords) -> None: ...
@_f
def glTexCoordP1uiv(type, coords) -> None: ...
@_f
def glTexCoordP2ui(type, coords) -> None: ...
@_f
def glTexCoordP2uiv(type, coords) -> None: ...
@_f
def glTexCoordP3ui(type, coords) -> None: ...
@_f
def glTexCoordP3uiv(type, coords) -> None: ...
@_f
def glTexCoordP4ui(type, coords) -> None: ...
@_f
def glTexCoordP4uiv(type, coords) -> None: ...
@_f
def glVertexAttribDivisor(index, divisor) -> None: ...
@_f
def glVertexAttribP1ui(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP1uiv(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP2ui(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP2uiv(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP3ui(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP3uiv(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP4ui(index, type, normalized, value) -> None: ...
@_f
def glVertexAttribP4uiv(index, type, normalized, value) -> None: ...
@_f
def glVertexP2ui(type, value) -> None: ...
@_f
def glVertexP2uiv(type, value) -> None: ...
@_f
def glVertexP3ui(type, value) -> None: ...
@_f
def glVertexP3uiv(type, value) -> None: ...
@_f
def glVertexP4ui(type, value) -> None: ...
@_f
def glVertexP4uiv(type, value) -> None: ...
