from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ACTIVE_PROGRAM: Incomplete
GL_ALL_SHADER_BITS: Incomplete
GL_FIXED: Incomplete
GL_FRAGMENT_SHADER_BIT: Incomplete
GL_GEOMETRY_SHADER_BIT: Incomplete
GL_HIGH_FLOAT: Incomplete
GL_HIGH_INT: Incomplete
GL_IMPLEMENTATION_COLOR_READ_FORMAT: Incomplete
GL_IMPLEMENTATION_COLOR_READ_TYPE: Incomplete
GL_LAYER_PROVOKING_VERTEX: Incomplete
GL_LOW_FLOAT: Incomplete
GL_LOW_INT: Incomplete
GL_MAX_FRAGMENT_UNIFORM_VECTORS: Incomplete
GL_MAX_VARYING_VECTORS: Incomplete
GL_MAX_VERTEX_UNIFORM_VECTORS: Incomplete
GL_MAX_VIEWPORTS: Incomplete
GL_MEDIUM_FLOAT: Incomplete
GL_MEDIUM_INT: Incomplete
GL_NUM_PROGRAM_BINARY_FORMATS: Incomplete
GL_NUM_SHADER_BINARY_FORMATS: Incomplete
GL_PROGRAM_BINARY_FORMATS: Incomplete
GL_PROGRAM_BINARY_LENGTH: Incomplete
GL_PROGRAM_BINARY_RETRIEVABLE_HINT: Incomplete
GL_PROGRAM_PIPELINE_BINDING: Incomplete
GL_PROGRAM_SEPARABLE: Incomplete
GL_RGB565: Incomplete
GL_SHADER_BINARY_FORMATS: Incomplete
GL_SHADER_COMPILER: Incomplete
GL_TESS_CONTROL_SHADER_BIT: Incomplete
GL_TESS_EVALUATION_SHADER_BIT: Incomplete
GL_UNDEFINED_VERTEX: Incomplete
GL_VERTEX_SHADER_BIT: Incomplete
GL_VIEWPORT_BOUNDS_RANGE: Incomplete
GL_VIEWPORT_INDEX_PROVOKING_VERTEX: Incomplete
GL_VIEWPORT_SUBPIXEL_BITS: Incomplete

@_f
def glActiveShaderProgram(pipeline, program) -> None: ...
@_f
def glBindProgramPipeline(pipeline) -> None: ...
@_f
def glClearDepthf(d) -> None: ...
@_f
def glCreateShaderProgramv(type, count, strings) -> None: ...
@_f
def glDeleteProgramPipelines(n, pipelines) -> None: ...
@_f
def glDepthRangeArrayv(first, count, v) -> None: ...
@_f
def glDepthRangeIndexed(index, n, f) -> None: ...
@_f
def glDepthRangef(n, f) -> None: ...
@_f
def glGenProgramPipelines(n, pipelines) -> None: ...
@_f
def glGetDoublei_v(target, index, data) -> None: ...
@_f
def glGetFloati_v(target, index, data) -> None: ...
@_f
def glGetProgramBinary(program, bufSize, length, binaryFormat, binary) -> None: ...
@_f
def glGetProgramPipelineInfoLog(pipeline, bufSize, length, infoLog) -> None: ...
@_f
def glGetProgramPipelineiv(pipeline, pname, params) -> None: ...
@_f
def glGetShaderPrecisionFormat(shadertype, precisiontype, range, precision) -> None: ...
@_f
def glGetVertexAttribLdv(index, pname, params) -> None: ...
@_f
def glIsProgramPipeline(pipeline) -> None: ...
@_f
def glProgramBinary(program, binaryFormat, binary, length) -> None: ...
@_f
def glProgramUniform1d(program, location, v0) -> None: ...
@_f
def glProgramUniform1dv(program, location, count, value) -> None: ...
@_f
def glProgramUniform1f(program, location, v0) -> None: ...
@_f
def glProgramUniform1fv(program, location, count, value) -> None: ...
@_f
def glProgramUniform1i(program, location, v0) -> None: ...
@_f
def glProgramUniform1iv(program, location, count, value) -> None: ...
@_f
def glProgramUniform1ui(program, location, v0) -> None: ...
@_f
def glProgramUniform1uiv(program, location, count, value) -> None: ...
@_f
def glProgramUniform2d(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2dv(program, location, count, value) -> None: ...
@_f
def glProgramUniform2f(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2fv(program, location, count, value) -> None: ...
@_f
def glProgramUniform2i(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2iv(program, location, count, value) -> None: ...
@_f
def glProgramUniform2ui(program, location, v0, v1) -> None: ...
@_f
def glProgramUniform2uiv(program, location, count, value) -> None: ...
@_f
def glProgramUniform3d(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3dv(program, location, count, value) -> None: ...
@_f
def glProgramUniform3f(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3fv(program, location, count, value) -> None: ...
@_f
def glProgramUniform3i(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3iv(program, location, count, value) -> None: ...
@_f
def glProgramUniform3ui(program, location, v0, v1, v2) -> None: ...
@_f
def glProgramUniform3uiv(program, location, count, value) -> None: ...
@_f
def glProgramUniform4d(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4dv(program, location, count, value) -> None: ...
@_f
def glProgramUniform4f(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4fv(program, location, count, value) -> None: ...
@_f
def glProgramUniform4i(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4iv(program, location, count, value) -> None: ...
@_f
def glProgramUniform4ui(program, location, v0, v1, v2, v3) -> None: ...
@_f
def glProgramUniform4uiv(program, location, count, value) -> None: ...
@_f
def glProgramUniformMatrix2dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x3dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x3fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x4dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix2x4fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x2dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x2fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x4dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix3x4fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x2dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x2fv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x3dv(program, location, count, transpose, value) -> None: ...
@_f
def glProgramUniformMatrix4x3fv(program, location, count, transpose, value) -> None: ...
@_f
def glReleaseShaderCompiler() -> None: ...
@_f
def glScissorArrayv(first, count, v) -> None: ...
@_f
def glScissorIndexed(index, left, bottom, width, height) -> None: ...
@_f
def glScissorIndexedv(index, v) -> None: ...
@_f
def glShaderBinary(count, shaders, binaryFormat, binary, length) -> None: ...
@_f
def glUseProgramStages(pipeline, stages, program) -> None: ...
@_f
def glValidateProgramPipeline(pipeline) -> None: ...
@_f
def glVertexAttribL1d(index, x) -> None: ...
@_f
def glVertexAttribL1dv(index, v) -> None: ...
@_f
def glVertexAttribL2d(index, x, y) -> None: ...
@_f
def glVertexAttribL2dv(index, v) -> None: ...
@_f
def glVertexAttribL3d(index, x, y, z) -> None: ...
@_f
def glVertexAttribL3dv(index, v) -> None: ...
@_f
def glVertexAttribL4d(index, x, y, z, w) -> None: ...
@_f
def glVertexAttribL4dv(index, v) -> None: ...
@_f
def glVertexAttribLPointer(index, size, type, stride, pointer) -> None: ...
@_f
def glViewportArrayv(first, count, v) -> None: ...
@_f
def glViewportIndexedf(index, x, y, w, h) -> None: ...
@_f
def glViewportIndexedfv(index, v) -> None: ...
