from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_BACK: Incomplete
GL_CLIP_DEPTH_MODE: Incomplete
GL_CLIP_ORIGIN: Incomplete
GL_COLOR_TABLE: Incomplete
GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT: Incomplete
GL_CONTEXT_LOST: Incomplete
GL_CONTEXT_RELEASE_BEHAVIOR: Incomplete
GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH: Incomplete
GL_CONVOLUTION_1D: Incomplete
GL_CONVOLUTION_2D: Incomplete
GL_GUILTY_CONTEXT_RESET: Incomplete
GL_HISTOGRAM: Incomplete
GL_INNOCENT_CONTEXT_RESET: Incomplete
GL_LOSE_CONTEXT_ON_RESET: Incomplete
GL_LOWER_LEFT: Incomplete
GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES: Incomplete
GL_MAX_CULL_DISTANCES: Incomplete
GL_MINMAX: Incomplete
GL_NEGATIVE_ONE_TO_ONE: Incomplete
GL_NONE: Incomplete
GL_NO_ERROR: Incomplete
GL_NO_RESET_NOTIFICATION: Incomplete
GL_POST_COLOR_MATRIX_COLOR_TABLE: Incomplete
GL_POST_CONVOLUTION_COLOR_TABLE: Incomplete
GL_PROXY_COLOR_TABLE: Incomplete
GL_PROXY_HISTOGRAM: Incomplete
GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE: Incomplete
GL_PROXY_POST_CONVOLUTION_COLOR_TABLE: Incomplete
GL_QUERY_BY_REGION_NO_WAIT_INVERTED: Incomplete
GL_QUERY_BY_REGION_WAIT_INVERTED: Incomplete
GL_QUERY_NO_WAIT_INVERTED: Incomplete
GL_QUERY_TARGET: Incomplete
GL_QUERY_WAIT_INVERTED: Incomplete
GL_RESET_NOTIFICATION_STRATEGY: Incomplete
GL_SEPARABLE_2D: Incomplete
GL_TEXTURE_BINDING_1D: Incomplete
GL_TEXTURE_BINDING_1D_ARRAY: Incomplete
GL_TEXTURE_BINDING_2D: Incomplete
GL_TEXTURE_BINDING_2D_ARRAY: Incomplete
GL_TEXTURE_BINDING_2D_MULTISAMPLE: Incomplete
GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY: Incomplete
GL_TEXTURE_BINDING_3D: Incomplete
GL_TEXTURE_BINDING_BUFFER: Incomplete
GL_TEXTURE_BINDING_CUBE_MAP: Incomplete
GL_TEXTURE_BINDING_CUBE_MAP_ARRAY: Incomplete
GL_TEXTURE_BINDING_RECTANGLE: Incomplete
GL_TEXTURE_TARGET: Incomplete
GL_UNKNOWN_CONTEXT_RESET: Incomplete
GL_UPPER_LEFT: Incomplete
GL_ZERO_TO_ONE: Incomplete

@_f
def glBindTextureUnit(unit, texture) -> None: ...
@_f
def glBlitNamedFramebuffer(readFramebuffer, drawFramebuffer, srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter) -> None: ...
@_f
def glCheckNamedFramebufferStatus(framebuffer, target) -> None: ...
@_f
def glClearNamedBufferData(buffer, internalformat, format, type, data) -> None: ...
@_f
def glClearNamedBufferSubData(buffer, internalformat, offset, size, format, type, data) -> None: ...
@_f
def glClearNamedFramebufferfi(framebuffer, buffer, drawbuffer, depth, stencil) -> None: ...
@_f
def glClearNamedFramebufferfv(framebuffer, buffer, drawbuffer, value) -> None: ...
@_f
def glClearNamedFramebufferiv(framebuffer, buffer, drawbuffer, value) -> None: ...
@_f
def glClearNamedFramebufferuiv(framebuffer, buffer, drawbuffer, value) -> None: ...
@_f
def glClipControl(origin, depth) -> None: ...
@_f
def glCompressedTextureSubImage1D(texture, level, xoffset, width, format, imageSize, data) -> None: ...
@_f
def glCompressedTextureSubImage2D(texture, level, xoffset, yoffset, width, height, format, imageSize, data) -> None: ...
@_f
def glCompressedTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, width, height, depth, format, imageSize, data) -> None: ...
@_f
def glCopyNamedBufferSubData(readBuffer, writeBuffer, readOffset, writeOffset, size) -> None: ...
@_f
def glCopyTextureSubImage1D(texture, level, xoffset, x, y, width) -> None: ...
@_f
def glCopyTextureSubImage2D(texture, level, xoffset, yoffset, x, y, width, height) -> None: ...
@_f
def glCopyTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, x, y, width, height) -> None: ...
@_f
def glCreateBuffers(n, buffers) -> None: ...
@_f
def glCreateFramebuffers(n, framebuffers) -> None: ...
@_f
def glCreateProgramPipelines(n, pipelines) -> None: ...
@_f
def glCreateQueries(target, n, ids) -> None: ...
@_f
def glCreateRenderbuffers(n, renderbuffers) -> None: ...
@_f
def glCreateSamplers(n, samplers) -> None: ...
@_f
def glCreateTextures(target, n, textures) -> None: ...
@_f
def glCreateTransformFeedbacks(n, ids) -> None: ...
@_f
def glCreateVertexArrays(n, arrays) -> None: ...
@_f
def glDisableVertexArrayAttrib(vaobj, index) -> None: ...
@_f
def glEnableVertexArrayAttrib(vaobj, index) -> None: ...
@_f
def glFlushMappedNamedBufferRange(buffer, offset, length) -> None: ...
@_f
def glGenerateTextureMipmap(texture) -> None: ...
@_f
def glGetCompressedTextureImage(texture, level, bufSize, pixels) -> None: ...
@_f
def glGetCompressedTextureSubImage(texture, level, xoffset, yoffset, zoffset, width, height, depth, bufSize, pixels) -> None: ...
@_f
def glGetGraphicsResetStatus() -> None: ...
@_f
def glGetNamedBufferParameteri64v(buffer, pname, params) -> None: ...
@_f
def glGetNamedBufferParameteriv(buffer, pname, params) -> None: ...
@_f
def glGetNamedBufferPointerv(buffer, pname, params) -> None: ...
@_f
def glGetNamedBufferSubData(buffer, offset, size, data) -> None: ...
@_f
def glGetNamedFramebufferAttachmentParameteriv(framebuffer, attachment, pname, params) -> None: ...
@_f
def glGetNamedFramebufferParameteriv(framebuffer, pname, param) -> None: ...
@_f
def glGetNamedRenderbufferParameteriv(renderbuffer, pname, params) -> None: ...
@_f
def glGetQueryBufferObjecti64v(id, buffer, pname, offset) -> None: ...
@_f
def glGetQueryBufferObjectiv(id, buffer, pname, offset) -> None: ...
@_f
def glGetQueryBufferObjectui64v(id, buffer, pname, offset) -> None: ...
@_f
def glGetQueryBufferObjectuiv(id, buffer, pname, offset) -> None: ...
@_f
def glGetTextureImage(texture, level, format, type, bufSize, pixels) -> None: ...
@_f
def glGetTextureLevelParameterfv(texture, level, pname, params) -> None: ...
@_f
def glGetTextureLevelParameteriv(texture, level, pname, params) -> None: ...
@_f
def glGetTextureParameterIiv(texture, pname, params) -> None: ...
@_f
def glGetTextureParameterIuiv(texture, pname, params) -> None: ...
@_f
def glGetTextureParameterfv(texture, pname, params) -> None: ...
@_f
def glGetTextureParameteriv(texture, pname, params) -> None: ...
@_f
def glGetTextureSubImage(texture, level, xoffset, yoffset, zoffset, width, height, depth, format, type, bufSize, pixels) -> None: ...
@_f
def glGetTransformFeedbacki64_v(xfb, pname, index, param) -> None: ...
@_f
def glGetTransformFeedbacki_v(xfb, pname, index, param) -> None: ...
@_f
def glGetTransformFeedbackiv(xfb, pname, param) -> None: ...
@_f
def glGetVertexArrayIndexed64iv(vaobj, index, pname, param) -> None: ...
@_f
def glGetVertexArrayIndexediv(vaobj, index, pname, param) -> None: ...
@_f
def glGetVertexArrayiv(vaobj, pname, param) -> None: ...
@_f
def glGetnColorTable(target, format, type, bufSize, table) -> None: ...
@_f
def glGetnCompressedTexImage(target, lod, bufSize, pixels) -> None: ...
@_f
def glGetnConvolutionFilter(target, format, type, bufSize, image) -> None: ...
@_f
def glGetnHistogram(target, reset, format, type, bufSize, values) -> None: ...
@_f
def glGetnMapdv(target, query, bufSize, v) -> None: ...
@_f
def glGetnMapfv(target, query, bufSize, v) -> None: ...
@_f
def glGetnMapiv(target, query, bufSize, v) -> None: ...
@_f
def glGetnMinmax(target, reset, format, type, bufSize, values) -> None: ...
@_f
def glGetnPixelMapfv(map, bufSize, values) -> None: ...
@_f
def glGetnPixelMapuiv(map, bufSize, values) -> None: ...
@_f
def glGetnPixelMapusv(map, bufSize, values) -> None: ...
@_f
def glGetnPolygonStipple(bufSize, pattern) -> None: ...
@_f
def glGetnSeparableFilter(target, format, type, rowBufSize, row, columnBufSize, column, span) -> None: ...
@_f
def glGetnTexImage(target, level, format, type, bufSize, pixels) -> None: ...
@_f
def glGetnUniformdv(program, location, bufSize, params) -> None: ...
@_f
def glGetnUniformfv(program, location, bufSize, params) -> None: ...
@_f
def glGetnUniformiv(program, location, bufSize, params) -> None: ...
@_f
def glGetnUniformuiv(program, location, bufSize, params) -> None: ...
@_f
def glInvalidateNamedFramebufferData(framebuffer, numAttachments, attachments) -> None: ...
@_f
def glInvalidateNamedFramebufferSubData(framebuffer, numAttachments, attachments, x, y, width, height) -> None: ...
@_f
def glMapNamedBuffer(buffer, access) -> None: ...
@_f
def glMapNamedBufferRange(buffer, offset, length, access) -> None: ...
@_f
def glMemoryBarrierByRegion(barriers) -> None: ...
@_f
def glNamedBufferData(buffer, size, data, usage) -> None: ...
@_f
def glNamedBufferStorage(buffer, size, data, flags) -> None: ...
@_f
def glNamedBufferSubData(buffer, offset, size, data) -> None: ...
@_f
def glNamedFramebufferDrawBuffer(framebuffer, buf) -> None: ...
@_f
def glNamedFramebufferDrawBuffers(framebuffer, n, bufs) -> None: ...
@_f
def glNamedFramebufferParameteri(framebuffer, pname, param) -> None: ...
@_f
def glNamedFramebufferReadBuffer(framebuffer, src) -> None: ...
@_f
def glNamedFramebufferRenderbuffer(framebuffer, attachment, renderbuffertarget, renderbuffer) -> None: ...
@_f
def glNamedFramebufferTexture(framebuffer, attachment, texture, level) -> None: ...
@_f
def glNamedFramebufferTextureLayer(framebuffer, attachment, texture, level, layer) -> None: ...
@_f
def glNamedRenderbufferStorage(renderbuffer, internalformat, width, height) -> None: ...
@_f
def glNamedRenderbufferStorageMultisample(renderbuffer, samples, internalformat, width, height) -> None: ...
@_f
def glReadnPixels(x, y, width, height, format, type, bufSize, data) -> None: ...
@_f
def glTextureBarrier() -> None: ...
@_f
def glTextureBuffer(texture, internalformat, buffer) -> None: ...
@_f
def glTextureBufferRange(texture, internalformat, buffer, offset, size) -> None: ...
@_f
def glTextureParameterIiv(texture, pname, params) -> None: ...
@_f
def glTextureParameterIuiv(texture, pname, params) -> None: ...
@_f
def glTextureParameterf(texture, pname, param) -> None: ...
@_f
def glTextureParameterfv(texture, pname, param) -> None: ...
@_f
def glTextureParameteri(texture, pname, param) -> None: ...
@_f
def glTextureParameteriv(texture, pname, param) -> None: ...
@_f
def glTextureStorage1D(texture, levels, internalformat, width) -> None: ...
@_f
def glTextureStorage2D(texture, levels, internalformat, width, height) -> None: ...
@_f
def glTextureStorage2DMultisample(texture, samples, internalformat, width, height, fixedsamplelocations) -> None: ...
@_f
def glTextureStorage3D(texture, levels, internalformat, width, height, depth) -> None: ...
@_f
def glTextureStorage3DMultisample(texture, samples, internalformat, width, height, depth, fixedsamplelocations) -> None: ...
@_f
def glTextureSubImage1D(texture, level, xoffset, width, format, type, pixels) -> None: ...
@_f
def glTextureSubImage2D(texture, level, xoffset, yoffset, width, height, format, type, pixels) -> None: ...
@_f
def glTextureSubImage3D(texture, level, xoffset, yoffset, zoffset, width, height, depth, format, type, pixels) -> None: ...
@_f
def glTransformFeedbackBufferBase(xfb, index, buffer) -> None: ...
@_f
def glTransformFeedbackBufferRange(xfb, index, buffer, offset, size) -> None: ...
@_f
def glUnmapNamedBuffer(buffer) -> None: ...
@_f
def glVertexArrayAttribBinding(vaobj, attribindex, bindingindex) -> None: ...
@_f
def glVertexArrayAttribFormat(vaobj, attribindex, size, type, normalized, relativeoffset) -> None: ...
@_f
def glVertexArrayAttribIFormat(vaobj, attribindex, size, type, relativeoffset) -> None: ...
@_f
def glVertexArrayAttribLFormat(vaobj, attribindex, size, type, relativeoffset) -> None: ...
@_f
def glVertexArrayBindingDivisor(vaobj, bindingindex, divisor) -> None: ...
@_f
def glVertexArrayElementBuffer(vaobj, buffer) -> None: ...
@_f
def glVertexArrayVertexBuffer(vaobj, bindingindex, buffer, offset, stride) -> None: ...
@_f
def glVertexArrayVertexBuffers(vaobj, first, count, buffers, offsets, strides) -> None: ...
