from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ALLOW_DRAW_FRG_HINT_PGI: Incomplete
GL_ALLOW_DRAW_MEM_HINT_PGI: Incomplete
GL_ALLOW_DRAW_OBJ_HINT_PGI: Incomplete
GL_ALLOW_DRAW_WIN_HINT_PGI: Incomplete
GL_ALWAYS_FAST_HINT_PGI: Incomplete
GL_ALWAYS_SOFT_HINT_PGI: Incomplete
GL_BACK_NORMALS_HINT_PGI: Incomplete
GL_CLIP_FAR_HINT_PGI: Incomplete
GL_CLIP_NEAR_HINT_PGI: Incomplete
GL_CONSERVE_MEMORY_HINT_PGI: Incomplete
GL_FULL_STIPPLE_HINT_PGI: Incomplete
GL_NATIVE_GRAPHICS_BEGIN_HINT_PGI: Incomplete
GL_NATIVE_GRAPHICS_END_HINT_PGI: Incomplete
GL_NATIVE_GRAPHICS_HANDLE_PGI: Incomplete
GL_PREFER_DOUBLEBUFFER_HINT_PGI: Incomplete
GL_RECLAIM_MEMORY_HINT_PGI: Incomplete
GL_STRICT_DEPTHFUNC_HINT_PGI: Incomplete
GL_STRICT_LIGHTING_HINT_PGI: Incomplete
GL_STRICT_SCISSOR_HINT_PGI: Incomplete
GL_WIDE_LINE_HINT_PGI: Incomplete

@_f
def glHintPGI(target, mode) -> None: ...
