from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_COLOR3_BIT_PGI: Incomplete
GL_COLOR4_BIT_PGI: Incomplete
GL_EDGEFLAG_BIT_PGI: Incomplete
GL_INDEX_BIT_PGI: Incomplete
GL_MATERIAL_SIDE_HINT_PGI: Incomplete
GL_MAT_AMBIENT_AND_DIFFUSE_BIT_PGI: Incomplete
GL_MAT_AMBIENT_BIT_PGI: Incomplete
GL_MAT_COLOR_INDEXES_BIT_PGI: Incomplete
GL_MAT_DIFFUSE_BIT_PGI: Incomplete
GL_MAT_EMISSION_BIT_PGI: Incomplete
GL_MAT_SHININESS_BIT_PGI: Incomplete
GL_MAT_SPECULAR_BIT_PGI: Incomplete
GL_MAX_VERTEX_HINT_PGI: Incomplete
GL_NORMAL_BIT_PGI: Incomplete
GL_TEXCOORD1_BIT_PGI: Incomplete
GL_TEXCOORD2_BIT_PGI: Incomplete
GL_TEXCOORD3_BIT_PGI: Incomplete
GL_TEXCOORD4_BIT_PGI: Incomplete
GL_VERTEX23_BIT_PGI: Incomplete
GL_VERTEX4_BIT_PGI: Incomplete
GL_VERTEX_CONSISTENT_HINT_PGI: Incomplete
GL_VERTEX_DATA_HINT_PGI: Incomplete
