from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_UPLOAD_GPU_MASK_NVX: Incomplete

@_f
def glAsyncCopyBufferSubDataNVX(waitSemaphoreCount, waitSemaphoreArray, fenceValueArray, readGpu, writeGpuMask, readBuffer, writeBuffer, readOffset, writeOffset, size, signalSemaphoreCount, signalSemaphoreArray, signalValueArray) -> None: ...
@_f
def glAsyncCopyImageSubDataNVX(waitSemaphoreCount, waitSemaphoreArray, waitValueArray, srcGpu, dstGpuMask, srcName, srcTarget, srcLevel, srcX, srcY, srcZ, dstName, dstTarget, dstLevel, dstX, dstY, dstZ, srcWidth, srcHeight, srcDepth, signalSemaphoreCount, signalSemaphoreArray, signalValueArray) -> None: ...
@_f
def glMulticastScissorArrayvNVX(gpu, first, count, v) -> None: ...
@_f
def glMulticastViewportArrayvNVX(gpu, first, count, v) -> None: ...
@_f
def glMulticastViewportPositionWScaleNVX(gpu, index, xcoeff, ycoeff) -> None: ...
@_f
def glUploadGpuMaskNVX(mask) -> None: ...
