from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glClientWaitSemaphoreui64NVX(fenceObjectCount, semaphoreArray, fenceValueArray) -> None: ...
@_f
def glCreateProgressFenceNVX() -> None: ...
@_f
def glSignalSemaphoreui64NVX(signalGpu, fenceObjectCount, semaphoreArray, fenceValueArray) -> None: ...
@_f
def glWaitSemaphoreui64NVX(waitGpu, fenceObjectCount, semaphoreArray, fenceValueArray) -> None: ...
