from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_SAMPLER_BINDING: Incomplete

@_f
def glBindSampler(unit, sampler) -> None: ...
@_f
def glDeleteSamplers(count, samplers) -> None: ...
@_f
def glGenSamplers(count, samplers) -> None: ...
@_f
def glGetSamplerParameterfv(sampler, pname, params) -> None: ...
@_f
def glGetSamplerParameteriv(sampler, pname, params) -> None: ...
@_f
def glIsSampler(sampler) -> None: ...
@_f
def glSamplerParameterf(sampler, pname, param) -> None: ...
@_f
def glSamplerParameterfv(sampler, pname, param) -> None: ...
@_f
def glSamplerParameteri(sampler, pname, param) -> None: ...
@_f
def glSamplerParameteriv(sampler, pname, param) -> None: ...
