from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_ARRAY_OBJECT_BUFFER_ATI: Incomplete
GL_ARRAY_OBJECT_OFFSET_ATI: Incomplete
GL_DISCARD_ATI: Incomplete
GL_DYNAMIC_ATI: Incomplete
GL_OBJECT_BUFFER_SIZE_ATI: Incomplete
GL_OBJECT_BUFFER_USAGE_ATI: Incomplete
GL_PRESERVE_ATI: Incomplete
GL_STATIC_ATI: Incomplete

@_f
def glArrayObjectATI(array, size, type, stride, buffer, offset) -> None: ...
@_f
def glFreeObjectBufferATI(buffer) -> None: ...
@_f
def glGetArrayObjectfvATI(array, pname, params) -> None: ...
@_f
def glGetArrayObjectivATI(array, pname, params) -> None: ...
@_f
def glGetObjectBufferfvATI(buffer, pname, params) -> None: ...
@_f
def glGetObjectBufferivATI(buffer, pname, params) -> None: ...
@_f
def glGetVariantArrayObjectfvATI(id, pname, params) -> None: ...
@_f
def glGetVariantArrayObjectivATI(id, pname, params) -> None: ...
@_f
def glIsObjectBufferATI(buffer) -> None: ...
@_f
def glNewObjectBufferATI(size, pointer, usage) -> None: ...
@_f
def glUpdateObjectBufferATI(buffer, offset, size, pointer, preserve) -> None: ...
@_f
def glVariantArrayObjectATI(id, type, stride, buffer, offset) -> None: ...
