from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_MAX_VERTEX_STREAMS_ATI: Incomplete
GL_VERTEX_SOURCE_ATI: Incomplete
GL_VERTEX_STREAM0_ATI: Incomplete
GL_VERTEX_STREAM1_ATI: Incomplete
GL_VERTEX_STREAM2_ATI: Incomplete
GL_VERTEX_STREAM3_ATI: Incomplete
GL_VERTEX_STREAM4_ATI: Incomplete
GL_VERTEX_STREAM5_ATI: Incomplete
GL_VERTEX_STREAM6_ATI: Incomplete
GL_VERTEX_STREAM7_ATI: Incomplete

@_f
def glClientActiveVertexStreamATI(stream) -> None: ...
@_f
def glNormalStream3bATI(stream, nx, ny, nz) -> None: ...
@_f
def glNormalStream3bvATI(stream, coords) -> None: ...
@_f
def glNormalStream3dATI(stream, nx, ny, nz) -> None: ...
@_f
def glNormalStream3dvATI(stream, coords) -> None: ...
@_f
def glNormalStream3fATI(stream, nx, ny, nz) -> None: ...
@_f
def glNormalStream3fvATI(stream, coords) -> None: ...
@_f
def glNormalStream3iATI(stream, nx, ny, nz) -> None: ...
@_f
def glNormalStream3ivATI(stream, coords) -> None: ...
@_f
def glNormalStream3sATI(stream, nx, ny, nz) -> None: ...
@_f
def glNormalStream3svATI(stream, coords) -> None: ...
@_f
def glVertexBlendEnvfATI(pname, param) -> None: ...
@_f
def glVertexBlendEnviATI(pname, param) -> None: ...
@_f
def glVertexStream1dATI(stream, x) -> None: ...
@_f
def glVertexStream1dvATI(stream, coords) -> None: ...
@_f
def glVertexStream1fATI(stream, x) -> None: ...
@_f
def glVertexStream1fvATI(stream, coords) -> None: ...
@_f
def glVertexStream1iATI(stream, x) -> None: ...
@_f
def glVertexStream1ivATI(stream, coords) -> None: ...
@_f
def glVertexStream1sATI(stream, x) -> None: ...
@_f
def glVertexStream1svATI(stream, coords) -> None: ...
@_f
def glVertexStream2dATI(stream, x, y) -> None: ...
@_f
def glVertexStream2dvATI(stream, coords) -> None: ...
@_f
def glVertexStream2fATI(stream, x, y) -> None: ...
@_f
def glVertexStream2fvATI(stream, coords) -> None: ...
@_f
def glVertexStream2iATI(stream, x, y) -> None: ...
@_f
def glVertexStream2ivATI(stream, coords) -> None: ...
@_f
def glVertexStream2sATI(stream, x, y) -> None: ...
@_f
def glVertexStream2svATI(stream, coords) -> None: ...
@_f
def glVertexStream3dATI(stream, x, y, z) -> None: ...
@_f
def glVertexStream3dvATI(stream, coords) -> None: ...
@_f
def glVertexStream3fATI(stream, x, y, z) -> None: ...
@_f
def glVertexStream3fvATI(stream, coords) -> None: ...
@_f
def glVertexStream3iATI(stream, x, y, z) -> None: ...
@_f
def glVertexStream3ivATI(stream, coords) -> None: ...
@_f
def glVertexStream3sATI(stream, x, y, z) -> None: ...
@_f
def glVertexStream3svATI(stream, coords) -> None: ...
@_f
def glVertexStream4dATI(stream, x, y, z, w) -> None: ...
@_f
def glVertexStream4dvATI(stream, coords) -> None: ...
@_f
def glVertexStream4fATI(stream, x, y, z, w) -> None: ...
@_f
def glVertexStream4fvATI(stream, coords) -> None: ...
@_f
def glVertexStream4iATI(stream, x, y, z, w) -> None: ...
@_f
def glVertexStream4ivATI(stream, coords) -> None: ...
@_f
def glVertexStream4sATI(stream, x, y, z, w) -> None: ...
@_f
def glVertexStream4svATI(stream, coords) -> None: ...
