from OpenGL import constant as constant
from OpenGL.arrays import formathandler as formathandler
from _typeshed import Incomplete

REGISTRY_NAME: str

class CtypesPointerHandler(formathandler.FormatHandler):
    @classmethod
    def from_param(cls, value, typeCode=None): ...
    @classmethod
    def dataPointer(cls, value): ...
    HANDLED_TYPES: Incomplete
    isOutput: bool
    def voidDataPointer(cls, value): ...
    def zeros(self, dims, typeCode) -> None: ...
    def ones(self, dims, typeCode: str = 'd') -> None: ...
    def arrayToGLType(self, value): ...
    def arraySize(self, value, typeCode=None) -> None: ...
    def asArray(self, value, typeCode=None): ...
    def unitSize(self, value, typeCode=None): ...
    def dimensions(self, value, typeCode=None) -> None: ...

ARRAY_TO_GL_TYPE_MAPPING: Incomplete
GL_TYPE_TO_ARRAY_MAPPING: Incomplete
