from OpenGL import constant as constant
from OpenGL._bytes import bytes as bytes, unicode as unicode
from OpenGL.arrays import formathandler as formathandler
from _typeshed import Incomplete
from collections.abc import Generator

REGISTRY_NAME: str

class CtypesArrayHandler(formathandler.FormatHandler):
    @classmethod
    def from_param(cls, value, typeCode=None): ...
    dataPointer: Incomplete
    HANDLED_TYPES: Incomplete
    isOutput: bool
    @classmethod
    def voidDataPointer(cls, value): ...
    @classmethod
    def zeros(cls, dims, typeCode): ...
    @classmethod
    def ones(cls, dims, typeCode: str = 'd') -> None: ...
    @classmethod
    def arrayToGLType(cls, value): ...
    @classmethod
    def arraySize(cls, value, typeCode=None): ...
    @classmethod
    def arrayByteCount(cls, value, typeCode=None): ...
    @classmethod
    def types(cls, value) -> Generator[Incomplete]: ...
    @classmethod
    def dims(cls, value): ...
    @classmethod
    def asArray(cls, value, typeCode=None): ...
    @classmethod
    def unitSize(cls, value, typeCode=None): ...
    @classmethod
    def dimensions(cls, value, typeCode=None): ...

ARRAY_TO_GL_TYPE_MAPPING: Incomplete
GL_TYPE_TO_ARRAY_MAPPING: Incomplete
