from OpenGL import constant as constant
from OpenGL._bytes import as_8_bit as as_8_bit, bytes as bytes, unicode as unicode
from OpenGL.arrays import formathandler as formathandler
from _typeshed import Incomplete
from collections.abc import Generator

REGISTRY_NAME: str
c: Incomplete
ParamaterType: Incomplete
DIRECT_RETURN_TYPES: Incomplete

class CtypesParameterHandler(formathandler.FormatHandler):
    isOutput: bool
    HANDLED_TYPES: Incomplete
    def from_param(cls, value, typeCode=None): ...
    from_param: Incomplete
    voidDataPointer: Incomplete
    def dataPointer(cls, value): ...
    dataPointer: Incomplete
    def zeros(self, dims, typeCode): ...
    def ones(self, dims, typeCode: str = 'd') -> None: ...
    def arrayToGLType(self, value): ...
    def arraySize(self, value, typeCode=None): ...
    def arrayByteCount(self, value, typeCode=None): ...
    def types(self, value) -> Generator[Incomplete]: ...
    def dims(self, value) -> Generator[Incomplete]: ...
    def asArray(self, value, typeCode=None): ...
    def unitSize(self, value, typeCode=None): ...
    def dimensions(self, value, typeCode=None): ...

ARRAY_TO_GL_TYPE_MAPPING: Incomplete
GL_TYPE_TO_ARRAY_MAPPING: Incomplete
