from OpenGL import plugins as plugins
from _typeshed import Incomplete

class FormatHandler:
    LAZY_TYPE_REGISTRY: Incomplete
    HANDLER_REGISTRY: Incomplete
    baseType: Incomplete
    typeConstant: Incomplete
    HANDLED_TYPES: Incomplete
    preferredOutput: Incomplete
    isOutput: bool
    GENERIC_OUTPUT_PREFERENCES: Incomplete
    ALL_OUTPUT_HANDLERS: Incomplete
    def loadAll(cls) -> None: ...
    @classmethod
    def loadPlugin(cls, entrypoint): ...
    @classmethod
    def typeLookup(cls, type): ...
    loadAll: Incomplete
    def register(self, types=None) -> None: ...
    def registerReturn(self) -> None: ...
    def from_param(self, value, typeCode=None) -> None: ...
    def dataPointer(self, value) -> None: ...
    def asArray(self, value, typeCode=None) -> None: ...
    def arrayToGLType(self, value) -> None: ...
    def arraySize(self, value, typeCode=None) -> None: ...
    def unitSize(self, value, typeCode=None) -> None: ...
    def dimensions(self, value, typeCode=None) -> None: ...
