from OpenGL import acceleratesupport as acceleratesupport
from OpenGL.arrays import formathandler as formathandler
from _typeshed import Incomplete

REGISTRY_NAME: str
NoneHandler: Incomplete

class NoneHandler(formathandler.FormatHandler):
    HANDLED_TYPES: Incomplete
    def from_param(self, value, typeCode=None) -> None: ...
    def dataPointer(self, value) -> None: ...
    def voidDataPointer(cls, value) -> None: ...
    def asArray(self, value, typeCode=None) -> None: ...
    def arrayToGLType(self, value) -> None: ...
    def arraySize(self, value, typeCode=None): ...
    def arrayByteCount(self, value, typeCode=None): ...
    def zeros(self, shape, typeCode=None) -> None: ...
    def ones(self, shape, typeCode=None) -> None: ...
    def unitSize(self, value, typeCode=None) -> None: ...
    def dimensions(self, value, typeCode=None): ...
