from OpenGL import error as error
from OpenGL._configflags import ERROR_ON_COPY as ERROR_ON_COPY
from OpenGL.arrays import formathandler as formathandler
from OpenGL.raw.GL.VERSION import GL_1_1 as GL_1_1
from _typeshed import Incomplete

def dataPointer(value, typeCode=None): ...

class StringHandler(formathandler.FormatHandler):
    HANDLED_TYPES: Incomplete
    @classmethod
    def from_param(cls, value, typeCode=None): ...
    dataPointer: Incomplete
    def zeros(self, dims, typeCode=None) -> None: ...
    def ones(self, dims, typeCode=None) -> None: ...
    def arrayToGLType(self, value) -> None: ...
    def arraySize(self, value, typeCode=None): ...
    def arrayByteCount(self, value, typeCode=None): ...
    def asArray(self, value, typeCode=None): ...
    def dimensions(self, value, typeCode=None) -> None: ...

class UnicodeHandler(StringHandler):
    HANDLED_TYPES: Incomplete
    @classmethod
    def from_param(cls, value, typeCode=None): ...
    def asArray(self, value, typeCode=None): ...

BYTE_SIZES: Incomplete
