from OpenGL.arrays.formathandler import FormatHandler
from OpenGL_accelerate.vbo import VBO as VBO, VBOHandler as VBOHandler
from _typeshed import Incomplete

__all__ = ['VBO', 'VBOHandler', 'mapVBO']

class Implementation:
    IMPLEMENTATION_CLASSES: Incomplete
    CHOSEN: Incomplete
    @classmethod
    def register(cls) -> None: ...
    @classmethod
    def get_implementation(cls, *args): ...
    EXPORTED_NAMES: Incomplete
    available: bool
    def basename(self, name): ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__
    def deleter(self, buffers, key): ...

VBO: Incomplete

class VBO:
    copied: bool
    usage: Incomplete
    target: Incomplete
    buffers: Incomplete
    def __init__(self, data, usage: str = 'GL_DYNAMIC_DRAW', target: str = 'GL_ARRAY_BUFFER', size=None) -> None: ...
    implementation: Incomplete
    def resolve(self, value): ...
    data: Incomplete
    size: Incomplete
    def set_array(self, data, size=None) -> None: ...
    def __setitem__(self, slice, array) -> None: ...
    def __len__(self) -> int: ...
    def __getattr__(self, key): ...
    def create_buffers(self): ...
    def copy_data(self) -> None: ...
    def delete(self) -> None: ...
    def __int__(self) -> int: ...
    def bind(self) -> None: ...
    def unbind(self) -> None: ...
    def __add__(self, other): ...
    __enter__ = bind
    def __exit__(self, exc_type=None, exc_val=None, exc_tb=None): ...

class VBOOffset:
    vbo: Incomplete
    offset: Incomplete
    def __init__(self, vbo, offset) -> None: ...
    def __getattr__(self, key): ...
    def __add__(self, other): ...

class VBOHandler(FormatHandler):
    vp0: Incomplete
    def dataPointer(self, instance): ...
    def from_param(self, instance, typeCode=None): ...
    def zeros(self, dims, typeCode) -> None: ...
    ones = zeros
    def asArray(self, value, typeCode=None): ...
    def arrayToGLType(self, value): ...
    def arrayByteCount(self, value): ...
    def arraySize(self, value, typeCode=None): ...
    def unitSize(self, value, typeCode=None): ...
    def dimensions(self, value, typeCode=None): ...

class VBOOffsetHandler(VBOHandler):
    def dataPointer(self, instance): ...
    def from_param(self, instance, typeCode=None): ...

def mapVBO(vbo, access: int = 35002): ...
