from ctypes import *
from _typeshed import Incomplete

__all__ = ['GLE_TEXTURE_ENABLE', 'GLE_TEXTURE_NORMAL_CYL', 'GLE_TEXTURE_NORMAL_FLAT', 'GLE_TEXTURE_NORMAL_MODEL_CYL', 'GLE_TEXTURE_NORMAL_MODEL_FLAT', 'GLE_TEXTURE_NORMAL_MODEL_SPH', 'GLE_TEXTURE_NORMAL_SPH', 'GLE_TEXTURE_STYLE_MASK', 'GLE_TEXTURE_VERTEX_CYL', 'GLE_TEXTURE_VERTEX_FLAT', 'GLE_TEXTURE_VERTEX_MODEL_CYL', 'GLE_TEXTURE_VERTEX_MODEL_FLAT', 'GLE_TEXTURE_VERTEX_MODEL_SPH', 'GLE_TEXTURE_VERTEX_SPH', 'TUBE_CONTOUR_CLOSED', 'TUBE_JN_ANGLE', 'TUBE_JN_CAP', 'TUBE_JN_CUT', 'TUBE_JN_MASK', 'TUBE_JN_RAW', 'TUBE_JN_ROUND', 'TUBE_NORM_EDGE', 'TUBE_NORM_FACET', 'TUBE_NORM_MASK', 'TUBE_NORM_PATH_EDGE', '__GLE_DOUBLE']

GLE_TEXTURE_ENABLE: Incomplete
GLE_TEXTURE_NORMAL_CYL: Incomplete
GLE_TEXTURE_NORMAL_FLAT: Incomplete
GLE_TEXTURE_NORMAL_MODEL_CYL: Incomplete
GLE_TEXTURE_NORMAL_MODEL_FLAT: Incomplete
GLE_TEXTURE_NORMAL_MODEL_SPH: Incomplete
GLE_TEXTURE_NORMAL_SPH: Incomplete
GLE_TEXTURE_STYLE_MASK: Incomplete
GLE_TEXTURE_VERTEX_CYL: Incomplete
GLE_TEXTURE_VERTEX_FLAT: Incomplete
GLE_TEXTURE_VERTEX_MODEL_CYL: Incomplete
GLE_TEXTURE_VERTEX_MODEL_FLAT: Incomplete
GLE_TEXTURE_VERTEX_MODEL_SPH: Incomplete
GLE_TEXTURE_VERTEX_SPH: Incomplete
TUBE_CONTOUR_CLOSED: Incomplete
TUBE_JN_ANGLE: Incomplete
TUBE_JN_CAP: Incomplete
TUBE_JN_CUT: Incomplete
TUBE_JN_MASK: Incomplete
TUBE_JN_RAW: Incomplete
TUBE_JN_ROUND: Incomplete
TUBE_NORM_EDGE: Incomplete
TUBE_NORM_FACET: Incomplete
TUBE_NORM_MASK: Incomplete
TUBE_NORM_PATH_EDGE: Incomplete
__GLE_DOUBLE: Incomplete
