from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays

@_f
def glGetTextureHandleIMG(texture) -> None: ...
@_f
def glGetTextureSamplerHandleIMG(texture, sampler) -> None: ...
@_f
def glProgramUniformHandleui64IMG(program, location, value) -> None: ...
@_f
def glProgramUniformHandleui64vIMG(program, location, count, values) -> None: ...
@_f
def glUniformHandleui64IMG(location, value) -> None: ...
@_f
def glUniformHandleui64vIMG(location, count, value) -> None: ...
