from OpenGL.raw.GL._types import *
from OpenGL import arrays as arrays

@_f
def glWindowPos2dMESA(x, y) -> None: ...
@_f
def glWindowPos2dvMESA(v) -> None: ...
@_f
def glWindowPos2fMESA(x, y) -> None: ...
@_f
def glWindowPos2fvMESA(v) -> None: ...
@_f
def glWindowPos2iMESA(x, y) -> None: ...
@_f
def glWindowPos2ivMESA(v) -> None: ...
@_f
def glWindowPos2sMESA(x, y) -> None: ...
@_f
def glWindowPos2svMESA(v) -> None: ...
@_f
def glWindowPos3dMESA(x, y, z) -> None: ...
@_f
def glWindowPos3dvMESA(v) -> None: ...
@_f
def glWindowPos3fMESA(x, y, z) -> None: ...
@_f
def glWindowPos3fvMESA(v) -> None: ...
@_f
def glWindowPos3iMESA(x, y, z) -> None: ...
@_f
def glWindowPos3ivMESA(v) -> None: ...
@_f
def glWindowPos3sMESA(x, y, z) -> None: ...
@_f
def glWindowPos3svMESA(v) -> None: ...
@_f
def glWindowPos4dMESA(x, y, z, w) -> None: ...
@_f
def glWindowPos4dvMESA(v) -> None: ...
@_f
def glWindowPos4fMESA(x, y, z, w) -> None: ...
@_f
def glWindowPos4fvMESA(v) -> None: ...
@_f
def glWindowPos4iMESA(x, y, z, w) -> None: ...
@_f
def glWindowPos4ivMESA(v) -> None: ...
@_f
def glWindowPos4sMESA(x, y, z, w) -> None: ...
@_f
def glWindowPos4svMESA(v) -> None: ...
