from OpenGL.raw.GLES1._types import *
from OpenGL import arrays as arrays

@_f
def glDisableDriverControlQCOM(driverControl) -> None: ...
@_f
def glEnableDriverControlQCOM(driverControl) -> None: ...
@_f
def glGetDriverControlStringQCOM(driverControl, bufSize, length, driverControlString) -> None: ...
@_f
def glGetDriverControlsQCOM(num, size, driverControls) -> None: ...
