from OpenGL.raw.GLES1._types import *
from OpenGL import arrays as arrays

@_f
def glExtGetProgramBinarySourceQCOM(program, shadertype, source, length) -> None: ...
@_f
def glExtGetProgramsQCOM(programs, maxPrograms, numPrograms) -> None: ...
@_f
def glExtGetShadersQCOM(shaders, maxShaders, numShaders) -> None: ...
@_f
def glExtIsProgramBinaryQCOM(program) -> None: ...
