from OpenGL.raw.GLES1._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_COLOR_BUFFER_BIT0_QCOM: Incomplete
GL_COLOR_BUFFER_BIT1_QCOM: Incomplete
GL_COLOR_BUFFER_BIT2_QCOM: Incomplete
GL_COLOR_BUFFER_BIT3_QCOM: Incomplete
GL_COLOR_BUFFER_BIT4_QCOM: Incomplete
GL_COLOR_BUFFER_BIT5_QCOM: Incomplete
GL_COLOR_BUFFER_BIT6_QCOM: Incomplete
GL_COLOR_BUFFER_BIT7_QCOM: Incomplete
GL_DEPTH_BUFFER_BIT0_QCOM: Incomplete
GL_DEPTH_BUFFER_BIT1_QCOM: Incomplete
GL_DEPTH_BUFFER_BIT2_QCOM: Incomplete
GL_DEPTH_BUFFER_BIT3_QCOM: Incomplete
GL_DEPTH_BUFFER_BIT4_QCOM: Incomplete
GL_DEPTH_BUFFER_BIT5_QCOM: Incomplete
GL_DEPTH_BUFFER_BIT6_QCOM: Incomplete
GL_DEPTH_BUFFER_BIT7_QCOM: Incomplete
GL_MULTISAMPLE_BUFFER_BIT0_QCOM: Incomplete
GL_MULTISAMPLE_BUFFER_BIT1_QCOM: Incomplete
GL_MULTISAMPLE_BUFFER_BIT2_QCOM: Incomplete
GL_MULTISAMPLE_BUFFER_BIT3_QCOM: Incomplete
GL_MULTISAMPLE_BUFFER_BIT4_QCOM: Incomplete
GL_MULTISAMPLE_BUFFER_BIT5_QCOM: Incomplete
GL_MULTISAMPLE_BUFFER_BIT6_QCOM: Incomplete
GL_MULTISAMPLE_BUFFER_BIT7_QCOM: Incomplete
GL_STENCIL_BUFFER_BIT0_QCOM: Incomplete
GL_STENCIL_BUFFER_BIT1_QCOM: Incomplete
GL_STENCIL_BUFFER_BIT2_QCOM: Incomplete
GL_STENCIL_BUFFER_BIT3_QCOM: Incomplete
GL_STENCIL_BUFFER_BIT4_QCOM: Incomplete
GL_STENCIL_BUFFER_BIT5_QCOM: Incomplete
GL_STENCIL_BUFFER_BIT6_QCOM: Incomplete
GL_STENCIL_BUFFER_BIT7_QCOM: Incomplete

@_f
def glEndTilingQCOM(preserveMask) -> None: ...
@_f
def glStartTilingQCOM(x, y, width, height, preserveMask) -> None: ...
