from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays

@_f
def glDrawVkImageNV(vkImage, sampler, x0, y0, x1, y1, z, s0, t0, s1, t1) -> None: ...
@_f
def glGetVkProcAddrNV(name) -> None: ...
@_f
def glSignalVkFenceNV(vkFence) -> None: ...
@_f
def glSignalVkSemaphoreNV(vkSemaphore) -> None: ...
@_f
def glWaitVkSemaphoreNV(vkSemaphore) -> None: ...
