from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays

@_f
def glBufferPageCommitmentMemNV(target, offset, size, memory, memOffset, commit) -> None: ...
@_f
def glNamedBufferPageCommitmentMemNV(buffer, offset, size, memory, memOffset, commit) -> None: ...
@_f
def glTexPageCommitmentMemNV(target, layer, level, xoffset, yoffset, zoffset, width, height, depth, memory, offset, commit) -> None: ...
@_f
def glTexturePageCommitmentMemNV(texture, layer, level, xoffset, yoffset, zoffset, width, height, depth, memory, offset, commit) -> None: ...
