from OpenGL.raw.GLES2._types import *
from OpenGL import arrays as arrays
from _typeshed import Incomplete

GL_DEPTH_RANGE: Incomplete
GL_MAX_VIEWPORTS_NV: Incomplete
GL_SCISSOR_BOX: Incomplete
GL_SCISSOR_TEST: Incomplete
GL_VIEWPORT: Incomplete
GL_VIEWPORT_BOUNDS_RANGE_NV: Incomplete
GL_VIEWPORT_INDEX_PROVOKING_VERTEX_NV: Incomplete
GL_VIEWPORT_SUBPIXEL_BITS_NV: Incomplete

@_f
def glDepthRangeArrayfvNV(first, count, v) -> None: ...
@_f
def glDepthRangeIndexedfNV(index, n, f) -> None: ...
@_f
def glDisableiNV(target, index) -> None: ...
@_f
def glEnableiNV(target, index) -> None: ...
@_f
def glGetFloati_vNV(target, index, data) -> None: ...
@_f
def glIsEnablediNV(target, index) -> None: ...
@_f
def glScissorArrayvNV(first, count, v) -> None: ...
@_f
def glScissorIndexedNV(index, left, bottom, width, height) -> None: ...
@_f
def glScissorIndexedvNV(index, v) -> None: ...
@_f
def glViewportArrayvNV(first, count, v) -> None: ...
@_f
def glViewportIndexedfNV(index, x, y, w, h) -> None: ...
@_f
def glViewportIndexedfvNV(index, v) -> None: ...
