from OpenGL.raw.GL.VERSION.GL_1_0 import *
from OpenGL import arrays as arrays, constant as constant, extensions as extensions, platform as platform, wrapper as wrapper
from _typeshed import Incomplete

def glInitGl10VERSION(): ...

glTexParameterfv: Incomplete
glTexParameteriv: Incomplete
glTexImage1D: Incomplete
glTexImage2D: Incomplete
glGetBooleanv: Incomplete
glGetDoublev: Incomplete
glGetFloatv: Incomplete
glGetIntegerv: Incomplete
glGetTexParameterfv: Incomplete
glGetTexParameteriv: Incomplete
glGetTexLevelParameterfv: Incomplete
glGetTexLevelParameteriv: Incomplete
glCallLists: Incomplete
glBitmap: Incomplete
glColor3bv: Incomplete
glColor3dv: Incomplete
glColor3fv: Incomplete
glColor3iv: Incomplete
glColor3sv: Incomplete
glColor3ubv: Incomplete
glColor3uiv: Incomplete
glColor3usv: Incomplete
glColor4bv: Incomplete
glColor4dv: Incomplete
glColor4fv: Incomplete
glColor4iv: Incomplete
glColor4sv: Incomplete
glColor4ubv: Incomplete
glColor4uiv: Incomplete
glColor4usv: Incomplete
glEdgeFlagv: Incomplete
glIndexdv: Incomplete
glIndexfv: Incomplete
glIndexiv: Incomplete
glIndexsv: Incomplete
glNormal3bv: Incomplete
glNormal3dv: Incomplete
glNormal3fv: Incomplete
glNormal3iv: Incomplete
glNormal3sv: Incomplete
glRasterPos2dv: Incomplete
glRasterPos2fv: Incomplete
glRasterPos2iv: Incomplete
glRasterPos2sv: Incomplete
glRasterPos3dv: Incomplete
glRasterPos3fv: Incomplete
glRasterPos3iv: Incomplete
glRasterPos3sv: Incomplete
glRasterPos4dv: Incomplete
glRasterPos4fv: Incomplete
glRasterPos4iv: Incomplete
glRasterPos4sv: Incomplete
glRectdv: Incomplete
glRectfv: Incomplete
glRectiv: Incomplete
glRectsv: Incomplete
glTexCoord1dv: Incomplete
glTexCoord1fv: Incomplete
glTexCoord1iv: Incomplete
glTexCoord1sv: Incomplete
glTexCoord2dv: Incomplete
glTexCoord2fv: Incomplete
glTexCoord2iv: Incomplete
glTexCoord2sv: Incomplete
glTexCoord3dv: Incomplete
glTexCoord3fv: Incomplete
glTexCoord3iv: Incomplete
glTexCoord3sv: Incomplete
glTexCoord4dv: Incomplete
glTexCoord4fv: Incomplete
glTexCoord4iv: Incomplete
glTexCoord4sv: Incomplete
glVertex2dv: Incomplete
glVertex2fv: Incomplete
glVertex2iv: Incomplete
glVertex2sv: Incomplete
glVertex3dv: Incomplete
glVertex3fv: Incomplete
glVertex3iv: Incomplete
glVertex3sv: Incomplete
glVertex4dv: Incomplete
glVertex4fv: Incomplete
glVertex4iv: Incomplete
glVertex4sv: Incomplete
glClipPlane: Incomplete
glFogfv: Incomplete
glFogiv: Incomplete
glLightfv: Incomplete
glLightiv: Incomplete
glLightModelfv: Incomplete
glLightModeliv: Incomplete
glMaterialfv: Incomplete
glMaterialiv: Incomplete
glPolygonStipple: Incomplete
glTexEnvfv: Incomplete
glTexEnviv: Incomplete
glTexGendv: Incomplete
glTexGenfv: Incomplete
glTexGeniv: Incomplete
glFeedbackBuffer: Incomplete
glSelectBuffer: Incomplete
glMap1d: Incomplete
glMap1f: Incomplete
glMap2d: Incomplete
glMap2f: Incomplete
glEvalCoord1dv: Incomplete
glEvalCoord1fv: Incomplete
glEvalCoord2dv: Incomplete
glEvalCoord2fv: Incomplete
glPixelMapfv: Incomplete
glPixelMapuiv: Incomplete
glPixelMapusv: Incomplete
glDrawPixels: Incomplete
glGetClipPlane: Incomplete
glGetLightfv: Incomplete
glGetLightiv: Incomplete
glGetMaterialfv: Incomplete
glGetMaterialiv: Incomplete
glGetPixelMapfv: Incomplete
glGetPixelMapuiv: Incomplete
glGetPixelMapusv: Incomplete
glGetPolygonStipple: Incomplete
glGetTexEnvfv: Incomplete
glGetTexEnviv: Incomplete
glGetTexGendv: Incomplete
glGetTexGenfv: Incomplete
glGetTexGeniv: Incomplete
glLoadMatrixf: Incomplete
glLoadMatrixd: Incomplete
glMultMatrixf: Incomplete
glMultMatrixd: Incomplete
